Repository alpaka-group/alpaka, pull requests merged in 2018-09, with the labels that each got.

#630 Add a check for OpenMP version
  alpakaConfig.cmake
Labels: backend-OpenMP

#619 Reduction example
  example/CMakeLists.txt
  example/reduce/CMakeLists.txt
  example/reduce/README.md
  example/reduce/src/alpakaConfig.hpp
  example/reduce/src/iterator.hpp
  example/reduce/src/kernel.hpp
  example/reduce/src/reduce.cpp
Labels: example

#633 Added prepareForAsyncCopy trait and specialization for cpu and cuda memory
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/mem/buf/BufCudaRt.hpp
  include/alpaka/mem/buf/Traits.hpp
Labels: backend-Boost.Fiber, backend-OpenMP, backend-TBB, backend-std::thread, enhancement

#635 Add compile-time error for atomic CUDA ops which are not available due to sm restrictions
  include/alpaka/atomic/AtomicCudaBuiltIn.hpp
Labels: enhancement

#636 Test ubuntu 18.04
  .travis.yml
  script/travis/docker_install.sh
  script/travis/install_cuda.sh
Labels: testing

#627 Fix empty(QueueCpuAsync) returning true even though the last task is still executing
  include/alpaka/core/ConcurrentExecPool.hpp
  include/alpaka/event/EventCpu.hpp
  include/alpaka/queue/QueueCpuAsync.hpp
  include/alpaka/queue/QueueCpuSync.hpp
  include/alpaka/queue/QueueCudaRtSync.hpp
  test/unit/event/src/EventTest.cpp
  test/unit/queue/src/QueueTest.cpp
Labels: backend-OpenMP, bug, work in progress

#646 Fix static_casts leading to overflows.
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGpuCudaRt.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/core/ClipCast.hpp
  include/alpaka/mem/buf/cpu/Copy.hpp
  include/alpaka/mem/buf/cpu/Set.hpp
  include/alpaka/meta/Integral.hpp
  include/alpaka/meta/IsIntegralSuperset.hpp
  test/common/include/alpaka/test/KernelExecutionFixture.hpp
  test/unit/core/src/ClipCastTest.cpp
  test/unit/meta/src/IntegralTest.cpp
  test/unit/meta/src/IsIntegralSupersetTest.cpp
Labels: backend-Boost.Fiber, backend-CUDA, backend-OpenMP, backend-std::thread, bug

#648 Fix tests using std::int16_t overflowing
  test/unit/mem/buf/src/BufTest.cpp
  test/unit/mem/p2p/src/P2P.cpp
  test/unit/mem/view/src/ViewSubViewTest.cpp
Labels: backend-CUDA, bug

#649 Fix warning about comparison unsigned < 0
  include/alpaka/core/Assert.hpp
  include/alpaka/vec/Vec.hpp
Labels: warning

#650 CUDA: Math & Public Headers
  include/alpaka/math/abs/AbsCudaBuiltIn.hpp
  include/alpaka/math/acos/AcosCudaBuiltIn.hpp
  include/alpaka/math/asin/AsinCudaBuiltIn.hpp
  include/alpaka/math/atan/AtanCudaBuiltIn.hpp
  include/alpaka/math/atan2/Atan2CudaBuiltIn.hpp
  include/alpaka/math/ceil/CeilCudaBuiltIn.hpp
  include/alpaka/math/cos/CosCudaBuiltIn.hpp
  include/alpaka/math/erf/ErfCudaBuiltIn.hpp
  include/alpaka/math/exp/ExpCudaBuiltIn.hpp
  include/alpaka/math/floor/FloorCudaBuiltIn.hpp
  include/alpaka/math/fmod/FmodCudaBuiltIn.hpp
  include/alpaka/math/log/LogCudaBuiltIn.hpp
  include/alpaka/math/max/MaxCudaBuiltIn.hpp
  include/alpaka/math/min/MinCudaBuiltIn.hpp
  include/alpaka/math/pow/PowCudaBuiltIn.hpp
  include/alpaka/math/remainder/RemainderCudaBuiltIn.hpp
  include/alpaka/math/round/RoundCudaBuiltIn.hpp
  include/alpaka/math/rsqrt/RsqrtCudaBuiltIn.hpp
  include/alpaka/math/sin/SinCudaBuiltIn.hpp
  include/alpaka/math/sqrt/SqrtCudaBuiltIn.hpp
  include/alpaka/math/tan/TanCudaBuiltIn.hpp
  include/alpaka/math/trunc/TruncCudaBuiltIn.hpp
Labels: backend-CUDA, warning

#641 CMake: Options Experimental NVCC Flags
  .travis.yml
  alpakaConfig.cmake
  script/travis/run_build.sh
  test/unit/kernel/src/KernelLambda.cpp
  test/unit/kernel/src/KernelWithHostConstexpr.cpp
Labels: backend-CUDA, enhancement

#654 Add support for CUDA 10.0
  .travis.yml
  README.md
  script/travis/install_cuda.sh
Labels: backend-CUDA, enhancement

#658 Add support for clang 7
  .travis.yml
  README.md
  alpakaConfig.cmake
Labels: enhancement, testing

#660 Initialize result vector (vectorAdd). cout -> cerr.
  example/reduce/src/reduce.cpp
  example/vectorAdd/src/main.cpp
  test/integ/axpy/src/main.cpp
  test/integ/mandelbrot/src/main.cpp
  test/integ/matMul/src/main.cpp
  test/integ/sharedMem/src/main.cpp
Labels: testing

#661 Change ALPAKA_ADD_EXECUTABLE|LIBRARY to CMake macros.
  cmake/addExecutable.cmake
  cmake/addLibrary.cmake
Labels: refactoring

#662 Replace assert with ALPAKA_ASSERT
  example/bufferCopy/src/bufferCopy.cpp
  include/alpaka/core/Assert.hpp
  include/alpaka/event/EventCpu.hpp
  include/alpaka/idx/bt/IdxBtOmp.hpp
  include/alpaka/idx/bt/IdxBtRefFiberIdMap.hpp
  include/alpaka/idx/bt/IdxBtRefThreadIdMap.hpp
  include/alpaka/mem/buf/BufCudaRt.hpp
  include/alpaka/mem/buf/cpu/Copy.hpp
  include/alpaka/mem/buf/cpu/Set.hpp
  include/alpaka/mem/buf/cuda/Copy.hpp
  include/alpaka/mem/buf/cuda/Set.hpp
  include/alpaka/mem/view/ViewSubView.hpp
  include/alpaka/workdiv/WorkDivHelpers.hpp
  test/common/include/alpaka/test/event/EventHostManualTrigger.hpp
  test/integ/mandelbrot/src/main.cpp
  test/integ/matMul/src/main.cpp
Labels: refactoring
