Repository alpaka-group/alpaka, pull requests merged in 2018-04, with the labels that each got.

#471 add support for clang 6, remove 3.x and fix OpenMP 4.0
  .travis.yml
  README.md
  alpakaConfig.cmake
  example/helloWorldLambda/src/helloWorldLambda.cpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/core/OpenMp.hpp
  include/alpaka/exec/ExecCpuOmp2Blocks.hpp
  include/alpaka/exec/ExecCpuOmp2Threads.hpp
  include/alpaka/exec/ExecCpuOmp4.hpp
  include/alpaka/idx/bt/IdxBtOmp.hpp
  script/travis/before_install.sh
  script/travis/compileExec.sh
  script/travis/docker_install.sh
  script/travis/docker_run.sh
  script/travis/install_boost.sh
  script/travis/install_clang.sh
  script/travis/prepare_sanitizers.sh
  test/unit/kernel/src/KernelLambda.cpp
Labels: testing

#472 exclude test from appveyor CI build due to out-of-memory crashes
  .travis.yml
  appveyor.yml
  script/travis/compileExec.sh
  test/unit/mem/view/CMakeLists.txt
Labels: testing

#452 test boost 1 66
  .travis.yml
  appveyor.yml
Labels: testing

#473 test CMake 3.11.0
  .travis.yml
Labels: testing

#475 Tests: Fix Undefined Define
  test/unit/atomic/src/AtomicTest.cpp
  test/unit/kernel/src/KernelLambda.cpp
Labels: bug, example

#476 CMake: Root Options
  CMakeLists.txt
  test/analysis/headerCheck/CMakeLists.txt
  test/integ/cudaOnly/CMakeLists.txt
  test/unit/acc/CMakeLists.txt
  test/unit/atomic/CMakeLists.txt
  test/unit/block/shared/CMakeLists.txt
  test/unit/block/sync/CMakeLists.txt
  test/unit/event/CMakeLists.txt
  test/unit/idx/CMakeLists.txt
  test/unit/kernel/CMakeLists.txt
  test/unit/mem/buf/CMakeLists.txt
  test/unit/mem/view/CMakeLists.txt
  test/unit/meta/CMakeLists.txt
  test/unit/queue/CMakeLists.txt
  test/unit/rand/CMakeLists.txt
  test/unit/time/CMakeLists.txt
  test/unit/vec/CMakeLists.txt
Labels: install, refactoring

#477 CMake: Unify Requirement of 3.7.0+
  cmake/addExecutable.cmake
  cmake/addLibrary.cmake
  example/CMakeLists.txt
  test/CMakeLists.txt
  test/analysis/CMakeLists.txt
  test/integ/CMakeLists.txt
  test/unit/CMakeLists.txt
Labels: install, refactoring

#479 Boost: Use CMake Targets
  alpakaConfig.cmake
  script/travis/install_boost.sh
Labels: install, refactoring
