Repository alpaka-group/alpaka, pull requests merged in 2018-07, with the labels that each got.

#553 Add test for const ViewSubView and clean up handling of such memory operations
  include/alpaka/mem/buf/cpu/Copy.hpp
  include/alpaka/mem/buf/cpu/Set.hpp
  include/alpaka/mem/buf/cuda/Copy.hpp
  include/alpaka/mem/buf/cuda/Set.hpp
  test/common/include/alpaka/test/mem/view/ViewTest.hpp
  test/unit/mem/buf/src/BufTest.cpp
  test/unit/mem/view/src/ViewSubViewTest.cpp
Labels: refactoring, testing

#555 Extend BlockSharedMemSt tests to better exhibit faulty implementations
  test/unit/block/shared/src/BlockSharedMemSt.cpp
Labels: testing

#547 Fix VS2017 CUDA build
  alpakaConfig.cmake
  appveyor.yml
  cmake/dev.cmake
  example/bufferCopy/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  include/alpaka/exec/ExecGpuCudaRt.hpp
  include/alpaka/mem/buf/BufCudaRt.hpp
  include/alpaka/vec/Vec.hpp
  test/common/commonConfig.cmake
  test/integ/axpy/CMakeLists.txt
  test/integ/cudaOnly/CMakeLists.txt
  test/integ/mandelbrot/CMakeLists.txt
  test/integ/matMul/CMakeLists.txt
  test/integ/sharedMem/CMakeLists.txt
  test/unit/acc/CMakeLists.txt
  test/unit/atomic/CMakeLists.txt
  test/unit/block/shared/CMakeLists.txt
  test/unit/block/sync/CMakeLists.txt
  test/unit/core/CMakeLists.txt
  test/unit/event/CMakeLists.txt
  test/unit/idx/CMakeLists.txt
  test/unit/kernel/CMakeLists.txt
  test/unit/kernel/src/KernelLambda.cpp
  test/unit/mem/buf/CMakeLists.txt
  test/unit/mem/view/CMakeLists.txt
  test/unit/meta/CMakeLists.txt
  test/unit/queue/CMakeLists.txt
  test/unit/rand/CMakeLists.txt
  test/unit/time/CMakeLists.txt
  test/unit/vec/CMakeLists.txt
Labels: backend-CUDA

#554 Add support for Vec::operator(<, >=, >)
  include/alpaka/vec/Vec.hpp
  test/unit/vec/src/VecTest.cpp
Labels: enhancement, testing

#558 back-port to 0.3.2
  include/alpaka/core/Cuda.hpp
  include/alpaka/exec/ExecCpuOmp2Blocks.hpp
  include/alpaka/exec/ExecCpuOmp2Threads.hpp
  include/alpaka/mem/buf/BufCudaRt.hpp
  include/alpaka/mem/buf/cuda/Copy.hpp
  include/alpaka/mem/buf/cuda/Set.hpp
  test/common/include/alpaka/test/event/EventHostManualTrigger.hpp
Labels: backend-CUDA, backend-OpenMP, bug

#560 Add default google test arguments for execution with ctest / make test
  test/analysis/headerCheck/CMakeLists.txt
  test/integ/axpy/CMakeLists.txt
  test/integ/cudaOnly/CMakeLists.txt
  test/integ/mandelbrot/CMakeLists.txt
  test/integ/matMul/CMakeLists.txt
  test/integ/sharedMem/CMakeLists.txt
  test/unit/acc/CMakeLists.txt
  test/unit/atomic/CMakeLists.txt
  test/unit/block/shared/CMakeLists.txt
  test/unit/block/sync/CMakeLists.txt
  test/unit/core/CMakeLists.txt
  test/unit/event/CMakeLists.txt
  test/unit/idx/CMakeLists.txt
  test/unit/kernel/CMakeLists.txt
  test/unit/mem/buf/CMakeLists.txt
  test/unit/mem/view/CMakeLists.txt
  test/unit/meta/CMakeLists.txt
  test/unit/queue/CMakeLists.txt
  test/unit/rand/CMakeLists.txt
  test/unit/time/CMakeLists.txt
  test/unit/vec/CMakeLists.txt
Labels: testing

#559 Make the examples compilable and executable even when the CPU accelerator is not available
  example/bufferCopy/src/bufferCopy.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/vectorAdd/src/main.cpp
Labels: testing

#564 Fix implicit cast warning
  include/alpaka/exec/ExecGpuCudaRt.hpp
Labels: backend-CUDA, warning

#557 Add CUDA 9.2 support to 0.3.2 release
  .travis.yml
  README.md
  alpakaConfig.cmake
  cmake/dev.cmake
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/block/shared/dyn/BlockSharedMemDynBoostAlignedAlloc.hpp
  include/alpaka/block/shared/st/BlockSharedMemStMasterSync.hpp
  include/alpaka/block/shared/st/BlockSharedMemStNoSync.hpp
  include/alpaka/core/Assert.hpp
  include/alpaka/core/OpenMp.hpp
  include/alpaka/dev/cpu/SysInfo.hpp
  include/alpaka/exec/ExecCpuOmp2Blocks.hpp
  include/alpaka/exec/ExecCpuOmp2Threads.hpp
  include/alpaka/exec/ExecCpuOmp4.hpp
  include/alpaka/idx/bt/IdxBtOmp.hpp
  include/alpaka/mem/buf/cpu/Copy.hpp
  include/alpaka/mem/buf/cpu/Set.hpp
  include/alpaka/mem/view/ViewSubView.hpp
  include/alpaka/vec/Vec.hpp
  script/travis/before_install.sh
  script/travis/compileExec.sh
  script/travis/docker_install.sh
  script/travis/docker_run.sh
  script/travis/install_boost.sh
  script/travis/install_cuda.sh
  test/common/include/alpaka/test/acc/Acc.hpp
  test/common/include/alpaka/test/event/EventHostManualTrigger.hpp
  test/common/include/alpaka/test/mem/view/Iterator.hpp
  test/integ/mandelbrot/src/main.cpp
  test/unit/acc/CMakeLists.txt
  test/unit/atomic/CMakeLists.txt
  test/unit/block/shared/CMakeLists.txt
  test/unit/block/sync/CMakeLists.txt
  test/unit/block/sync/src/BlockSyncPredicate.cpp
  test/unit/event/CMakeLists.txt
  test/unit/idx/CMakeLists.txt
  test/unit/kernel/CMakeLists.txt
  test/unit/kernel/src/KernelWithAdditionalParam.cpp
  test/unit/mem/buf/CMakeLists.txt
  test/unit/mem/view/CMakeLists.txt
  test/unit/mem/view/src/ViewSubViewTest.cpp
  test/unit/meta/CMakeLists.txt
  test/unit/rand/CMakeLists.txt
  test/unit/stream/CMakeLists.txt
  test/unit/time/CMakeLists.txt
  test/unit/vec/CMakeLists.txt
Labels: backend-CUDA, work in progress

#562 Build all tests and examples from the main CMakeLists.txt and use ctest for test execution
  .travis.yml
  script/travis/run.sh
  script/travis/run_build.sh
  script/travis/run_headerCheck.sh
  script/travis/run_tests.sh
  test/analysis/headerCheck/CMakeLists.txt
Labels: testing

#567 Clean up test and example CMakeLists
  CMakeLists.txt
  example/bufferCopy/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  script/travis/run_tests.sh
  test/CMakeLists.txt
  test/analysis/headerCheck/CMakeLists.txt
  test/common/CMakeLists.txt
  test/common/Findcommon.cmake
  test/common/commonConfig.cmake
  test/integ/axpy/CMakeLists.txt
  test/integ/cudaOnly/CMakeLists.txt
  test/integ/mandelbrot/CMakeLists.txt
  test/integ/matMul/CMakeLists.txt
  test/integ/sharedMem/CMakeLists.txt
  test/unit/acc/CMakeLists.txt
  test/unit/atomic/CMakeLists.txt
  test/unit/block/shared/CMakeLists.txt
  test/unit/block/sync/CMakeLists.txt
  test/unit/core/CMakeLists.txt
  test/unit/event/CMakeLists.txt
  test/unit/idx/CMakeLists.txt
  test/unit/kernel/CMakeLists.txt
  test/unit/mem/buf/CMakeLists.txt
  test/unit/mem/view/CMakeLists.txt
  test/unit/meta/CMakeLists.txt
  test/unit/queue/CMakeLists.txt
  test/unit/rand/CMakeLists.txt
  test/unit/time/CMakeLists.txt
  test/unit/vec/CMakeLists.txt
Labels: refactoring, testing

#566 NVCC 8.0: GCC <= 5.3
  alpakaConfig.cmake
Labels: backend-CUDA, bug

#563 back port to 0.3.2
  alpakaConfig.cmake
  appveyor.yml
  cmake/dev.cmake
  example/bufferCopy/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  include/alpaka/exec/ExecGpuCudaRt.hpp
  include/alpaka/mem/buf/BufCudaRt.hpp
  include/alpaka/stream/StreamCudaRtAsync.hpp
  include/alpaka/vec/Vec.hpp
  test/common/commonConfig.cmake
  test/integ/axpy/CMakeLists.txt
  test/integ/cudaOnly/CMakeLists.txt
  test/integ/mandelbrot/CMakeLists.txt
  test/integ/matMul/CMakeLists.txt
  test/integ/sharedMem/CMakeLists.txt
  test/unit/acc/CMakeLists.txt
  test/unit/atomic/CMakeLists.txt
  test/unit/block/shared/CMakeLists.txt
  test/unit/block/sync/CMakeLists.txt
  test/unit/event/CMakeLists.txt
  test/unit/idx/CMakeLists.txt
  test/unit/kernel/CMakeLists.txt
  test/unit/kernel/src/KernelLambda.cpp
  test/unit/mem/buf/CMakeLists.txt
  test/unit/mem/view/CMakeLists.txt
  test/unit/meta/CMakeLists.txt
  test/unit/rand/CMakeLists.txt
  test/unit/stream/CMakeLists.txt
  test/unit/stream/src/StreamTest.cpp
  test/unit/time/CMakeLists.txt
  test/unit/vec/CMakeLists.txt
Labels: backend-CUDA, bug, testing

#569 back-ports to 0.3.2
  alpakaConfig.cmake
  include/alpaka/exec/ExecGpuCudaRt.hpp
Labels: backend-CUDA, bug, warning

#571 Enhance CMakeLists.txt
  .travis.yml
  alpakaConfig.cmake
  appveyor.yml
  script/travis/before_install.sh
  script/travis/docker_install.sh
  script/travis/docker_run.sh
  script/travis/install.sh
  script/travis/install_boost.sh
Labels: backend-CUDA, enhancement
