Repository alpaka-group/alpaka, pull requests merged in 2018-11, with the labels that each got.

#694 Small exec clean ups
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/exec/ExecCpuFibers.hpp
  include/alpaka/exec/ExecCpuOmp2Blocks.hpp
  include/alpaka/exec/ExecCpuOmp2Threads.hpp
  include/alpaka/exec/ExecCpuOmp4.hpp
  include/alpaka/exec/ExecCpuSerial.hpp
  include/alpaka/exec/ExecCpuTbbBlocks.hpp
  include/alpaka/exec/ExecCpuThreads.hpp
  include/alpaka/exec/ExecGpuCudaRt.hpp
  include/alpaka/exec/ExecGpuHipRt.hpp
Labels: enhancement, refactoring

#698 backport to 0.3.5 chunk 1
  .travis.yml
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/atomic/AtomicOmpBuiltIn.hpp
  include/alpaka/atomic/AtomicOmpCritSec.hpp
Labels: backend-OpenMP

#699 0.3.5: Enhance OpenMP atomics performance
  .travis.yml
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/atomic/AtomicOmpBuiltIn.hpp
  include/alpaka/atomic/AtomicOmpCritSec.hpp
Labels: backend-OpenMP

#702 Power Linux: Fix NVCC Macro
  alpakaConfig.cmake
Labels: backend-CUDA, bug, machine/system

#700 Use libc++ instead of libstdc++ for clang builds
  .travis.yml
  include/alpaka/exec/ExecGpuCudaRt.hpp
  script/travis/before_install.sh
  script/travis/docker_install.sh
  script/travis/docker_run.sh
  script/travis/install_boost.sh
  script/travis/install_clang.sh
  script/travis/prepare_sanitizers.sh
  script/travis/run.sh
  script/travis/run_build.sh
Labels: enhancement, testing

#705 Test CMake 3.13
  .travis.yml
Labels: testing

#704 Readme update
  README.md
Labels: documentation
