Repository alpaka-group/alpaka, pull requests merged in 2018-06, with the labels that each got.

#510 Fix naming of test typedefs
  test/common/include/alpaka/test/acc/Acc.hpp
Labels: refactoring, testing

#511 Support variadic operators for Transform
  include/alpaka/meta/Transform.hpp
  test/unit/meta/src/TransformTest.cpp
Labels: enhancement

#516 CMake Test Option and Unified Requirement Backport 0.3.1
  CMakeLists.txt
  cmake/addExecutable.cmake
  cmake/addLibrary.cmake
  example/CMakeLists.txt
  test/CMakeLists.txt
  test/analysis/CMakeLists.txt
  test/analysis/headerCheck/CMakeLists.txt
  test/integ/CMakeLists.txt
  test/integ/cudaOnly/CMakeLists.txt
  test/unit/CMakeLists.txt
  test/unit/acc/CMakeLists.txt
  test/unit/atomic/CMakeLists.txt
  test/unit/block/shared/CMakeLists.txt
  test/unit/block/sync/CMakeLists.txt
  test/unit/event/CMakeLists.txt
  test/unit/idx/CMakeLists.txt
  test/unit/kernel/CMakeLists.txt
  test/unit/mem/buf/CMakeLists.txt
  test/unit/mem/view/CMakeLists.txt
  test/unit/meta/CMakeLists.txt
  test/unit/rand/CMakeLists.txt
  test/unit/stream/CMakeLists.txt
  test/unit/time/CMakeLists.txt
  test/unit/vec/CMakeLists.txt
Labels: install, refactoring

#515 Test const buffers
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/mem/buf/BufCudaRt.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
  include/alpaka/mem/view/ViewSubView.hpp
  test/common/include/alpaka/test/mem/view/ViewTest.hpp
  test/unit/mem/buf/src/BufTest.cpp
Labels: enhancement

#517 Tests: fix CMake empty `ALPAKA_CUDA_ARCH`
  script/travis/compileExec.sh
Labels: bug, testing

#509 fix test analysis
  .travis.yml
  include/alpaka/idx/bt/IdxBtCudaBuiltIn.hpp
  include/alpaka/idx/gb/IdxGbCudaBuiltIn.hpp
  include/alpaka/queue/QueueCudaRtAsync.hpp
  include/alpaka/queue/QueueCudaRtSync.hpp
  script/travis/run.sh
  test/analysis/headerCheck/CMakeLists.txt
Labels: bug, testing

#519 backport cmake changes for bug fix release 0.3.1
  .travis.yml
  alpakaConfig.cmake
  include/alpaka/core/Dummy.cpp
  include/alpaka/idx/bt/IdxBtCudaBuiltIn.hpp
  include/alpaka/idx/gb/IdxGbCudaBuiltIn.hpp
  include/alpaka/stream/StreamCudaRtAsync.hpp
  include/alpaka/stream/StreamCudaRtSync.hpp
  script/travis/compileExec.sh
  script/travis/run.sh
  test/analysis/headerCheck/CMakeLists.txt
Labels: bug, install, testing

#513 Move ViewStdContainers into seperate headers
  include/alpaka/alpaka.hpp
  include/alpaka/mem/view/ViewCompileTimeArray.hpp
  include/alpaka/mem/view/ViewStdArray.hpp
  include/alpaka/mem/view/ViewStdContainers.hpp
  include/alpaka/mem/view/ViewStdVector.hpp
Labels: refactoring

#512 Use inheriting constructor for ViewSubView
  include/alpaka/mem/view/ViewSubView.hpp
  test/unit/kernel/src/KernelWithHostConstexpr.cpp
  test/unit/mem/view/src/ViewSubViewTest.cpp
Labels: enhancement

#522 Docs: Zenodo JSON
  .zenodo.json
Labels: documentation

#523 Fix AtomicTest on CUDA
  include/alpaka/atomic/AtomicCudaBuiltIn.hpp
  test/unit/atomic/src/AtomicTest.cpp
Labels: backend-CUDA, bug, testing, work in progress

#528 Move compiler compatibility checks into CMake
  .travis.yml
  README.md
  alpakaConfig.cmake
  script/travis/before_install.sh
Labels: backend-CUDA, enhancement

#527 Rename BOOST_ARCH_CUDA_DEVICE to BOOST_ARCH_PTX to match naming in boost
  include/alpaka/atomic/AtomicCudaBuiltIn.hpp
  include/alpaka/core/Assert.hpp
  include/alpaka/core/Common.hpp
  include/alpaka/core/ConcurrentExecPool.hpp
  include/alpaka/core/Unroll.hpp
  include/alpaka/event/EventCpu.hpp
  include/alpaka/exec/ExecCpuFibers.hpp
  include/alpaka/exec/ExecCpuThreads.hpp
  include/alpaka/exec/ExecGpuCudaRt.hpp
  include/alpaka/extent/Traits.hpp
  include/alpaka/idx/Accessors.hpp
  include/alpaka/idx/MapIdx.hpp
  include/alpaka/kernel/Traits.hpp
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/meta/ApplyTuple.hpp
  include/alpaka/meta/Fold.hpp
  include/alpaka/meta/ForEachType.hpp
  include/alpaka/meta/NdLoop.hpp
  include/alpaka/queue/QueueCpuAsync.hpp
  include/alpaka/vec/Vec.hpp
  test/common/include/alpaka/test/event/EventHostManualTrigger.hpp
  test/unit/queue/src/QueueTest.cpp
  test/unit/rand/src/RandTest.cpp
Labels: refactoring

#531 Make BOOST_COMP_NVCC compatible to boost version
  include/alpaka/core/Common.hpp
Labels: enhancement

#532 Add test which prints the defines from Common.hpp when they are set
  script/travis/run_tests.sh
  test/unit/CMakeLists.txt
  test/unit/core/CMakeLists.txt
  test/unit/core/src/CommonTest.cpp
  test/unit/core/src/main.cpp
Labels: testing

#534 Convert old integration tests to boost.test for consistency and clean up CMake
  example/bufferCopy/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  script/travis/run_tests.sh
  test/analysis/headerCheck/CMakeLists.txt
  test/integ/axpy/CMakeLists.txt
  test/integ/axpy/src/main.cpp
  test/integ/cudaOnly/CMakeLists.txt
  test/integ/mandelbrot/CMakeLists.txt
  test/integ/mandelbrot/src/main.cpp
  test/integ/matMul/CMakeLists.txt
  test/integ/matMul/src/main.cpp
  test/integ/sharedMem/CMakeLists.txt
  test/integ/sharedMem/src/main.cpp
  test/unit/acc/CMakeLists.txt
  test/unit/atomic/CMakeLists.txt
  test/unit/block/shared/CMakeLists.txt
  test/unit/block/sync/CMakeLists.txt
  test/unit/event/CMakeLists.txt
  test/unit/idx/CMakeLists.txt
  test/unit/kernel/CMakeLists.txt
  test/unit/mem/buf/CMakeLists.txt
  test/unit/mem/view/CMakeLists.txt
  test/unit/meta/CMakeLists.txt
  test/unit/queue/CMakeLists.txt
  test/unit/rand/CMakeLists.txt
  test/unit/time/CMakeLists.txt
  test/unit/vec/CMakeLists.txt
Labels: testing

#533 Add support for CUDA 9.2 using gcc
  .travis.yml
  alpakaConfig.cmake
  include/alpaka/core/Assert.hpp
  include/alpaka/dev/cpu/SysInfo.hpp
  script/travis/before_install.sh
  script/travis/install_cuda.sh
  test/unit/acc/CMakeLists.txt
  test/unit/atomic/CMakeLists.txt
  test/unit/block/shared/CMakeLists.txt
  test/unit/block/sync/CMakeLists.txt
  test/unit/event/CMakeLists.txt
  test/unit/idx/CMakeLists.txt
  test/unit/kernel/CMakeLists.txt
  test/unit/mem/buf/CMakeLists.txt
  test/unit/mem/view/CMakeLists.txt
  test/unit/meta/CMakeLists.txt
  test/unit/queue/CMakeLists.txt
  test/unit/rand/CMakeLists.txt
  test/unit/time/CMakeLists.txt
  test/unit/vec/CMakeLists.txt
Labels: enhancement, work in progress

#530 [WIP] Updates cmake compiler checks (CUDA9.2 +gcc|clang, CUDA+Fiber+?)
  alpakaConfig.cmake
Labels: enhancement, work in progress

#536 Update readme for CUDA support
  README.md
Labels: backend-CUDA, documentation

#539 Adds proper float comparison for axpy test.
  test/common/include/alpaka/test/mem/view/ViewTest.hpp
  test/integ/axpy/src/main.cpp
Labels: bug, testing

#540 Replaces C rand with C++11 random engine (test, example).
  example/vectorAdd/src/main.cpp
  test/integ/axpy/src/main.cpp
Labels: example, refactoring, testing

#542 Updates Readme (CUDA: nvcc and clang separated).
  README.md
Labels: backend-CUDA, documentation

#545 Fix cudaOnly test being part of make test when cuda only mode is not enabled
  test/integ/cudaOnly/CMakeLists.txt
Labels: testing

#544 Fix cuda memcpy and memset for zero sized buffers (division by zero)
  include/alpaka/mem/buf/cuda/Copy.hpp
  include/alpaka/mem/buf/cuda/Set.hpp
Labels: backend-CUDA, bug

#548 Fixes CUDA driver API error handler.
  include/alpaka/core/Cuda.hpp
  include/alpaka/mem/buf/BufCudaRt.hpp
  test/common/include/alpaka/test/event/EventHostManualTrigger.hpp
Labels: backend-CUDA, bug

#546 Do not execute tests using EventHostManualTrigger if not supported
  test/common/include/alpaka/test/event/EventHostManualTrigger.hpp
  test/unit/event/src/EventTest.cpp
Labels: backend-CUDA, testing
