Repository alpaka-group/alpaka, pull requests merged in 2018-10, with the labels that each got.

#665 Remove explicit queue deregistration from device because this could throw in destructors
  include/alpaka/dev/DevCpu.hpp
  include/alpaka/queue/QueueCpuAsync.hpp
Labels: enhancement

#670 Mem Tests: Boost Predef
  test/unit/mem/p2p/src/P2P.cpp
  test/unit/mem/p2p/src/main.cpp
Labels: bug, testing

#672 Check definition of __GLIBCXX__ first.
  include/alpaka/exec/ExecGpuCudaRt.hpp
Labels: backend-CUDA, bug

#667 Add test for ViewPlainPtr
  test/unit/mem/view/src/ViewPlainPtrTest.cpp
Labels: testing

#664 OpenMP builtin atomics
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/atomic/AtomicOmpBuiltIn.hpp
  include/alpaka/atomic/AtomicOmpCritSec.hpp
Labels: backend-OpenMP, refactoring

#669 Backports for 0.3.4 Part 2
  alpakaConfig.cmake
  appveyor.yml
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGpuCudaRt.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/core/Assert.hpp
  include/alpaka/core/ClipCast.hpp
  include/alpaka/exec/ExecGpuCudaRt.hpp
  include/alpaka/math/abs/AbsCudaBuiltIn.hpp
  include/alpaka/math/acos/AcosCudaBuiltIn.hpp
  include/alpaka/math/asin/AsinCudaBuiltIn.hpp
  include/alpaka/math/atan/AtanCudaBuiltIn.hpp
  include/alpaka/math/atan2/Atan2CudaBuiltIn.hpp
  include/alpaka/math/ceil/CeilCudaBuiltIn.hpp
  include/alpaka/math/cos/CosCudaBuiltIn.hpp
  include/alpaka/math/erf/ErfCudaBuiltIn.hpp
  include/alpaka/math/exp/ExpCudaBuiltIn.hpp
  include/alpaka/math/floor/FloorCudaBuiltIn.hpp
  include/alpaka/math/fmod/FmodCudaBuiltIn.hpp
  include/alpaka/math/log/LogCudaBuiltIn.hpp
  include/alpaka/math/max/MaxCudaBuiltIn.hpp
  include/alpaka/math/min/MinCudaBuiltIn.hpp
  include/alpaka/math/pow/PowCudaBuiltIn.hpp
  include/alpaka/math/remainder/RemainderCudaBuiltIn.hpp
  include/alpaka/math/round/RoundCudaBuiltIn.hpp
  include/alpaka/math/rsqrt/RsqrtCudaBuiltIn.hpp
  include/alpaka/math/sin/SinCudaBuiltIn.hpp
  include/alpaka/math/sqrt/SqrtCudaBuiltIn.hpp
  include/alpaka/math/tan/TanCudaBuiltIn.hpp
  include/alpaka/math/trunc/TruncCudaBuiltIn.hpp
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/mem/buf/BufCudaRt.hpp
  include/alpaka/mem/buf/Traits.hpp
  include/alpaka/mem/buf/cpu/Copy.hpp
  include/alpaka/mem/buf/cpu/Set.hpp
  include/alpaka/mem/view/ViewStdContainers.hpp
  include/alpaka/meta/Integral.hpp
  include/alpaka/meta/IsIntegralSuperset.hpp
  include/alpaka/rand/TinyMT/tinymt32.h
  include/alpaka/vec/Vec.hpp
  test/common/include/alpaka/test/KernelExecutionFixture.hpp
  test/unit/core/src/ClipCastTest.cpp
  test/unit/mem/buf/src/BufTest.cpp
  test/unit/mem/view/src/ViewSubViewTest.cpp
  test/unit/meta/src/IntegralTest.cpp
  test/unit/meta/src/IsIntegralSupersetTest.cpp
Labels: bug

#674 Extract CreateExtentBufVal from tests and fix documentation
  test/common/include/alpaka/test/Extent.hpp
  test/unit/idx/src/MapIdx.cpp
  test/unit/mem/buf/src/BufTest.cpp
  test/unit/mem/p2p/src/P2P.cpp
  test/unit/mem/view/src/ViewPlainPtrTest.cpp
  test/unit/mem/view/src/ViewSubViewTest.cpp
Labels: documentation, refactoring, testing

#677 Remove noexcept(false) from destructor
  include/alpaka/mem/buf/BufCpu.hpp
Labels: bug

#666 Allow to run OpenMP 2 block backend within parallel region
  include/alpaka/exec/ExecCpuOmp2Blocks.hpp
  include/alpaka/exec/ExecCpuOmp2Threads.hpp
  include/alpaka/exec/ExecCpuOmp4.hpp
Labels: enhancement, help wanted, question

#676 Add error for unsupported types/operations for CUDA atomics
  include/alpaka/atomic/AtomicCudaBuiltIn.hpp
Labels: backend-CUDA, enhancement

#681 Fixed broken `alpaka::math::min` for non-integral types
  include/alpaka/math/min/MinCudaBuiltIn.hpp
  include/alpaka/math/min/MinStdLib.hpp
Labels: backend-Boost.Fiber, backend-CUDA, backend-OpenMP, backend-TBB, backend-std::thread, bug

#679 Allow to copy and move construct ViewPlainPtr
  include/alpaka/mem/view/ViewPlainPtr.hpp
  test/unit/mem/view/src/ViewPlainPtrTest.cpp
Labels: enhancement

#683 Suppress warning in clang about exit time destructor
  include/alpaka/atomic/AtomicStdLibLock.hpp
Labels: warning

#678 backport to 0.3.4 chunk 3
  include/alpaka/dev/DevCpu.hpp
  include/alpaka/exec/ExecCpuOmp2Blocks.hpp
  include/alpaka/exec/ExecCpuOmp2Threads.hpp
  include/alpaka/exec/ExecCpuOmp4.hpp
  include/alpaka/math/min/MinCudaBuiltIn.hpp
  include/alpaka/math/min/MinStl.hpp
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/stream/StreamCpuAsync.hpp
Labels: bug, enhancement

#686 Add support for CUDA atomics using "unsigned long int"
  .travis.yml
  include/alpaka/atomic/AtomicCudaBuiltIn.hpp
  test/unit/atomic/src/AtomicTest.cpp
Labels: backend-CUDA, enhancement

#688 Travis update
  .travis.yml
Labels: testing
