Repository alpaka-group/alpaka, pull requests merged in 2018-08, with the labels that each got.

#574 Add support for gcc 8.1 to ReadMe
  README.md
Labels: documentation

#576 Rng: add std::random_device gen
  include/alpaka/rand/RandStl.hpp
Labels: backend-OpenMP

#581 Update tested CMake, clang and gcc versions
  .travis.yml
  README.md
Labels: documentation, testing

#584 ignore_unused in Device
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/block/sync/BlockSyncBarrierOmp.hpp
  include/alpaka/block/sync/BlockSyncNoOp.hpp
  include/alpaka/core/Assert.hpp
  include/alpaka/extent/Traits.hpp
  include/alpaka/idx/Accessors.hpp
  include/alpaka/idx/MapIdx.hpp
  include/alpaka/idx/bt/IdxBtCudaBuiltIn.hpp
  include/alpaka/idx/bt/IdxBtOmp.hpp
  include/alpaka/idx/bt/IdxBtRefFiberIdMap.hpp
  include/alpaka/idx/bt/IdxBtRefThreadIdMap.hpp
  include/alpaka/idx/bt/IdxBtZero.hpp
  include/alpaka/idx/gb/IdxGbCudaBuiltIn.hpp
  include/alpaka/idx/gb/IdxGbRef.hpp
  include/alpaka/kernel/Traits.hpp
  include/alpaka/math/abs/AbsCudaBuiltIn.hpp
  include/alpaka/math/acos/AcosCudaBuiltIn.hpp
  include/alpaka/math/asin/AsinCudaBuiltIn.hpp
  include/alpaka/math/atan/AtanCudaBuiltIn.hpp
  include/alpaka/math/atan2/Atan2CudaBuiltIn.hpp
  include/alpaka/math/cbrt/CbrtCudaBuiltIn.hpp
  include/alpaka/math/ceil/CeilCudaBuiltIn.hpp
  include/alpaka/math/erf/ErfCudaBuiltIn.hpp
  include/alpaka/math/exp/ExpCudaBuiltIn.hpp
  include/alpaka/math/floor/FloorCudaBuiltIn.hpp
  include/alpaka/math/fmod/FmodCudaBuiltIn.hpp
  include/alpaka/math/log/LogCudaBuiltIn.hpp
  include/alpaka/math/max/MaxCudaBuiltIn.hpp
  include/alpaka/math/min/MinCudaBuiltIn.hpp
  include/alpaka/math/pow/PowCudaBuiltIn.hpp
  include/alpaka/math/remainder/RemainderCudaBuiltIn.hpp
  include/alpaka/math/round/RoundCudaBuiltIn.hpp
  include/alpaka/math/rsqrt/RsqrtCudaBuiltIn.hpp
  include/alpaka/math/sin/SinCudaBuiltIn.hpp
  include/alpaka/math/sqrt/SqrtCudaBuiltIn.hpp
  include/alpaka/math/tan/TanCudaBuiltIn.hpp
  include/alpaka/math/trunc/TruncCudaBuiltIn.hpp
  include/alpaka/mem/alloc/AllocCpuNew.hpp
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/mem/view/Traits.hpp
  include/alpaka/mem/view/ViewCompileTimeArray.hpp
  include/alpaka/mem/view/ViewStdArray.hpp
  include/alpaka/mem/view/ViewStdVector.hpp
  include/alpaka/meta/ApplyTuple.hpp
  include/alpaka/meta/Fold.hpp
  include/alpaka/meta/ForEachType.hpp
  include/alpaka/meta/NdLoop.hpp
  include/alpaka/rand/RandStl.hpp
  include/alpaka/time/TimeOmp.hpp
  include/alpaka/time/TimeStl.hpp
  include/alpaka/vec/Vec.hpp
  include/alpaka/workdiv/WorkDivCudaBuiltIn.hpp
  test/integ/matMul/src/main.cpp
Labels: backend-CUDA, refactoring

#583 Clean up alpaka::ignore_unused usages
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/block/sync/BlockSyncNoOp.hpp
  include/alpaka/dev/DevCpu.hpp
  include/alpaka/event/EventCpu.hpp
  include/alpaka/exec/ExecCpuOmp2Threads.hpp
  include/alpaka/exec/ExecCpuSerial.hpp
  include/alpaka/extent/Traits.hpp
  include/alpaka/idx/MapIdx.hpp
  include/alpaka/idx/bt/IdxBtOmp.hpp
  include/alpaka/idx/bt/IdxBtRefFiberIdMap.hpp
  include/alpaka/idx/bt/IdxBtRefThreadIdMap.hpp
  include/alpaka/idx/bt/IdxBtZero.hpp
  include/alpaka/idx/gb/IdxGbRef.hpp
  include/alpaka/math/acos/AcosCudaBuiltIn.hpp
  include/alpaka/math/cos/CosCudaBuiltIn.hpp
  include/alpaka/mem/alloc/AllocCpuBoostAligned.hpp
  include/alpaka/mem/view/Traits.hpp
  include/alpaka/mem/view/ViewCompileTimeArray.hpp
  include/alpaka/mem/view/ViewStdArray.hpp
  include/alpaka/mem/view/ViewStdVector.hpp
  include/alpaka/meta/NdLoop.hpp
  include/alpaka/queue/QueueCpuSync.hpp
  include/alpaka/vec/Vec.hpp
  include/alpaka/workdiv/WorkDivCudaBuiltIn.hpp
  test/integ/matMul/src/main.cpp
  test/unit/rand/src/RandTest.cpp
Labels: backend-CUDA, refactoring

#579 CPU Rng: TinyMT
  include/alpaka/rand/RandStl.hpp
  include/alpaka/rand/TinyMT/Engine.hpp
  include/alpaka/rand/TinyMT/LICENSE.txt
  include/alpaka/rand/TinyMT/tinymt32.h
  test/unit/rand/src/RandTest.cpp
Labels: backend-Boost.Fiber, backend-OpenMP, backend-TBB, backend-std::thread

#589 TinyMT Engine: Default Seed
  include/alpaka/rand/TinyMT/Engine.hpp
Labels: backend-OpenMP, backend-TBB, backend-std::thread, bug

#590 NVCC 8.0 Exact Compare
  test/unit/queue/src/QueueTest.cpp
  test/unit/rand/src/RandTest.cpp
Labels: backend-CUDA, bug, testing

#592 Rng: Copyright Forgotten
  include/alpaka/rand/RandStl.hpp
  test/unit/rand/src/RandTest.cpp
Labels: documentation

#598 Fix Visual Studio build
  .appveyor.yml
  alpakaConfig.cmake
  include/alpaka/rand/TinyMT/Engine.hpp
  include/alpaka/rand/TinyMT/tinymt32.h
Labels: bug

#604 remove static from templates in ViewTest
  test/common/include/alpaka/test/mem/view/ViewTest.hpp
Labels: testing

#605 Replace ALPAKA_FN_ACC_CUDA_ONLY by __device__
  doc/markdown/user/implementation/mapping/CUDA.md
  include/alpaka/acc/AccGpuCudaRt.hpp
  include/alpaka/atomic/AtomicCudaBuiltIn.hpp
  include/alpaka/block/shared/dyn/BlockSharedMemDynCudaBuiltIn.hpp
  include/alpaka/block/shared/st/BlockSharedMemStCudaBuiltIn.hpp
  include/alpaka/block/sync/BlockSyncCudaBuiltIn.hpp
  include/alpaka/core/Common.hpp
  include/alpaka/idx/bt/IdxBtCudaBuiltIn.hpp
  include/alpaka/idx/gb/IdxGbCudaBuiltIn.hpp
  include/alpaka/math/abs/AbsCudaBuiltIn.hpp
  include/alpaka/math/acos/AcosCudaBuiltIn.hpp
  include/alpaka/math/asin/AsinCudaBuiltIn.hpp
  include/alpaka/math/atan/AtanCudaBuiltIn.hpp
  include/alpaka/math/atan2/Atan2CudaBuiltIn.hpp
  include/alpaka/math/cbrt/CbrtCudaBuiltIn.hpp
  include/alpaka/math/ceil/CeilCudaBuiltIn.hpp
  include/alpaka/math/cos/CosCudaBuiltIn.hpp
  include/alpaka/math/erf/ErfCudaBuiltIn.hpp
  include/alpaka/math/exp/ExpCudaBuiltIn.hpp
  include/alpaka/math/floor/FloorCudaBuiltIn.hpp
  include/alpaka/math/fmod/FmodCudaBuiltIn.hpp
  include/alpaka/math/log/LogCudaBuiltIn.hpp
  include/alpaka/math/max/MaxCudaBuiltIn.hpp
  include/alpaka/math/min/MinCudaBuiltIn.hpp
  include/alpaka/math/pow/PowCudaBuiltIn.hpp
  include/alpaka/math/remainder/RemainderCudaBuiltIn.hpp
  include/alpaka/math/round/RoundCudaBuiltIn.hpp
  include/alpaka/math/rsqrt/RsqrtCudaBuiltIn.hpp
  include/alpaka/math/sin/SinCudaBuiltIn.hpp
  include/alpaka/math/sqrt/SqrtCudaBuiltIn.hpp
  include/alpaka/math/tan/TanCudaBuiltIn.hpp
  include/alpaka/math/trunc/TruncCudaBuiltIn.hpp
  include/alpaka/rand/RandCuRand.hpp
  include/alpaka/time/TimeCudaBuiltIn.hpp
  include/alpaka/workdiv/WorkDivCudaBuiltIn.hpp
  test/unit/kernel/src/KernelWithoutTemplatedAccParam.cpp
Labels: backend-CUDA

#607 Replace ALPAKA_FN_ACC_NO_CUDA with ALPAKA_FN_HOST
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/atomic/AtomicNoOp.hpp
  include/alpaka/atomic/AtomicOmpCritSec.hpp
  include/alpaka/atomic/AtomicStlLock.hpp
  include/alpaka/block/shared/dyn/BlockSharedMemDynBoostAlignedAlloc.hpp
  include/alpaka/block/shared/st/BlockSharedMemStMasterSync.hpp
  include/alpaka/block/shared/st/BlockSharedMemStNoSync.hpp
  include/alpaka/block/sync/BlockSyncBarrierFiber.hpp
  include/alpaka/block/sync/BlockSyncBarrierOmp.hpp
  include/alpaka/block/sync/BlockSyncBarrierThread.hpp
  include/alpaka/core/BarrierThread.hpp
  include/alpaka/core/Common.hpp
  include/alpaka/idx/bt/IdxBtOmp.hpp
  include/alpaka/idx/bt/IdxBtRefFiberIdMap.hpp
  include/alpaka/idx/bt/IdxBtRefThreadIdMap.hpp
  include/alpaka/idx/bt/IdxBtZero.hpp
  include/alpaka/idx/gb/IdxGbRef.hpp
  include/alpaka/math/abs/AbsStl.hpp
  include/alpaka/math/acos/AcosStl.hpp
  include/alpaka/math/asin/AsinStl.hpp
  include/alpaka/math/atan/AtanStl.hpp
  include/alpaka/math/atan2/Atan2Stl.hpp
  include/alpaka/math/cbrt/CbrtStl.hpp
  include/alpaka/math/ceil/CeilStl.hpp
  include/alpaka/math/cos/CosStl.hpp
  include/alpaka/math/erf/ErfStl.hpp
  include/alpaka/math/exp/ExpStl.hpp
  include/alpaka/math/floor/FloorStl.hpp
  include/alpaka/math/fmod/FmodStl.hpp
  include/alpaka/math/log/LogStl.hpp
  include/alpaka/math/max/MaxStl.hpp
  include/alpaka/math/min/MinStl.hpp
  include/alpaka/math/pow/PowStl.hpp
  include/alpaka/math/remainder/RemainderStl.hpp
  include/alpaka/math/round/RoundStl.hpp
  include/alpaka/math/rsqrt/RsqrtStl.hpp
  include/alpaka/math/sin/SinStl.hpp
  include/alpaka/math/sqrt/SqrtStl.hpp
  include/alpaka/math/tan/TanStl.hpp
  include/alpaka/math/trunc/TruncStl.hpp
  include/alpaka/rand/RandStl.hpp
  include/alpaka/time/TimeOmp.hpp
  include/alpaka/time/TimeStl.hpp
Labels: refactoring

#586 Unit test for peer-to-peer memory copies.
  test/unit/CMakeLists.txt
  test/unit/mem/p2p/CMakeLists.txt
  test/unit/mem/p2p/src/P2P.cpp
  test/unit/mem/p2p/src/main.cpp
Labels: help wanted, testing, work in progress

#608 Clean up and extend CI job names
  .travis.yml
Labels: testing

#616 Fix P2P test
  doc/markdown/user/implementation/mapping/CUDA.md
  include/alpaka/mem/buf/cuda/Copy.hpp
  test/unit/mem/p2p/src/P2P.cpp
Labels: backend-CUDA, enhancement

#609 Remove unused includes of boost/assert.hpp from implementation
  include/alpaka/exec/ExecCpuOmp2Blocks.hpp
  include/alpaka/exec/ExecCpuSerial.hpp
  include/alpaka/exec/ExecCpuTbbBlocks.hpp
  include/alpaka/exec/ExecGpuCudaRt.hpp
Labels: enhancement
