Repository alpaka-group/alpaka, pull requests merged in 2018-05, with the labels that each got.

#485 fix getDevCount documentation
  doc/markdown/user/implementation/mapping/CUDA.md
Labels: bug

#488 rename getProductOfExtent to getExtentProduct to be more consistent
  include/alpaka/extent/Traits.hpp
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/mem/buf/BufCudaRt.hpp
  test/common/include/alpaka/test/mem/view/ViewTest.hpp
  test/integ/matMul/src/main.cpp
Labels: enhancement

#486 Upgrade tested dependencies
  .travis.yml
  cmake/dev.cmake
  include/alpaka/block/shared/dyn/BlockSharedMemDynBoostAlignedAlloc.hpp
  include/alpaka/block/shared/st/BlockSharedMemStMasterSync.hpp
  include/alpaka/block/shared/st/BlockSharedMemStNoSync.hpp
  include/alpaka/mem/buf/cpu/Copy.hpp
  include/alpaka/mem/buf/cpu/Set.hpp
  include/alpaka/mem/view/ViewSubView.hpp
  include/alpaka/vec/Vec.hpp
  test/common/include/alpaka/test/acc/Acc.hpp
  test/common/include/alpaka/test/mem/view/Iterator.hpp
  test/integ/mandelbrot/src/main.cpp
  test/unit/kernel/src/KernelWithAdditionalParam.cpp
  test/unit/mem/view/src/ViewSubViewTest.cpp
Labels: testing

#487 move the CUDA 9 boost compatibility check into the CMake file
  alpakaConfig.cmake
  script/travis/before_install.sh
Labels: enhancement

#489 ViewSubView clean up
  include/alpaka/mem/view/ViewSubView.hpp
  test/unit/mem/view/src/ViewSubViewTest.cpp
Labels: enhancement

#494 Simplify and unify examples
  example/bufferCopy/src/bufferCopy.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/vectorAdd/src/main.cpp
Labels: example

#474 remove support for CUDA 7.x
  .travis.yml
  Findalpaka.cmake
  README.md
  alpakaConfig.cmake
  doc/markdown/user/implementation/mapping/Accelerators.md
  example/helloWorldLambda/src/helloWorldLambda.cpp
  include/alpaka/core/Common.hpp
  include/alpaka/core/Cuda.hpp
  include/alpaka/vec/Vec.hpp
  script/travis/before_install.sh
  script/travis/install_cuda.sh
  test/common/include/alpaka/test/event/EventHostManualTrigger.hpp
  test/common/include/alpaka/test/queue/Queue.hpp
  test/unit/event/src/EventTest.cpp
  test/unit/kernel/src/KernelLambda.cpp
  test/unit/queue/src/QueueTest.cpp
  test/unit/rand/src/RandTest.cpp
Labels: backend-CUDA

#495 Rename internal task creation traits for clarity
  include/alpaka/mem/buf/cpu/Copy.hpp
  include/alpaka/mem/buf/cpu/Set.hpp
  include/alpaka/mem/buf/cuda/Copy.hpp
  include/alpaka/mem/buf/cuda/Set.hpp
  include/alpaka/mem/view/Traits.hpp
Labels: refactoring

#503 fixes kernel host pointer bug in vectorAdd example.
  example/vectorAdd/src/main.cpp
Labels: bug, example

#499 add kernel::exec(...) as shortcut for queue::enqueue(q, exec::create(...))
  doc/markdown/user/implementation/library/Usage.md
  doc/markdown/user/implementation/mapping/CUDA.md
  example/bufferCopy/src/bufferCopy.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/vectorAdd/src/main.cpp
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGpuCudaRt.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/exec/ExecCpuFibers.hpp
  include/alpaka/exec/ExecCpuOmp2Blocks.hpp
  include/alpaka/exec/ExecCpuOmp2Threads.hpp
  include/alpaka/exec/ExecCpuOmp4.hpp
  include/alpaka/exec/ExecCpuSerial.hpp
  include/alpaka/exec/ExecCpuTbbBlocks.hpp
  include/alpaka/exec/ExecCpuThreads.hpp
  include/alpaka/exec/ExecGpuCudaRt.hpp
  include/alpaka/exec/Traits.hpp
  include/alpaka/kernel/Traits.hpp
  test/common/include/alpaka/test/KernelExecutionFixture.hpp
  test/common/include/alpaka/test/MeasureKernelRunTime.hpp
  test/common/include/alpaka/test/mem/view/ViewTest.hpp
  test/integ/axpy/src/main.cpp
  test/integ/mandelbrot/src/main.cpp
  test/integ/matMul/src/main.cpp
  test/integ/sharedMem/src/main.cpp
Labels: enhancement
