Repository alpaka-group/alpaka, pull requests merged in 2018-12, with the labels that each got.

#695 Check that the kernel return type is void
  doc/markdown/user/implementation/library/Usage.md
  example/helloWorldLambda/src/helloWorldLambda.cpp
  include/alpaka/kernel/Traits.hpp
Labels: enhancement

#709 Use boost.test header-only
  .appveyor.yml
  alpakaConfig.cmake
  script/travis/install_boost.sh
  test/CMakeLists.txt
  test/analysis/headerCheck/CMakeLists.txt
  test/analysis/headerCheck/src/main.cpp
  test/common/CMakeLists.txt
  test/integ/axpy/CMakeLists.txt
  test/integ/axpy/src/axpy.cpp
  test/integ/axpy/src/main.cpp
  test/integ/cudaOnly/CMakeLists.txt
  test/integ/cudaOnly/src/main.cpp
  test/integ/mandelbrot/CMakeLists.txt
  test/integ/mandelbrot/src/main.cpp
  test/integ/mandelbrot/src/mandelbrot.cpp
  test/integ/matMul/CMakeLists.txt
  test/integ/matMul/src/main.cpp
  test/integ/matMul/src/matMul.cpp
  test/integ/sharedMem/CMakeLists.txt
  test/integ/sharedMem/src/main.cpp
  test/integ/sharedMem/src/sharedMem.cpp
  test/unit/acc/CMakeLists.txt
  test/unit/acc/src/main.cpp
  test/unit/atomic/CMakeLists.txt
  test/unit/atomic/src/main.cpp
  test/unit/block/shared/CMakeLists.txt
  test/unit/block/shared/src/main.cpp
  test/unit/block/sync/CMakeLists.txt
  test/unit/block/sync/src/main.cpp
  test/unit/core/CMakeLists.txt
  test/unit/core/src/main.cpp
  test/unit/event/CMakeLists.txt
  test/unit/event/src/main.cpp
  test/unit/idx/CMakeLists.txt
  test/unit/idx/src/main.cpp
  test/unit/kernel/CMakeLists.txt
  test/unit/kernel/src/main.cpp
  test/unit/mem/buf/CMakeLists.txt
  test/unit/mem/buf/src/main.cpp
  test/unit/mem/p2p/CMakeLists.txt
  test/unit/mem/p2p/src/main.cpp
  test/unit/mem/view/CMakeLists.txt
  test/unit/mem/view/src/main.cpp
  test/unit/meta/CMakeLists.txt
  test/unit/meta/src/main.cpp
  test/unit/queue/CMakeLists.txt
  test/unit/queue/src/main.cpp
  test/unit/rand/CMakeLists.txt
  test/unit/rand/src/main.cpp
  test/unit/time/CMakeLists.txt
  test/unit/time/src/main.cpp
  test/unit/vec/CMakeLists.txt
  test/unit/vec/src/main.cpp
Labels: refactoring, testing

#711 check for kernel void return type
  include/alpaka/acc/AccGpuCudaRt.hpp
  include/alpaka/acc/AccGpuHipRt.hpp
  include/alpaka/exec/ExecGpuCudaRt.hpp
  include/alpaka/exec/ExecGpuHipRt.hpp
  include/alpaka/kernel/Traits.hpp
Labels: backend-CUDA, backend-HIP

#713 CMake: 3.11.0+
  .travis.yml
  CMakeLists.txt
  README.md
  alpakaConfig.cmake
  cmake/addExecutable.cmake
  cmake/addLibrary.cmake
  example/CMakeLists.txt
  example/bufferCopy/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/reduce/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  test/CMakeLists.txt
  test/analysis/CMakeLists.txt
  test/common/CMakeLists.txt
  test/integ/CMakeLists.txt
  test/unit/CMakeLists.txt
Labels: enhancement
