Repository alpaka-group/alpaka, pull requests merged in 2019-09, with the labels that each got.

#831 /math/fmod && /math/remainder incomplete type bug-fix && /math/min/ fix
  include/alpaka/math/fmod/Traits.hpp
  include/alpaka/math/min/MinHipBuiltIn.hpp
  include/alpaka/math/remainder/RemainderCudaBuiltIn.hpp
  include/alpaka/math/remainder/RemainderHipBuiltIn.hpp
  include/alpaka/math/remainder/RemainderStdLib.hpp
Labels: bug

#830 /math/exp/Traits muted cuda-warning
  include/alpaka/math/exp/Traits.hpp
Labels: Backend-CUDA, warning

#841 Fixes GCC/Address Sanitizer false-positive issue.
  include/alpaka/kernel/TaskKernelCpuOmp2Blocks.hpp
Labels: Backend-OpenMP, bug

#844 fix: cuda exeptions
  include/alpaka/core/Cuda.hpp
Labels: bug

#846 Use cudaDeviceGetAttribute instead of slow cudaGetDeviceProperties
  include/alpaka/acc/AccGpuCudaRt.hpp
  include/alpaka/dev/DevCudaRt.hpp
  include/alpaka/pltf/PltfCudaRt.hpp
Labels: Backend-CUDA, enhancement

#848 /test/.../KernelExecutionFixture.hpp missing pragma once
  test/common/include/alpaka/test/KernelExecutionFixture.hpp
Labels: bug
