Repository alpaka-group/alpaka, pull requests merged in 2019-12, with the labels that each got.

#886 Add support for CUDA 10.2
  .travis.yml
  README.md
  alpakaConfig.cmake
  script/travis/install_cuda.sh
  test/CMakeLists.txt
  test/unit/CMakeLists.txt
  test/unit/queue/src/CollectiveQueue.cpp
Labels: Backend-CUDA

#890 Simplify examples CMake
  example/bufferCopy/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/reduce/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  example/vectorAdd/src/vectorAdd.cpp
Labels: enhancement, example

#893 Add support for CMake 3.16
  .travis.yml
Labels: testing

#896 fix memory alignment
  include/alpaka/mem/alloc/AllocCpuBoostAligned.hpp
Labels: Backend-CUDA, Backend-HIP, bug

#897 HIP: allow memory pinning
  include/alpaka/core/Utility.hpp
  include/alpaka/mem/buf/BufCpu.hpp
Labels: Backend-HIP, enhancement

#894 implement queue properties
  example/bufferCopy/src/bufferCopy.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/reduce/src/reduce.cpp
  example/vectorAdd/src/vectorAdd.cpp
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGpuCudaRt.hpp
  include/alpaka/acc/AccGpuHipRt.hpp
  include/alpaka/acc/Traits.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/core/Concepts.hpp
  include/alpaka/dev/DevCpu.hpp
  include/alpaka/dev/DevCudaRt.hpp
  include/alpaka/dev/DevHipRt.hpp
  include/alpaka/pltf/PltfCpu.hpp
  include/alpaka/pltf/PltfCudaRt.hpp
  include/alpaka/pltf/PltfHipRt.hpp
  include/alpaka/pltf/Traits.hpp
  include/alpaka/queue/Properties.hpp
  include/alpaka/queue/Traits.hpp
Labels: enhancement

#892 Structure fix
  .gitignore
  doc/markdown/user/implementation/library/structure.png
  doc/markdown/user/implementation/library/structure.svg
  doc/markdown/user/implementation/library/structure_assoc.png
  doc/markdown/user/implementation/library/structure_assoc.svg
Labels: documentation
