Repository alpaka-group/alpaka, pull requests merged in 2019-07, with the labels that each got.

#800 Fixes HIP issues
  .travis.yml
  README.md
  alpakaConfig.cmake
  include/alpaka/event/EventHipRt.hpp
  include/alpaka/kernel/TaskKernelGpuHipRt.hpp
  include/alpaka/mem/view/Traits.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
  include/alpaka/queue/QueueCudaRtBlocking.hpp
  include/alpaka/queue/QueueHipRtBlocking.hpp
  include/alpaka/queue/QueueHipRtNonBlocking.hpp
  include/alpaka/rand/RandHipRand.hpp
  script/travis/install_hip.sh
  script/travis/run.sh
  test/common/include/alpaka/test/event/EventHostManualTrigger.hpp
  test/unit/kernel/src/KernelWithHostConstexpr.cpp
Labels: Backend-HIP, bug

#803 Atomics test reduced to 1D size_t accelerator set
  include/alpaka/atomic/Op.hpp
  test/unit/atomic/src/AtomicTest.cpp
Labels: testing

#807 Add unit tests for std::function and std::bind kernels and remove from examples
  .travis.yml
  example/helloWorldLambda/src/helloWorldLambda.cpp
  test/unit/kernel/src/KernelGenericLambda.cpp
  test/unit/kernel/src/KernelLambda.cpp
  test/unit/kernel/src/KernelStdFunction.cpp
  test/unit/kernel/src/KernelWithAdditionalParam.cpp
  test/unit/kernel/src/KernelWithConstructorAndMember.cpp
  test/unit/kernel/src/KernelWithHostConstexpr.cpp
  test/unit/kernel/src/KernelWithTemplate.cpp
  test/unit/kernel/src/KernelWithoutTemplatedAccParam.cpp
Labels: enhancement

#808 Fixes alpaka logo (removes white color in ear).
  doc/images/alpaka.svg
  doc/images/alpaka_inkscape.svg
Labels: documentation

#809 Template Depth: C++11 Default (1024)
  alpakaConfig.cmake
Labels: install, refactoring
