Repository alpaka-group/alpaka, pull requests merged in 2019-11, with the labels that each got.

#869 fix hip-hcc compile
  include/alpaka/kernel/TaskKernelGpuHipRt.hpp
  include/alpaka/mem/buf/cpu/Copy.hpp
Labels: Backend-HIP, bug

#871 Do not specialze traits for shared_ptr<Xxx> but only for Xxx
  include/alpaka/event/EventCpu.hpp
Labels: refactoring

#870 Simplify AtomicHierarchy
  include/alpaka/atomic/AtomicHierarchy.hpp
  include/alpaka/atomic/Traits.hpp
  include/alpaka/meta/InheritFromList.hpp
  include/alpaka/meta/Unique.hpp
  test/unit/meta/src/UniqueTest.cpp
Labels: refactoring

#872 Test concepts and extend with base case for types without inheritance
  include/alpaka/core/Concepts.hpp
  test/unit/core/src/ConceptsTest.cpp
Labels: enhancement

#878 Always add nvcc warning/error numbers to output
  alpakaConfig.cmake
Labels: Backend-CUDA, enhancement

#877 Make memcpy and memset operations for QueueCudaRtBlocking blocking async
  include/alpaka/mem/buf/cuda/Copy.hpp
  include/alpaka/mem/buf/cuda/Set.hpp
Labels: Backend-CUDA, bug

#876 Add concept for CurrentThreadWaitFor
  include/alpaka/dev/DevCpu.hpp
  include/alpaka/dev/DevCudaRt.hpp
  include/alpaka/dev/DevHipRt.hpp
  include/alpaka/event/EventCpu.hpp
  include/alpaka/event/EventCudaRt.hpp
  include/alpaka/event/EventHipRt.hpp
  include/alpaka/queue/QueueCpuBlocking.hpp
  include/alpaka/queue/QueueCpuNonBlocking.hpp
  include/alpaka/queue/QueueCudaRtBlocking.hpp
  include/alpaka/queue/QueueCudaRtNonBlocking.hpp
  include/alpaka/queue/QueueHipRtBlocking.hpp
  include/alpaka/queue/QueueHipRtNonBlocking.hpp
  include/alpaka/wait/Traits.hpp
  test/common/include/alpaka/test/queue/QueueCpuOmp2Collective.hpp
Labels: enhancement

#881 Fix QueueHipRtBlocking not being blocking
  .travis.yml
  include/alpaka/mem/buf/hip/Copy.hpp
  include/alpaka/mem/buf/hip/Set.hpp
Labels: Backend-HIP, bug

#874 HIP-clang support
  alpakaConfig.cmake
  include/alpaka/block/sync/BlockSyncHipBuiltIn.hpp
  include/alpaka/core/BoostPredef.hpp
  include/alpaka/core/Utility.hpp
  include/alpaka/kernel/TaskKernelGpuHipRt.hpp
  include/alpaka/math/abs/AbsHipBuiltIn.hpp
  include/alpaka/math/acos/AcosHipBuiltIn.hpp
  include/alpaka/math/asin/AsinHipBuiltIn.hpp
  include/alpaka/math/atan/AtanHipBuiltIn.hpp
  include/alpaka/math/atan2/Atan2HipBuiltIn.hpp
  include/alpaka/math/cbrt/CbrtHipBuiltIn.hpp
  include/alpaka/math/ceil/CeilHipBuiltIn.hpp
  include/alpaka/math/cos/CosHipBuiltIn.hpp
  include/alpaka/math/erf/ErfHipBuiltIn.hpp
  include/alpaka/math/exp/ExpHipBuiltIn.hpp
  include/alpaka/math/floor/FloorHipBuiltIn.hpp
  include/alpaka/math/fmod/FmodHipBuiltIn.hpp
  include/alpaka/math/log/LogHipBuiltIn.hpp
  include/alpaka/math/max/MaxHipBuiltIn.hpp
  include/alpaka/math/min/MinHipBuiltIn.hpp
  include/alpaka/math/pow/PowHipBuiltIn.hpp
  include/alpaka/math/remainder/RemainderHipBuiltIn.hpp
  include/alpaka/math/round/RoundHipBuiltIn.hpp
  include/alpaka/math/rsqrt/RsqrtHipBuiltIn.hpp
  include/alpaka/math/sin/SinHipBuiltIn.hpp
  include/alpaka/math/sincos/SinCosHipBuiltIn.hpp
  include/alpaka/math/sqrt/SqrtHipBuiltIn.hpp
  include/alpaka/math/tan/TanHipBuiltIn.hpp
  include/alpaka/math/trunc/TruncHipBuiltIn.hpp
  include/alpaka/queue/QueueHipRtNonBlocking.hpp
  include/alpaka/vec/Vec.hpp
  test/unit/core/src/BoostPredefTest.cpp
  test/unit/mem/view/src/ViewStaticAccMem.cpp
  test/unit/queue/src/QueueTest.cpp
Labels: Backend-HIP

#879 fix warning: implicit deleted constructor
  include/alpaka/rand/RandCuRand.hpp
  include/alpaka/rand/RandHipRand.hpp
Labels: Backend-CUDA, Backend-HIP, warning

#884 fix warning for `std::__shared_counter`
  alpakaConfig.cmake
Labels: Backend-CUDA, warning

#882 Update catch2 to 2.11.0 to use the new TEMPLATE_LIST_TEST_CASE feature
  test/CMakeLists.txt
  test/unit/acc/src/AccNameTest.cpp
  test/unit/atomic/src/AtomicTest.cpp
  test/unit/block/shared/src/BlockSharedMemDyn.cpp
  test/unit/block/shared/src/BlockSharedMemSt.cpp
  test/unit/block/sync/src/BlockSync.cpp
  test/unit/block/sync/src/BlockSyncPredicate.cpp
  test/unit/event/src/EventTest.cpp
  test/unit/idx/src/MapIdx.cpp
  test/unit/kernel/src/KernelGenericLambda.cpp
  test/unit/kernel/src/KernelWithAdditionalParam.cpp
  test/unit/kernel/src/KernelWithConstructorAndMember.cpp
  test/unit/kernel/src/KernelWithHostConstexpr.cpp
  test/unit/kernel/src/KernelWithTemplate.cpp
  test/unit/math/sincos/src/sincos.cpp
  test/unit/mem/buf/src/BufTest.cpp
  test/unit/mem/p2p/src/P2P.cpp
  test/unit/mem/view/src/ViewPlainPtrTest.cpp
  test/unit/mem/view/src/ViewStaticAccMem.cpp
  test/unit/mem/view/src/ViewSubViewTest.cpp
  test/unit/queue/src/QueueTest.cpp
  test/unit/rand/src/RandTest.cpp
  test/unit/time/src/ClockTest.cpp
  test/unit/vec/src/VecTest.cpp
  thirdParty/catch2/include/catch2/catch.hpp
Labels: enhancement, testing

#887 Use TEMPLATE_LIST_TEST_CASE for more tests
  test/integ/axpy/src/axpy.cpp
  test/integ/mandelbrot/src/mandelbrot.cpp
  test/integ/matMul/src/matMul.cpp
  test/integ/separableCompilation/src/main.cpp
  test/integ/sharedMem/src/sharedMem.cpp
  test/unit/kernel/src/KernelStdFunction.cpp
  test/unit/kernel/src/KernelWithTemplateArgumentDeduction.cpp
Labels: testing

#889 remove deprecated NVIDIA architectures
  alpakaConfig.cmake
Labels: install
