Repository alpaka-group/alpaka, pull requests merged in 2019-08, with the labels that each got.

#812 Add noexcept to some ctors
  include/alpaka/event/EventCpu.hpp
  include/alpaka/queue/QueueCpuBlocking.hpp
  test/common/include/alpaka/test/event/EventHostManualTrigger.hpp
Labels: warning

#813 Add gcc-9 to CI testing
  .travis.yml
  script/travis/before_install.sh
Labels: testing

#816 Fixes race-condition HIP/NVCC. HIP/HCC non-blocking queue destructor waits ...
  include/alpaka/queue/QueueHipRtBlocking.hpp
  include/alpaka/queue/QueueHipRtNonBlocking.hpp
Labels: Backend-HIP, bug

#818 Mandelbrot: const inline member
  test/integ/mandelbrot/src/mandelbrot.cpp
Labels: example, refactoring

#814 Clean up unit test includes
  alpakaConfig.cmake
  include/alpaka/core/BoostPredef.hpp
  include/alpaka/core/Common.hpp
  include/alpaka/core/Cuda.hpp
  include/alpaka/meta/ApplyTuple.hpp
  test/common/include/alpaka/test/acc/TestAccs.hpp
  test/common/include/alpaka/test/dim/TestDims.hpp
  test/common/include/alpaka/test/idx/TestIdxs.hpp
  test/common/include/alpaka/test/mem/view/Iterator.hpp
  test/integ/axpy/src/axpy.cpp
  test/integ/cudaOnly/src/cudaNativeFunctions.cpp
  test/integ/mandelbrot/src/mandelbrot.cpp
  test/integ/matMul/src/matMul.cpp
  test/integ/separableCompilation/src/main.cpp
  test/integ/sharedMem/src/sharedMem.cpp
  test/unit/acc/src/AccNameTest.cpp
  test/unit/atomic/src/AtomicTest.cpp
  test/unit/block/shared/src/BlockSharedMemDyn.cpp
  test/unit/block/shared/src/BlockSharedMemSt.cpp
  test/unit/block/sync/src/BlockSync.cpp
  test/unit/block/sync/src/BlockSyncPredicate.cpp
  test/unit/core/src/BoostPredefTest.cpp
  test/unit/core/src/ClipCastTest.cpp
  test/unit/event/src/EventTest.cpp
  test/unit/idx/src/MapIdx.cpp
  test/unit/kernel/src/KernelGenericLambda.cpp
  test/unit/kernel/src/KernelLambda.cpp
  test/unit/kernel/src/KernelStdFunction.cpp
  test/unit/kernel/src/KernelWithAdditionalParam.cpp
  test/unit/kernel/src/KernelWithConstructorAndMember.cpp
  test/unit/kernel/src/KernelWithHostConstexpr.cpp
  test/unit/kernel/src/KernelWithTemplate.cpp
  test/unit/kernel/src/KernelWithoutTemplatedAccParam.cpp
  test/unit/math/sincos/src/sincos.cpp
  test/unit/mem/buf/src/BufTest.cpp
  test/unit/mem/p2p/src/P2P.cpp
  test/unit/mem/view/src/ViewPlainPtrTest.cpp
  test/unit/mem/view/src/ViewStaticAccMem.cpp
  test/unit/mem/view/src/ViewSubViewTest.cpp
  test/unit/meta/src/ApplyTest.cpp
  test/unit/meta/src/ApplyTupleTest.cpp
  test/unit/meta/src/CartesianProductTest.cpp
  test/unit/meta/src/ConcatenateTest.cpp
  test/unit/meta/src/FilterTest.cpp
  test/unit/meta/src/IntegralTest.cpp
  test/unit/meta/src/IsStrictBaseTest.cpp
  test/unit/meta/src/MetafunctionsTest.cpp
  test/unit/meta/src/SetTest.cpp
  test/unit/meta/src/TransformTest.cpp
  test/unit/queue/src/QueueTest.cpp
  test/unit/rand/src/RandTest.cpp
  test/unit/time/src/ClockTest.cpp
  test/unit/vec/src/VecTest.cpp
Labels: refactoring, testing

#824 Enable types with alignment higher than defaultAlignment for static shared memory
  include/alpaka/block/shared/st/BlockSharedMemStMasterSync.hpp
  include/alpaka/block/shared/st/BlockSharedMemStNoSync.hpp
Labels: enhancement

#825 Add support for boost-1.71.0
  .travis.yml
  README.md
Labels: testing

#822 support external queue implementations
  include/alpaka/dev/DevCpu.hpp
  include/alpaka/dev/cpu/Wait.hpp
  include/alpaka/event/EventCpu.hpp
  include/alpaka/queue/QueueCpuBlocking.hpp
  include/alpaka/queue/QueueCpuNonBlocking.hpp
  include/alpaka/queue/cpu/ICpuQueue.hpp
  test/common/include/alpaka/test/queue/QueueCpuOmp2Collective.hpp
  test/unit/event/src/EventTest.cpp
  test/unit/queue/src/CollectiveQueue.cpp
  test/unit/queue/src/QueueTest.cpp
Labels: Backend-OpenMP

#819 Use CMake 3.15 in CI
  .travis.yml
  alpakaConfig.cmake
Labels: testing

#832 Updates travis/HIP to use rocm2.7.0.
  .travis.yml
Labels: Backend-HIP, bug, testing

#829 Fix #750 by adding a dummy bBusyWaiting parameter to the EventCpu
  include/alpaka/event/EventCpu.hpp
Labels: Backend-Boost.Fiber, Backend-OpenMP, Backend-TBB, Backend-std::thread, refactoring

#834 Workaround hanging CUDA windows installer removal
  script/travis/install_cuda.sh
Labels: bug, testing
