Repository alpaka-group/alpaka, pull requests merged in 2019-02, with the labels that each got.

#742 Install TBB on OSX
  script/travis/install.sh
Labels: backend-TBB, machine/system, testing

#744 Extend CommonTest
  test/unit/core/src/CommonTest.cpp
Labels: testing

#746 Clean up osx tbb installation
  README.md
  script/travis/install.sh
  script/travis/install_tbb.sh
Labels: Backend-TBB, OS-macOS, testing

#745 Install selected CMake version on windows
  .travis.yml
  script/travis/install.sh
  script/travis/install_cmake.sh
Labels: OS-Windows, testing

#747 Rename createTaskExec to createTaskKernel
  example/reduce/src/reduce.cpp
  example/vectorAdd/src/main.cpp
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGpuCudaRt.hpp
  include/alpaka/acc/AccGpuHipRt.hpp
  include/alpaka/kernel/Traits.hpp
  test/integ/axpy/src/axpy.cpp
  test/integ/mandelbrot/src/mandelbrot.cpp
  test/integ/matMul/src/matMul.cpp
  test/integ/sharedMem/src/sharedMem.cpp
Labels: enhancement, refactoring

#748 Rename ExecXxx to TaskKernelXxx
  cmake/dev.cmake
  doc/markdown/user/implementation/library/Usage.md
  example/bufferCopy/src/bufferCopy.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/vectorAdd/src/main.cpp
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGpuCudaRt.hpp
  include/alpaka/acc/AccGpuHipRt.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/core/ConcurrentExecPool.hpp
  include/alpaka/kernel/TaskKernelCpuFibers.hpp
  include/alpaka/kernel/TaskKernelCpuOmp2Blocks.hpp
  include/alpaka/kernel/TaskKernelCpuOmp2Threads.hpp
  include/alpaka/kernel/TaskKernelCpuOmp4.hpp
  include/alpaka/kernel/TaskKernelCpuSerial.hpp
  include/alpaka/kernel/TaskKernelCpuTbbBlocks.hpp
  include/alpaka/kernel/TaskKernelCpuThreads.hpp
  include/alpaka/kernel/TaskKernelGpuCudaRt.hpp
  include/alpaka/kernel/TaskKernelGpuHipRt.hpp
  script/travis/prepare_sanitizers.sh
Labels: enhancement, refactoring

#751 CMake: Honor _ROOT Env Hints
  CMakeLists.txt
  alpakaConfig.cmake
  example/bufferCopy/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/reduce/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  test/CMakeLists.txt
Labels: install, warning

#749 Enhance documentation
  doc/markdown/user/implementation/library/Usage.md
Labels: documentation

#753 Relicense Examples: ISC
  example/CMakeLists.txt
  example/bufferCopy/CMakeLists.txt
  example/bufferCopy/src/bufferCopy.cpp
  example/helloWorld/CMakeLists.txt
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/CMakeLists.txt
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/reduce/CMakeLists.txt
  example/reduce/src/alpakaConfig.hpp
  example/reduce/src/iterator.hpp
  example/reduce/src/kernel.hpp
  example/reduce/src/reduce.cpp
  example/vectorAdd/CMakeLists.txt
  example/vectorAdd/src/main.cpp
Labels: example, relicense
