Repository alpaka-group/alpaka, pull requests merged in 2019-01, with the labels that each got.

#717 Update tested versions
  .travis.yml
Labels: testing

#718 Vendor Catch2: v2.5.0
  .appveyor.yml
  .travis.yml
  script/travis/before_install.sh
  script/travis/docker_install.sh
  script/travis/docker_run.sh
  script/travis/install.sh
  script/travis/install_catch2.sh
  script/travis/run.sh
  test/CMakeLists.txt
  thirdParty/catch2/include/catch2/catch.hpp
Labels: testing

#715 Move windows CI builds from appveyor to Travis CI.
  .appveyor.yml
  .travis.yml
  README.md
  alpakaConfig.cmake
  script/travis/after_failure.sh
  script/travis/before_install.sh
  script/travis/docker_install.sh
  script/travis/docker_run.sh
  script/travis/install.sh
  script/travis/install_boost.sh
  script/travis/install_tbb.sh
  script/travis/print_travisEnv.sh
  script/travis/run.sh
  script/travis/run_build.sh
  script/travis/script.sh
  test/unit/mem/view/CMakeLists.txt
Labels: enhancement, testing

#721 Use empty ALPAKA_CI_SANITIZERS as default for all jobs
  .travis.yml
Labels: refactoring, testing

#724 Execute tests on windows
  .travis.yml
  script/travis/run.sh
  script/travis/run_build.sh
  script/travis/run_tests.sh
Labels: testing

#727 Clean up usage of catch2
  test/CMakeLists.txt
  test/common/CMakeLists.txt
Labels: enhancement, testing

#729 Test multiple boost versions in windows builds
  .travis.yml
Labels: testing

#730 Fix CI not building HIP, replace ALPAKA_HIP_ARCH with ALPAKA_CUDA_ARCH, clean-up HIP CI handling
  .travis.yml
  Findalpaka.cmake
  alpakaConfig.cmake
  example/bufferCopy/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/reduce/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  include/alpaka/acc/AccGpuHipRt.hpp
  include/alpaka/exec/ExecGpuHipRt.hpp
  script/travis/before_install.sh
  script/travis/docker_install.sh
  script/travis/docker_run.sh
  script/travis/install.sh
  script/travis/run.sh
  script/travis/run_build.sh
Labels: backend-HIP, bug, testing

#731 Rename ALPAKA_CI_BOOST_ROOT_DIR to BOOST_ROOT
  .travis.yml
  script/travis/docker_install.sh
  script/travis/docker_run.sh
  script/travis/install_boost.sh
  script/travis/run_build.sh
Labels: testing

#733 Add additional checks for OpenMP executors
  .travis.yml
  include/alpaka/exec/ExecCpuOmp2Blocks.hpp
  include/alpaka/exec/ExecCpuOmp2Threads.hpp
Labels: backend-OpenMP, enhancement

#737 [WIP] Prepare CI scripts for osx
  .travis.yml
  script/travis/before_install.sh
  script/travis/docker_install.sh
  script/travis/docker_run.sh
  script/travis/install.sh
  script/travis/install_boost.sh
  script/travis/run.sh
  script/travis/run_build.sh
  script/travis/script.sh
Labels: refactoring

#739 Add osx tests to CI
  .travis.yml
  README.md
  alpakaConfig.cmake
  include/alpaka/dev/cpu/SysInfo.hpp
  script/travis/before_install.sh
  script/travis/docker_install.sh
  script/travis/docker_run.sh
  script/travis/install_boost.sh
  script/travis/install_cmake.sh
  script/travis/run.sh
  script/travis/run_build.sh
  script/travis/run_tests.sh
Labels: machine/system, testing, work in progress
