Repository alpaka-group/alpaka, pull requests merged in 2020-05, with the labels that each got.

#991 fix CMake compiler option handling
  cmake/alpakaCommon.cmake
Labels: bug

#996 Test boost 1.72 and 1.73
  .github/workflows/ci.yml
  .travis.yml
Labels: testing

#997 Fix conversion warning in TinyMT
  include/alpaka/rand/TinyMT/tinymt32.h
Labels: warning

#998 Add support for clang 10
  .travis.yml
  README.md
  script/install_clang.sh
Labels: testing

#1001 TinyMT: Upstream Update
  include/alpaka/rand/TinyMT/tinymt32.h
Labels: Backend-Boost.Fiber, Backend-OpenMP, Backend-TBB, Backend-std::thread, enhancement, warning

#1006 update required HIP version to 3.3.0
  .travis.yml
  README.md
  cmake/alpakaCommon.cmake
  script/install_hip.sh
Labels: Backend-HIP, bug, testing

#1007 Test Ubuntu 20.04
  .travis.yml
  script/before_install.sh
  script/install.sh
  script/install_clang.sh
  script/install_cuda.sh
Labels: testing

#1008 Fix clang-CUDA warning in 2D memory allocation
  include/alpaka/mem/buf/BufUniformCudaHipRt.hpp
  test/common/include/alpaka/test/dim/TestDims.hpp
Labels: warning

#1010 Move CI builds completely from Travis CI to Github Actions
  .github/workflows/ci.yml
  .travis.yml
  CMakeLists.txt
  README.md
  script/docker_install.sh
  script/print_env.sh
  script/run_generate.sh
Labels: testing

#1012 Vec: rm unused static constexpr to enable GCC OMP4
  include/alpaka/vec/Vec.hpp
Labels: refactoring

#1004 Add popcount intrinsic
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
  include/alpaka/intrinsic/IntrinsicCpu.hpp
  include/alpaka/intrinsic/IntrinsicUniformCudaHipBuiltIn.hpp
  include/alpaka/intrinsic/Traits.hpp
  test/unit/CMakeLists.txt
  test/unit/intrinsic/CMakeLists.txt
  test/unit/intrinsic/src/IntrinsicTest.cpp
Labels: enhancement

#1016 Disable automatic build of examples and test cases
  CMakeLists.txt
  script/run_generate.sh
Labels: testing
