Repository alpaka-group/alpaka, pull requests merged in 2020-07, with the labels that each got.

#1063 Add a guard around sanity checks for Omp2Threads accelerator
  include/alpaka/kernel/TaskKernelCpuOmp2Threads.hpp
Labels: Backend-OpenMP

#1049 fix intrinsic `ffs` for HIP
  include/alpaka/intrinsic/IntrinsicUniformCudaHipBuiltIn.hpp
Labels: Backend-HIP, bug

#1062 documentation: change C++11 to C++14
  .zenodo.json
  README.md
  docs/source/usage/implementation.rst
  docs/source/usage/implementation/library.rst
  example/vectorAdd/src/vectorAdd.cpp
Labels: bug, documentation

#1064 fix CUDA/HIP accelerator concept usage
  include/alpaka/acc/AccGpuCudaRt.hpp
  include/alpaka/acc/AccGpuHipRt.hpp
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
Labels: Backend-CUDA, Backend-HIP, bug

#1057 Add cheat sheet to the docs
  docs/cheatsheet/README.md
  docs/cheatsheet/cheatsheet.style
  docs/requirements.txt
  docs/source/conf.py
  docs/source/dev/sphinx.rst
  docs/source/index.rst
  docs/source/usage/cheatsheet.rst
Labels: documentation

#1070 Redefine BOOST_COMP_INTEL the same way BOOST_COMP_NVCC is handled
  include/alpaka/core/BoostPredef.hpp
Labels: bug

#1071 fix installation
  CMakeLists.txt
Labels: bug, install

#1073 build type compiler flags not passed to nvcc
  cmake/alpakaCommon.cmake
Labels: bug

#1077 Allow to filter specific jobs based on commit message
  .github/workflows/ci.yml
Labels: testing

#1078 Remove duplication of names from github actions matrix
  .github/workflows/ci.yml
Labels: testing

#1082 BoostPredef.hpp: Add redefinition of BOOST_COMP_PGI
  include/alpaka/core/BoostPredef.hpp
Labels: enhancement

#1076 [WIP] Add support for CUDA 11
  .github/workflows/ci.yml
  README.md
  script/install_cuda.sh
  test/common/devCompileOptions.cmake
Labels: Backend-CUDA, enhancement

#1085 fix min/max return type deduction
  include/alpaka/math/max/MaxUniformCudaHipBuiltIn.hpp
  include/alpaka/math/min/MinUniformCudaHipBuiltIn.hpp
Labels: Backend:CUDA, Backend:HIP, Type:Bug

#1087 Test CMake 3.18.0
  .github/workflows/ci.yml
Labels: Backend:CUDA, Type:Testing

#1088 cmake: fix boost fiber linking
  cmake/alpakaCommon.cmake
Labels: Type:Bug

#1089 Use runner.os instead of manually defining ALPAKA_CI_OS_NAME
  .github/workflows/ci.yml
  script/after_failure.sh
  script/before_install.sh
  script/ci.sh
  script/docker_install.sh
  script/docker_run.sh
  script/install.sh
  script/install_analysis.sh
  script/install_boost.sh
  script/install_cmake.sh
  script/install_cuda.sh
  script/install_tbb.sh
  script/print_env.sh
  script/run.sh
  script/run_analysis.sh
  script/run_build.sh
  script/run_generate.sh
  script/run_tests.sh
Labels: Type:Testing

#1090 fix warp functions
  include/alpaka/warp/WarpUniformCudaHipBuiltIn.hpp
Labels: Backend:CUDA, Backend:HIP, Type:Bug

#1092 use fixed size integral types
  include/alpaka/intrinsic/IntrinsicCpu.hpp
  include/alpaka/intrinsic/IntrinsicUniformCudaHipBuiltIn.hpp
  include/alpaka/intrinsic/Traits.hpp
  include/alpaka/warp/WarpUniformCudaHipBuiltIn.hpp
  test/unit/intrinsic/src/Popcount.cpp
Labels: Backend:CUDA, Backend:HIP, Type:Bug

#1095 Add unit tests for work div
  test/unit/CMakeLists.txt
  test/unit/workDiv/CMakeLists.txt
  test/unit/workDiv/src/WorkDivHelpersTest.cpp
Labels: Type:Testing

#1094 remove boost::aligned_alloc
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuOmp4.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/block/shared/dyn/BlockSharedMemDynAlignedAlloc.hpp
  include/alpaka/block/shared/st/BlockSharedMemStMasterSync.hpp
  include/alpaka/block/shared/st/BlockSharedMemStNoSync.hpp
  include/alpaka/core/AlignedAlloc.hpp
  include/alpaka/mem/alloc/AllocCpuAligned.hpp
  include/alpaka/mem/buf/BufCpu.hpp
Labels: Type:Refactoring

#1099 Use `apt-get` to install clang
  .github/workflows/ci.yml
  include/alpaka/workdiv/WorkDivHelpers.hpp
  script/before_install.sh
  script/docker_install.sh
  script/docker_run.sh
  script/install_boost.sh
  script/install_clang.sh
  script/run.sh
Labels: OS:Linux, Type:Testing

#1098 Replace usage of custom ALPAKA_CI_DOCKER_BASE_IMAGE_NAME with `/etc/os-release`
  script/before_install.sh
  script/docker_install.sh
  script/install.sh
  script/install_cuda.sh
Labels: Type:Enhancement, Type:Testing

#1104 Change examples (except reduce) to use getValidWorkDiv
  example/bufferCopy/src/bufferCopy.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
Labels: Type:Bug, Type:Enhancement, Type:Example

#1079 Tidy up the heat equation example
  example/heatEquation/src/heatEquation.cpp
Labels: Type:Example, Type:Refactoring

#1107 fix HIP-clang compile
  include/alpaka/rand/RandUniformCudaHipRand.hpp
Labels: Backend:HIP, Type:Bug
