Repository alpaka-group/alpaka, pull requests merged in 2020-06, with the labels that each got.

#1014 emulate hip/cuda-Memcpy3D with a kernel
  .github/workflows/ci.yml
  cmake/alpakaCommon.cmake
  include/alpaka/mem/buf/uniformCudaHip/Copy.hpp
  script/run_generate.sh
Labels: Backend-CUDA, Backend-HIP, enhancement, testing

#1017 simplify alpaka usage
  example/bufferCopy/src/bufferCopy.cpp
  example/heatEquation/src/heatEquation.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/reduce/src/alpakaConfig.hpp
  example/reduce/src/reduce.cpp
  example/vectorAdd/src/vectorAdd.cpp
  include/alpaka/dev/DevCpu.hpp
  include/alpaka/dev/DevUniformCudaHipRt.hpp
  include/alpaka/dev/Traits.hpp
  include/alpaka/mem/buf/Traits.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
  include/alpaka/mem/view/ViewSubView.hpp
  include/alpaka/pltf/PltfUniformCudaHipRt.hpp
  include/alpaka/pltf/Traits.hpp
Labels: refactoring

#1023 Update the install documentation
  docs/source/install/instructions.rst
Labels: documentation, install

#1027 Add missing doxygen for TIdx parameter of mem::buf::alloc
  include/alpaka/mem/buf/Traits.hpp
Labels: documentation

#1031 Remove saving created docker images
  .github/workflows/ci.yml
  script/docker_install.sh
  script/docker_run.sh
Labels: testing

#1030 Test gcc 10
  .github/workflows/ci.yml
  README.md
Labels: testing

#1029 Use structured offset for SubView tests instead of uniform 1
  test/common/include/alpaka/test/Extent.hpp
  test/unit/idx/src/MapIdx.cpp
  test/unit/mem/buf/src/BufTest.cpp
  test/unit/mem/p2p/src/P2P.cpp
  test/unit/mem/view/src/ViewPlainPtrTest.cpp
  test/unit/mem/view/src/ViewSubViewTest.cpp
Labels: testing

#1044 Apply some clang-tidy fixes
  include/alpaka/core/Debug.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
  include/alpaka/mem/view/ViewSubView.hpp
  include/alpaka/queue/QueueGenericThreadsBlocking.hpp
  include/alpaka/queue/QueueGenericThreadsNonBlocking.hpp
  include/alpaka/vec/Vec.hpp
Labels: enhancement

#1043 Reduce test buffer sizes to fix tests with small Idx types
  test/common/include/alpaka/test/Extent.hpp
Labels: bug

#1047 Use std::invoke_result_t instead of std::result_of_t when available
  include/alpaka/kernel/Traits.hpp
Labels: enhancement

#1048 Fix doxygen html generation
  script/push_doc.sh
  script/run_doxygen.sh
Labels: bug, documentation

#1022 Examples: Enable subdirectories and use alpaka_ROOT
  example/bufferCopy/CMakeLists.txt
  example/heatEquation/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/reduce/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
Labels: refactoring

#1052 Readme fix used CUDA version for HIP
  README.md
Labels: documentation

#1054 Update install instructions with cmake --install instead of make install
  docs/source/install/instructions.rst
Labels: documentation
