Repository alpaka-group/alpaka, pull requests merged in 2020-02, with the labels that each got.

#923 Fix exception in TaskKernelCpuOmp2Blocks when OMP_NUM_THREADS==1
  .travis.yml
  include/alpaka/kernel/TaskKernelCpuOmp2Blocks.hpp
Labels: bug

#926 test: fix implicit cast warning
  test/unit/math/sincos/src/sincos.cpp
Labels: testing, warning

#925 Update CI to more recent CMake versions
  .travis.yml
  CMakeLists.txt
  README.md
  alpakaConfig.cmake
  cmake/addExecutable.cmake
  cmake/addLibrary.cmake
  example/CMakeLists.txt
  example/bufferCopy/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/reduce/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  test/CMakeLists.txt
  test/analysis/CMakeLists.txt
  test/common/CMakeLists.txt
  test/integ/CMakeLists.txt
  test/unit/CMakeLists.txt
Labels: documentation, install, testing

#932 Disable Windows+CUDA builds as they are broken
  .travis.yml
Labels: OS-Windows, bug, testing

#933 Remove setting cmake policies
  CMakeLists.txt
  alpakaConfig.cmake
  cmake/addExecutable.cmake
  cmake/addLibrary.cmake
  cmake/common.cmake
  example/bufferCopy/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/reduce/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  test/CMakeLists.txt
Labels: enhancement

#935 gitignore: more IntelliJ/KDevelop
  .gitignore
Labels: enhancement

#921 Installation via CMake
  .travis.yml
  CMakeLists.txt
  Findalpaka.cmake
  alpakaConfig.cmake
  cmake/alpakaCommon.cmake
  cmake/alpakaConfig.cmake.in
  cmake/modules/FindTBB.cmake
  example/CMakeLists.txt
  example/bufferCopy/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/reduce/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  script/travis/install_tbb.sh
  script/travis/run.sh
  script/travis/run_build.sh
  test/CMakeLists.txt
  test/analysis/CMakeLists.txt
  test/analysis/headerCheck/CMakeLists.txt
  test/common/CMakeLists.txt
  test/integ/CMakeLists.txt
  test/integ/axpy/CMakeLists.txt
  test/integ/cudaOnly/CMakeLists.txt
  test/integ/mandelbrot/CMakeLists.txt
  test/integ/matMul/CMakeLists.txt
  test/integ/separableCompilation/CMakeLists.txt
  test/integ/sharedMem/CMakeLists.txt
  test/unit/CMakeLists.txt
  test/unit/acc/CMakeLists.txt
  test/unit/atomic/CMakeLists.txt
  test/unit/block/shared/CMakeLists.txt
  test/unit/block/sync/CMakeLists.txt
  test/unit/core/CMakeLists.txt
  test/unit/event/CMakeLists.txt
  test/unit/idx/CMakeLists.txt
  test/unit/kernel/CMakeLists.txt
  test/unit/math/sincos/CMakeLists.txt
  test/unit/mem/buf/CMakeLists.txt
  test/unit/mem/p2p/CMakeLists.txt
  test/unit/mem/view/CMakeLists.txt
  test/unit/meta/CMakeLists.txt
  test/unit/queue/CMakeLists.txt
  test/unit/rand/CMakeLists.txt
  test/unit/time/CMakeLists.txt
  test/unit/vec/CMakeLists.txt
Labels: install

#937 Extract CatchMain into separate folder/CMakeLists.txt
  test/CMakeLists.txt
  test/catch_main/CMakeLists.txt
  test/catch_main/src/CatchMain.cpp
Labels: refactoring, testing

#938 Move dev compile options into tests
  CMakeLists.txt
  test/common/CMakeLists.txt
  test/common/devCompileOptions.cmake
Labels: refactoring, testing
