Repository alpaka-group/alpaka, pull requests merged in 2020-01, with the labels that each got.

#901 Fix TBB installation in CI
  script/travis/install_tbb.sh
Labels: bug, testing

#899 Add support for XCode 11.3
  .travis.yml
Labels: testing

#902 backport to 0.3.6
  include/alpaka/core/Cuda.hpp
  include/alpaka/math/abs/AbsCudaBuiltIn.hpp
  include/alpaka/math/abs/Traits.hpp
  include/alpaka/math/acos/AcosCudaBuiltIn.hpp
  include/alpaka/math/acos/Traits.hpp
  include/alpaka/math/asin/AsinCudaBuiltIn.hpp
  include/alpaka/math/asin/Traits.hpp
  include/alpaka/math/atan/AtanCudaBuiltIn.hpp
  include/alpaka/math/atan/Traits.hpp
  include/alpaka/math/atan2/Atan2CudaBuiltIn.hpp
  include/alpaka/math/atan2/Traits.hpp
  include/alpaka/math/cbrt/CbrtCudaBuiltIn.hpp
  include/alpaka/math/cbrt/Traits.hpp
  include/alpaka/math/ceil/CeilCudaBuiltIn.hpp
  include/alpaka/math/ceil/Traits.hpp
  include/alpaka/math/cos/CosCudaBuiltIn.hpp
  include/alpaka/math/cos/Traits.hpp
  include/alpaka/math/erf/ErfCudaBuiltIn.hpp
  include/alpaka/math/erf/Traits.hpp
  include/alpaka/math/exp/ExpCudaBuiltIn.hpp
  include/alpaka/math/exp/Traits.hpp
  include/alpaka/math/floor/FloorCudaBuiltIn.hpp
  include/alpaka/math/floor/Traits.hpp
  include/alpaka/math/fmod/FmodCudaBuiltIn.hpp
  include/alpaka/math/fmod/Traits.hpp
  include/alpaka/math/log/LogCudaBuiltIn.hpp
  include/alpaka/math/log/Traits.hpp
  include/alpaka/math/max/MaxCudaBuiltIn.hpp
  include/alpaka/math/max/Traits.hpp
  include/alpaka/math/min/MinCudaBuiltIn.hpp
  include/alpaka/math/min/Traits.hpp
  include/alpaka/math/pow/PowCudaBuiltIn.hpp
  include/alpaka/math/pow/Traits.hpp
  include/alpaka/math/remainder/RemainderCudaBuiltIn.hpp
  include/alpaka/math/remainder/Traits.hpp
  include/alpaka/math/round/RoundCudaBuiltIn.hpp
  include/alpaka/math/round/Traits.hpp
  include/alpaka/math/rsqrt/RsqrtCudaBuiltIn.hpp
  include/alpaka/math/rsqrt/Traits.hpp
  include/alpaka/math/sin/SinCudaBuiltIn.hpp
  include/alpaka/math/sin/Traits.hpp
  include/alpaka/math/sqrt/SqrtCudaBuiltIn.hpp
  include/alpaka/math/sqrt/Traits.hpp
  include/alpaka/math/tan/TanCudaBuiltIn.hpp
  include/alpaka/math/tan/Traits.hpp
  include/alpaka/math/trunc/Traits.hpp
  include/alpaka/math/trunc/TruncCudaBuiltIn.hpp
Labels: bug

#903 remove beta status
  README.md
Labels: documentation

#904 Remove Support for ubuntu 14.04
  .travis.yml
  script/travis/before_install.sh
  test/unit/mem/p2p/src/P2P.cpp
Labels: documentation, testing

#905 backport of #901 to the release branch
  script/travis/install_tbb.sh
Labels: bug, testing

#906 Raise minimum supported boost version from 1.62.0 to 1.65.1
  .travis.yml
  README.md
  alpakaConfig.cmake
  include/alpaka/core/BoostPredef.hpp
  script/travis/before_install.sh
Labels: testing

#907 Replace alpaka::meta::IndexSequence with C++14 std::index_sequence
  include/alpaka/kernel/TaskKernelCpuOmp2Threads.hpp
  include/alpaka/meta/ApplyTuple.hpp
Labels: enhancement

#910 remove beta status
  README.md
Labels: documentation

#909 Use std::integer_sequence instead of own IntegerSequence
  include/alpaka/extent/Traits.hpp
  include/alpaka/mem/view/ViewSubView.hpp
  include/alpaka/meta/IntegerSequence.hpp
  include/alpaka/meta/NdLoop.hpp
  include/alpaka/vec/Traits.hpp
  include/alpaka/vec/Vec.hpp
  test/unit/vec/src/VecTest.cpp
Labels: enhancement

#913 Add forgotten TBB accelerator to the list in comments of the examples
  example/bufferCopy/src/bufferCopy.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/vectorAdd/src/vectorAdd.cpp
Labels: documentation, example

#914 Add a reference to cupla to readme
  README.md
Labels: documentation

#918 Remove commented out code
  include/alpaka/core/Cuda.hpp
  include/alpaka/core/Hip.hpp
  include/alpaka/dev/cpu/SysInfo.hpp
  include/alpaka/dim/DimIntegralConst.hpp
  include/alpaka/kernel/TaskKernelGpuCudaRt.hpp
  include/alpaka/kernel/TaskKernelGpuHipRt.hpp
Labels: enhancement

#917 Add info on pinning to the CUDA mapping docs
  doc/markdown/user/implementation/mapping/CUDA.md
Labels: Backend-CUDA, Backend-HIP, documentation

#916 Add automated gh-pages deployment for branch develop
  .github/workflows/gh-pages.yml
  doc/doxygen/Doxyfile
  doc/markdown/Index.md
  doc/markdown/dev/gh-pages.md
  script/travis/install_doxygen.sh
  script/travis/push_doc.sh
  script/travis/run_doxygen.sh
Labels: enhancement
