Repository alpaka-group/alpaka, pull requests merged in 2020-08, with the labels that each got.

#1109 Invoke docker run only once instead of twice
  script/ci.sh
  script/docker_ci.sh
  script/docker_install.sh
Labels: OS:Linux, Type:Testing

#1108 fix error handling CUDA/HIP
  include/alpaka/core/UniformCudaHip.hpp
Labels: Backend:CUDA, Backend:HIP, Type:Bug

#1111 Explicitly require backends and do not enable them by default
  .github/workflows/ci.yml
  README.md
  cmake/alpakaCommon.cmake
  script/install_clang.sh
  script/run_generate.sh
Labels: Priority: 1, Type:Enhancement

#1112 fix how to set HIP target architecture
  cmake/alpakaCommon.cmake
Labels: Priority: 1, Type:Bug

#1113 set HIP-clang as default compiler for HIP
  cmake/alpakaCommon.cmake
Labels: Backend:HIP

#1115 Clean up CI scripts
  .github/workflows/ci.yml
  README.md
  script/run.sh
Labels: Type:Testing

#1114 Make filtered CI jobs not succeed
  .github/workflows/ci.yml
Labels: Type:Testing

#1116 ALPAKA_DECAY_T: Fix INTEL detection, Add PGI
  include/alpaka/core/Decay.hpp
Labels: Type:Bug, Type:Enhancement

#1121 Add support for NVCC + VS 2019
  .github/workflows/ci.yml
  README.md
  test/unit/kernel/src/KernelLambda.cpp
Labels: Backend:CUDA, OS:Windows, Type:Enhancement, Type:Testing

#1131 Add --Wno-extra-semi-stmt for clang > 7 (new warning flag)
  test/common/devCompileOptions.cmake
Labels: Type:Enhancement, Type:Warning

#1128 Fix and improve block shared mem st member sanity checks
  include/alpaka/block/shared/st/BlockSharedMemStMember.hpp
Labels: Type:Bug, Type:Enhancement

#1136 Update badge to C++14
  README.md
Labels: Type:Documentation

#1086 Add CUDA 11 support for Windows
  .github/workflows/ci.yml
  README.md
  script/install_cuda.sh
Labels: Backend:CUDA, OS:Windows
