Repository alpaka-group/alpaka, pull requests merged in 2020-10, with the labels that each got.

#1152 fix CUDA/HIP cmake flags
  cmake/alpakaCommon.cmake
Labels: Backend:CUDA, Backend:HIP, Type:Bug

#1150 Remove namespace alpaka::workdiv
  example/bufferCopy/src/bufferCopy.cpp
  example/heatEquation/src/heatEquation.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/monteCarloIntegration/src/monteCarloIntegration.cpp
  example/reduce/src/alpakaConfig.hpp
  example/reduce/src/kernel.hpp
  example/vectorAdd/src/vectorAdd.cpp
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
  include/alpaka/acc/AccOmp5.hpp
  include/alpaka/idx/Accessors.hpp
  include/alpaka/idx/bt/IdxBtOmp.hpp
  include/alpaka/idx/gb/IdxGbLinear.hpp
  include/alpaka/kernel/TaskKernelCpuFibers.hpp
  include/alpaka/kernel/TaskKernelCpuOmp2Blocks.hpp
  include/alpaka/kernel/TaskKernelCpuOmp2Threads.hpp
  include/alpaka/kernel/TaskKernelCpuSerial.hpp
  include/alpaka/kernel/TaskKernelCpuTbbBlocks.hpp
  include/alpaka/kernel/TaskKernelCpuThreads.hpp
  include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp
  include/alpaka/kernel/TaskKernelOmp5.hpp
  include/alpaka/mem/buf/SetKernel.hpp
  include/alpaka/mem/buf/omp5/Set.hpp
  include/alpaka/workdiv/Traits.hpp
  include/alpaka/workdiv/WorkDivHelpers.hpp
  include/alpaka/workdiv/WorkDivMembers.hpp
  include/alpaka/workdiv/WorkDivUniformCudaHipBuiltIn.hpp
  test/common/include/alpaka/test/KernelExecutionFixture.hpp
  test/integ/axpy/src/axpy.cpp
  test/integ/mandelbrot/src/mandelbrot.cpp
  test/integ/matMul/src/matMul.cpp
  test/integ/separableCompilation/src/main.cpp
  test/integ/sharedMem/src/sharedMem.cpp
  test/unit/block/sync/src/BlockSync.cpp
  test/unit/block/sync/src/BlockSyncPredicate.cpp
  test/unit/kernel/src/KernelGenericLambda.cpp
  test/unit/kernel/src/KernelLambda.cpp
  test/unit/kernel/src/KernelWithTemplate.cpp
  test/unit/kernel/src/KernelWithTemplateArgumentDeduction.cpp
  test/unit/kernel/src/KernelWithoutTemplatedAccParam.cpp
  test/unit/math/src/math.cpp
  test/unit/mem/view/src/ViewStaticAccMem.cpp
  test/unit/queue/src/CollectiveQueue.cpp
  test/unit/warp/src/Activemask.cpp
  test/unit/warp/src/All.cpp
  test/unit/warp/src/Any.cpp
  test/unit/warp/src/Ballot.cpp
  test/unit/workDiv/src/WorkDivHelpersTest.cpp
Labels: Type:Refactoring

#1155 Remove namespace alpaka::atomic
  example/monteCarloIntegration/src/monteCarloIntegration.cpp
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
  include/alpaka/acc/AccOmp5.hpp
  include/alpaka/atomic/AtomicHierarchy.hpp
  include/alpaka/atomic/AtomicNoOp.hpp
  include/alpaka/atomic/AtomicOmpBuiltIn.hpp
  include/alpaka/atomic/AtomicStdLibLock.hpp
  include/alpaka/atomic/AtomicUniformCudaHipBuiltIn.hpp
  include/alpaka/atomic/Op.hpp
  include/alpaka/atomic/Traits.hpp
  test/integ/sharedMem/src/sharedMem.cpp
  test/unit/atomic/src/AtomicTest.cpp
Labels: Type:Refactoring

#1159 Remove namespace alpaka::kernel
  example/bufferCopy/src/bufferCopy.cpp
  example/heatEquation/src/heatEquation.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/monteCarloIntegration/src/monteCarloIntegration.cpp
  example/reduce/src/reduce.cpp
  example/vectorAdd/src/vectorAdd.cpp
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGpuCudaRt.hpp
  include/alpaka/acc/AccGpuHipRt.hpp
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
  include/alpaka/acc/AccOmp5.hpp
  include/alpaka/acc/Traits.hpp
  include/alpaka/kernel/TaskKernelCpuFibers.hpp
  include/alpaka/kernel/TaskKernelCpuOmp2Blocks.hpp
  include/alpaka/kernel/TaskKernelCpuOmp2Threads.hpp
  include/alpaka/kernel/TaskKernelCpuSerial.hpp
  include/alpaka/kernel/TaskKernelCpuTbbBlocks.hpp
  include/alpaka/kernel/TaskKernelCpuThreads.hpp
  include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp
  include/alpaka/kernel/TaskKernelOmp5.hpp
  include/alpaka/kernel/Traits.hpp
  include/alpaka/mem/buf/omp5/Set.hpp
  test/common/include/alpaka/test/KernelExecutionFixture.hpp
  test/common/include/alpaka/test/queue/QueueCpuOmp2Collective.hpp
  test/integ/axpy/src/axpy.cpp
  test/integ/mandelbrot/src/mandelbrot.cpp
  test/integ/matMul/src/matMul.cpp
  test/integ/separableCompilation/src/main.cpp
  test/integ/sharedMem/src/sharedMem.cpp
  test/unit/block/shared/src/BlockSharedMemDyn.cpp
  test/unit/block/sync/src/BlockSync.cpp
  test/unit/math/src/math.cpp
  test/unit/queue/src/CollectiveQueue.cpp
Labels: Type:Refactoring

#1161 Remove namespace alpaka::mem
  example/bufferCopy/src/bufferCopy.cpp
  example/heatEquation/src/heatEquation.cpp
  example/monteCarloIntegration/src/monteCarloIntegration.cpp
  example/reduce/src/reduce.cpp
  example/vectorAdd/src/vectorAdd.cpp
  include/alpaka/dev/DevCpu.hpp
  include/alpaka/dev/DevOmp5.hpp
  include/alpaka/dev/DevUniformCudaHipRt.hpp
  include/alpaka/mem/alloc/AllocCpuAligned.hpp
  include/alpaka/mem/alloc/AllocCpuNew.hpp
  include/alpaka/mem/alloc/Traits.hpp
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/mem/buf/BufOmp5.hpp
  include/alpaka/mem/buf/BufUniformCudaHipRt.hpp
  include/alpaka/mem/buf/SetKernel.hpp
  include/alpaka/mem/buf/Traits.hpp
  include/alpaka/mem/buf/cpu/Copy.hpp
  include/alpaka/mem/buf/cpu/Set.hpp
  include/alpaka/mem/buf/omp5/Copy.hpp
  include/alpaka/mem/buf/omp5/Set.hpp
  include/alpaka/mem/buf/uniformCudaHip/Copy.hpp
  include/alpaka/mem/buf/uniformCudaHip/Set.hpp
  include/alpaka/mem/view/Traits.hpp
  include/alpaka/mem/view/ViewCompileTimeArray.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
  include/alpaka/mem/view/ViewStdArray.hpp
  include/alpaka/mem/view/ViewStdVector.hpp
  include/alpaka/mem/view/ViewSubView.hpp
  test/common/include/alpaka/test/KernelExecutionFixture.hpp
  test/common/include/alpaka/test/mem/view/Iterator.hpp
  test/common/include/alpaka/test/mem/view/ViewTest.hpp
  test/integ/axpy/src/axpy.cpp
  test/integ/mandelbrot/src/mandelbrot.cpp
  test/integ/matMul/src/matMul.cpp
  test/integ/separableCompilation/src/main.cpp
  test/integ/sharedMem/src/sharedMem.cpp
  test/unit/idx/src/MapIdxPitchBytes.cpp
  test/unit/math/src/Buffer.hpp
  test/unit/mem/buf/src/BufTest.cpp
  test/unit/mem/copy/src/BufSlicing.cpp
  test/unit/mem/p2p/src/P2P.cpp
  test/unit/mem/view/src/ViewPlainPtrTest.cpp
  test/unit/mem/view/src/ViewStaticAccMem.cpp
  test/unit/mem/view/src/ViewSubViewTest.cpp
  test/unit/queue/src/CollectiveQueue.cpp
Labels: Type:Refactoring

#1162 Remove namespace alpaka::offset
  include/alpaka/core/Cuda.hpp
  include/alpaka/core/Hip.hpp
  include/alpaka/idx/bt/IdxBtUniformCudaHipBuiltIn.hpp
  include/alpaka/idx/gb/IdxGbUniformCudaHipBuiltIn.hpp
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/mem/buf/BufOmp5.hpp
  include/alpaka/mem/buf/BufUniformCudaHipRt.hpp
  include/alpaka/mem/view/ViewCompileTimeArray.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
  include/alpaka/mem/view/ViewStdArray.hpp
  include/alpaka/mem/view/ViewStdVector.hpp
  include/alpaka/mem/view/ViewSubView.hpp
  include/alpaka/offset/Traits.hpp
  include/alpaka/vec/Vec.hpp
  test/common/include/alpaka/test/mem/view/ViewTest.hpp
Labels: Type:Refactoring

#1164 Remove namespace alpaka::intrinsic
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
  include/alpaka/acc/AccOmp5.hpp
  include/alpaka/intrinsic/IntrinsicCpu.hpp
  include/alpaka/intrinsic/IntrinsicFallback.hpp
  include/alpaka/intrinsic/IntrinsicUniformCudaHipBuiltIn.hpp
  include/alpaka/intrinsic/Traits.hpp
  test/unit/intrinsic/src/Ffs.cpp
  test/unit/intrinsic/src/Popcount.cpp
Labels: Type:Refactoring

#1171 Merge adjacent traits namespaces
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGpuCudaRt.hpp
  include/alpaka/acc/AccGpuHipRt.hpp
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
  include/alpaka/acc/AccOmp5.hpp
  include/alpaka/acc/Traits.hpp
  include/alpaka/core/Cuda.hpp
  include/alpaka/core/Hip.hpp
  include/alpaka/dev/DevOmp5.hpp
  include/alpaka/dev/DevUniformCudaHipRt.hpp
  include/alpaka/event/EventGenericThreads.hpp
  include/alpaka/event/EventUniformCudaHipRt.hpp
  include/alpaka/idx/Traits.hpp
  include/alpaka/idx/bt/IdxBtOmp.hpp
  include/alpaka/idx/bt/IdxBtRefFiberIdMap.hpp
  include/alpaka/idx/bt/IdxBtRefThreadIdMap.hpp
  include/alpaka/idx/bt/IdxBtUniformCudaHipBuiltIn.hpp
  include/alpaka/idx/bt/IdxBtZero.hpp
  include/alpaka/idx/gb/IdxGbLinear.hpp
  include/alpaka/idx/gb/IdxGbRef.hpp
  include/alpaka/idx/gb/IdxGbUniformCudaHipBuiltIn.hpp
  include/alpaka/kernel/TaskKernelCpuFibers.hpp
  include/alpaka/kernel/TaskKernelCpuOmp2Blocks.hpp
  include/alpaka/kernel/TaskKernelCpuOmp2Threads.hpp
  include/alpaka/kernel/TaskKernelCpuSerial.hpp
  include/alpaka/kernel/TaskKernelCpuTbbBlocks.hpp
  include/alpaka/kernel/TaskKernelCpuThreads.hpp
  include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp
  include/alpaka/kernel/TaskKernelOmp5.hpp
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/mem/buf/BufOmp5.hpp
  include/alpaka/mem/buf/BufUniformCudaHipRt.hpp
  include/alpaka/mem/view/ViewCompileTimeArray.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
  include/alpaka/mem/view/ViewStdArray.hpp
  include/alpaka/mem/view/ViewStdVector.hpp
  include/alpaka/mem/view/ViewSubView.hpp
  include/alpaka/pltf/PltfCpu.hpp
  include/alpaka/pltf/PltfOmp5.hpp
  include/alpaka/pltf/PltfUniformCudaHipRt.hpp
  include/alpaka/queue/QueueGenericThreadsBlocking.hpp
  include/alpaka/queue/QueueGenericThreadsNonBlocking.hpp
  include/alpaka/queue/QueueUniformCudaHipRtBlocking.hpp
  include/alpaka/queue/QueueUniformCudaHipRtNonBlocking.hpp
  include/alpaka/queue/cuda_hip/QueueUniformCudaHipRtBase.hpp
  include/alpaka/vec/Vec.hpp
  include/alpaka/workdiv/WorkDivMembers.hpp
  include/alpaka/workdiv/WorkDivUniformCudaHipBuiltIn.hpp
  test/common/include/alpaka/test/event/EventHostManualTrigger.hpp
  test/common/include/alpaka/test/queue/QueueCpuOmp2Collective.hpp
Labels: Type:Refactoring

#1172 Add CHANGELOG.md with information copied from release notes
  CHANGELOG.md
Labels: Type:Documentation

#1177 Fix atomic hierarchy usage in the cheatsheet
  docs/source/basic/cheatsheet.rst
Labels: Type:Documentation

#1180 increase version to 0.7.0-develop
  docs/source/conf.py
  include/alpaka/version.hpp
Labels: Type:Documentation
