Repository alpaka-group/alpaka, pull requests merged in 2020-04, with the labels that each got.

#959 Turn QueueCPU* into template QueueGeneric*<TDev>
  include/alpaka/dev/DevCpu.hpp
  include/alpaka/dev/cpu/Wait.hpp
  include/alpaka/event/EventCpu.hpp
  include/alpaka/event/EventGenericThreads.hpp
  include/alpaka/queue/QueueCpuBlocking.hpp
  include/alpaka/queue/QueueCpuNonBlocking.hpp
  include/alpaka/queue/QueueGenericThreadsBlocking.hpp
  include/alpaka/queue/QueueGenericThreadsNonBlocking.hpp
  include/alpaka/queue/cpu/ICpuQueue.hpp
  include/alpaka/queue/cpu/IGenericThreadsQueue.hpp
  test/common/include/alpaka/test/queue/QueueCpuOmp2Collective.hpp
Labels: Backend-OpenMP

#969 update github links to alpaka and cupla
  CMakeLists.txt
  README.md
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
Labels: documentation

#970 Remove unnecessary includes of boost/config.hpp
  include/alpaka/core/Common.hpp
  include/alpaka/core/ConcurrentExecPool.hpp
  include/alpaka/dev/Traits.hpp
  include/alpaka/idx/Accessors.hpp
  include/alpaka/math/abs/Traits.hpp
  include/alpaka/math/acos/Traits.hpp
  include/alpaka/math/asin/Traits.hpp
  include/alpaka/math/atan/Traits.hpp
  include/alpaka/math/atan2/Traits.hpp
  include/alpaka/math/cbrt/Traits.hpp
  include/alpaka/math/ceil/Traits.hpp
  include/alpaka/math/cos/Traits.hpp
  include/alpaka/math/erf/Traits.hpp
  include/alpaka/math/exp/Traits.hpp
  include/alpaka/math/floor/Traits.hpp
  include/alpaka/math/fmod/Traits.hpp
  include/alpaka/math/log/Traits.hpp
  include/alpaka/math/max/Traits.hpp
  include/alpaka/math/min/Traits.hpp
  include/alpaka/math/pow/Traits.hpp
  include/alpaka/math/remainder/Traits.hpp
  include/alpaka/math/round/Traits.hpp
  include/alpaka/math/rsqrt/Traits.hpp
  include/alpaka/math/sin/Traits.hpp
  include/alpaka/math/sincos/Traits.hpp
  include/alpaka/math/sqrt/Traits.hpp
  include/alpaka/math/tan/Traits.hpp
  include/alpaka/math/trunc/Traits.hpp
  include/alpaka/mem/buf/Traits.hpp
  include/alpaka/mem/view/Traits.hpp
  include/alpaka/meta/ApplyTuple.hpp
  include/alpaka/pltf/Traits.hpp
  include/alpaka/rand/Traits.hpp
  include/alpaka/vec/Traits.hpp
  include/alpaka/vec/Vec.hpp
  include/alpaka/workdiv/Traits.hpp
Labels: enhancement

#972 Remove duplicate MacOS build
  .travis.yml
Labels: testing

#973 Always use out-of-class version of vec::createVecFromIndexedFn
  include/alpaka/mem/view/Traits.hpp
  include/alpaka/vec/Vec.hpp
  test/unit/idx/src/MapIdx.cpp
  test/unit/mem/buf/src/BufTest.cpp
  test/unit/mem/p2p/src/P2P.cpp
  test/unit/mem/view/src/ViewPlainPtrTest.cpp
  test/unit/mem/view/src/ViewSubViewTest.cpp
Labels: enhancement

#974 Fix compatibility for MSVC + NVCC + Boost-1.68.0+
  .github/workflows/ci.yml
  include/alpaka/core/Common.hpp
  include/alpaka/core/UniformCudaHip.hpp
  include/alpaka/core/Unroll.hpp
  include/alpaka/core/Unused.hpp
  include/alpaka/dev/cpu/SysInfo.hpp
  include/alpaka/meta/ForEachType.hpp
  include/alpaka/rand/TinyMT/tinymt32.h
  include/alpaka/vec/Vec.hpp
  test/unit/core/src/BoostPredefTest.cpp
  test/unit/kernel/src/KernelWithHostConstexpr.cpp
Labels: Backend-CUDA, OS-Windows, bug

#975 Reenable CI tests for OMP2 after it was fixed in VS 2019 16.5
  .github/workflows/ci.yml
Labels: Backend-OpenMP, OS-Windows, bug

#976 Refactor CI scripts
  script/install.sh
  script/install_analysis.sh
  script/run.sh
  script/run_analysis.sh
  script/run_build.sh
  script/run_generate.sh
  script/run_tests.sh
Labels: refactoring, testing

#977 Simplify vector operator construction
  include/alpaka/vec/Vec.hpp
Labels: refactoring

#979 Add /bigobj to all tests on Windows
  test/common/CMakeLists.txt
Labels: Backend-CUDA, OS-Windows, testing

#980 Add common base class for blocking and non blocking CUDA/HIP queue
  include/alpaka/dev/Traits.hpp
  include/alpaka/event/EventGenericThreads.hpp
  include/alpaka/event/EventUniformCudaHipRt.hpp
  include/alpaka/queue/Properties.hpp
  include/alpaka/queue/QueueGenericThreadsBlocking.hpp
  include/alpaka/queue/QueueGenericThreadsNonBlocking.hpp
  include/alpaka/queue/QueueUniformCudaHipRtBlocking.hpp
  include/alpaka/queue/QueueUniformCudaHipRtNonBlocking.hpp
  include/alpaka/queue/Traits.hpp
  include/alpaka/queue/cuda_hip/QueueUniformCudaHipRtBase.hpp
Labels: Backend-CUDA, Backend-HIP, refactoring

#981 Reduce code duplication in CUDA memcpy and memset implementations
  include/alpaka/mem/buf/uniformCudaHip/Copy.hpp
  include/alpaka/mem/buf/uniformCudaHip/Set.hpp
Labels: Backend-CUDA, Backend-HIP, refactoring

#982 fix missing include
  include/alpaka/queue/QueueUniformCudaHipRtBlocking.hpp
  include/alpaka/queue/QueueUniformCudaHipRtNonBlocking.hpp
Labels: Backend-HIP, bug

#985 Extend supported compiler combinations gcc-8+nvcc 10.1-10.2
  README.md
Labels: bug, documentation

#986 Refactor math operations unit tests
  test/unit/CMakeLists.txt
  test/unit/math/CMakeLists.txt
  test/unit/math/sincos/CMakeLists.txt
  test/unit/math/src/Buffer.hpp
  test/unit/math/src/DataGen.hpp
  test/unit/math/src/Defines.hpp
  test/unit/math/src/Functor.hpp
  test/unit/math/src/math.cpp
  test/unit/math/src/sincos.cpp
Labels: refactoring, testing

#988 Add support for CMake 3.17
  .github/workflows/ci.yml
  .travis.yml
Labels: testing
