Repository alpaka-group/alpaka, pull requests merged in 2020-03, with the labels that each got.

#939 increase required rocm/HIP to 3.1
  .travis.yml
  README.md
  cmake/alpakaCommon.cmake
  doc/markdown/user/implementation/mapping/HIP.md
Labels: Backend-HIP, bug

#941 fix CMake error
  cmake/alpakaCommon.cmake
Labels: Backend-CUDA, bug

#940 unify CUDA/HIP function calls/types
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
  include/alpaka/core/Cuda.hpp
  include/alpaka/core/Hip.hpp
  include/alpaka/core/UniformCudaHip.hpp
  include/alpaka/dev/DevUniformCudaHipRt.hpp
  include/alpaka/event/EventUniformCudaHipRt.hpp
  include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/mem/buf/BufUniformCudaHipRt.hpp
  include/alpaka/mem/buf/uniformCudaHip/Copy.hpp
  include/alpaka/mem/buf/uniformCudaHip/Set.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
  include/alpaka/pltf/PltfUniformCudaHipRt.hpp
  include/alpaka/queue/QueueUniformCudaHipRtBlocking.hpp
  include/alpaka/queue/QueueUniformCudaHipRtNonBlocking.hpp
  test/common/include/alpaka/test/event/EventHostManualTrigger.hpp
Labels: Backend-CUDA, Backend-HIP, refactoring

#947 fix HIP math include
  include/alpaka/math/MathUniformCudaHipBuiltIn.hpp
  include/alpaka/math/abs/AbsUniformCudaHipBuiltIn.hpp
  include/alpaka/math/acos/AcosUniformCudaHipBuiltIn.hpp
  include/alpaka/math/asin/AsinUniformCudaHipBuiltIn.hpp
  include/alpaka/math/atan/AtanUniformCudaHipBuiltIn.hpp
  include/alpaka/math/atan2/Atan2UniformCudaHipBuiltIn.hpp
  include/alpaka/math/cbrt/CbrtUniformCudaHipBuiltIn.hpp
  include/alpaka/math/ceil/CeilUniformCudaHipBuiltIn.hpp
  include/alpaka/math/cos/CosUniformCudaHipBuiltIn.hpp
  include/alpaka/math/erf/ErfUniformCudaHipBuiltIn.hpp
  include/alpaka/math/exp/ExpUniformCudaHipBuiltIn.hpp
  include/alpaka/math/floor/FloorUniformCudaHipBuiltIn.hpp
  include/alpaka/math/fmod/FmodUniformCudaHipBuiltIn.hpp
  include/alpaka/math/log/LogUniformCudaHipBuiltIn.hpp
  include/alpaka/math/max/MaxUniformCudaHipBuiltIn.hpp
  include/alpaka/math/min/MinUniformCudaHipBuiltIn.hpp
  include/alpaka/math/pow/PowUniformCudaHipBuiltIn.hpp
  include/alpaka/math/remainder/RemainderUniformCudaHipBuiltIn.hpp
  include/alpaka/math/round/RoundUniformCudaHipBuiltIn.hpp
  include/alpaka/math/rsqrt/RsqrtUniformCudaHipBuiltIn.hpp
  include/alpaka/math/sin/SinUniformCudaHipBuiltIn.hpp
  include/alpaka/math/sincos/SinCosUniformCudaHipBuiltIn.hpp
  include/alpaka/math/sqrt/SqrtUniformCudaHipBuiltIn.hpp
  include/alpaka/math/tan/TanUniformCudaHipBuiltIn.hpp
  include/alpaka/math/trunc/TruncUniformCudaHipBuiltIn.hpp
Labels: Backend-HIP, bug

#946 fix accelerator auto selection
  cmake/alpakaCommon.cmake
Labels: Backend-HIP, bug

#949 Add support for Visual Studio 2019
  .github/workflows/ci.yml
  .travis.yml
  CMakeLists.txt
  README.md
  script/travis/before_install.sh
  script/travis/install_boost.sh
  script/travis/install_cmake.sh
  script/travis/print_env.sh
  script/travis/print_travisEnv.sh
  script/travis/run_build.sh
  script/travis/script.sh
  test/CMakeLists.txt
Labels: OS-Windows, enhancement, testing

#951 fix missing platform concept
  include/alpaka/pltf/PltfUniformCudaHipRt.hpp
Labels: Backend-CUDA, Backend-HIP, bug

#950 fix CUDA and HIP standalone header
  include/alpaka/standalone/GpuCudaRt.hpp
  include/alpaka/standalone/GpuHipRt.hpp
Labels: Backend-CUDA, Backend-HIP, bug

#953 Fix VS 2017 CUDA builds
  .github/workflows/ci.yml
  .travis.yml
  CMakeLists.txt
  script/travis/before_install.sh
Labels: OS-Windows, testing

#954 allow instances of concept definitions
  include/alpaka/acc/Traits.hpp
  include/alpaka/atomic/Traits.hpp
  include/alpaka/block/shared/dyn/Traits.hpp
  include/alpaka/block/shared/st/Traits.hpp
  include/alpaka/block/sync/Traits.hpp
  include/alpaka/idx/Traits.hpp
  include/alpaka/math/abs/Traits.hpp
  include/alpaka/math/acos/Traits.hpp
  include/alpaka/math/asin/Traits.hpp
  include/alpaka/math/atan/Traits.hpp
  include/alpaka/math/atan2/Traits.hpp
  include/alpaka/math/cbrt/Traits.hpp
  include/alpaka/math/ceil/Traits.hpp
  include/alpaka/math/cos/Traits.hpp
  include/alpaka/math/erf/Traits.hpp
  include/alpaka/math/exp/Traits.hpp
  include/alpaka/math/floor/Traits.hpp
  include/alpaka/math/fmod/Traits.hpp
  include/alpaka/math/log/Traits.hpp
  include/alpaka/math/max/Traits.hpp
  include/alpaka/math/min/Traits.hpp
  include/alpaka/math/pow/Traits.hpp
  include/alpaka/math/remainder/Traits.hpp
  include/alpaka/math/round/Traits.hpp
  include/alpaka/math/rsqrt/Traits.hpp
  include/alpaka/math/sin/Traits.hpp
  include/alpaka/math/sincos/Traits.hpp
  include/alpaka/math/sqrt/Traits.hpp
  include/alpaka/math/tan/Traits.hpp
  include/alpaka/math/trunc/Traits.hpp
  include/alpaka/mem/alloc/Traits.hpp
  include/alpaka/pltf/Traits.hpp
  include/alpaka/rand/Traits.hpp
  include/alpaka/time/Traits.hpp
  include/alpaka/wait/Traits.hpp
  include/alpaka/workdiv/Traits.hpp
  test/unit/core/src/ConceptsTest.cpp
Labels: enhancement

#955 Move scripts out of travis folder
  .github/workflows/ci.yml
  .github/workflows/gh-pages.yml
  .travis.yml
  script/after_failure.sh
  script/before_install.sh
  script/ci.sh
  script/docker_install.sh
  script/docker_run.sh
  script/install.sh
  script/install_analysis.sh
  script/install_boost.sh
  script/install_clang.sh
  script/install_cmake.sh
  script/install_cuda.sh
  script/install_doxygen.sh
  script/install_gcc.sh
  script/install_hip.sh
  script/install_tbb.sh
  script/prepare_sanitizers.sh
  script/print_env.sh
  script/push_doc.sh
  script/run.sh
  script/run_analysis.sh
  script/run_build.sh
  script/run_doxygen.sh
  script/run_tests.sh
  script/set.sh
  script/travis_retry.sh
  test/unit/mem/p2p/src/P2P.cpp
Labels: refactoring, testing

#965 fix windows CI builds
  script/run_build.sh
Labels: bug, testing

#963 fix uninitialized pitch
  include/alpaka/mem/buf/BufUniformCudaHipRt.hpp
Labels: Backend-HIP, bug

#948 fix: missing hipRand and rocRand library
  cmake/alpakaCommon.cmake
Labels: Backend-HIP, bug
