Repository alpaka-group/alpaka, pull requests merged in 2020-12, with the labels that each got.

#1224 Fix a comment copy-paste mistake in Omp5 check output function
  include/alpaka/core/Omp5.hpp
Labels: Backend:OpenMP, Priority: 4, Type:Documentation

#1226 Fix marking of unit tests for concepts
  test/unit/core/src/ConceptsTest.cpp
Labels: Priority: 4, Type:Refactoring, Type:Testing

#1225 Add BOOST_COMP_INTEL to the Boost.Predef unit test
  test/unit/core/src/BoostPredefTest.cpp
Labels: Priority: 4, Type:Testing

#1227 Remove support for CUDA 11.0 with MSVC 2019
  .github/workflows/ci.yml
  README.md
Labels: Backend:CUDA, OS:Windows, Type:Testing

#1229 fix gh-pages branch update
  script/push_doc.sh
Labels: Priority: 1, Type:Bug, Type:Documentation

#1230 fix gh-pages
  script/run_doxygen.sh
Labels: Type:Bug, Type:Documentation
