Repository alpaka-group/alpaka, pull requests merged in 2020-11, with the labels that each got.

#1190 Add comments to math function traits that explain valid argument range
  include/alpaka/math/acos/Traits.hpp
  include/alpaka/math/asin/Traits.hpp
  include/alpaka/math/log/Traits.hpp
  include/alpaka/math/pow/Traits.hpp
  include/alpaka/math/rsqrt/Traits.hpp
  include/alpaka/math/sqrt/Traits.hpp
Labels: Type:Documentation, Type:Enhancement

#1191 provide docker_retry
  script/docker_ci.sh
  script/docker_retry.sh
Labels: Type:Testing

#1187 Change block memory size back to be stored as 32 bit
  include/alpaka/block/shared/dyn/BlockSharedMemDynMember.hpp
  include/alpaka/block/shared/st/BlockSharedMemStMember.hpp
Labels: Type:Enhancement

#1192 fix travis_retry
  script/travis_retry.sh
Labels: Type:Bug

#1193 Pass native pointers to kernel instead of buffer objects
  test/unit/math/src/math.cpp
Labels: Type:Bug, Type:Testing

#1188 HIP: remove copy device2device workaround
  .github/workflows/ci.yml
  cmake/alpakaCommon.cmake
  docs/source/advanced/cmake.rst
  include/alpaka/mem/buf/uniformCudaHip/Copy.hpp
  script/run_generate.sh
Labels: Type:Bug, Type:Refactoring

#1189 remove CMake HIP module shipped with alpaka
  CMakeLists.txt
  cmake/alpakaConfig.cmake.in
  cmake/modules/FindHIP.cmake
  cmake/modules/FindHIP/run_hipcc.cmake
  cmake/modules/FindHIP/run_make2cmake.cmake
  cmake/modules/FindROCR.cmake
  cmake/modules/FindROCT.cmake
  docs/source/advanced/cmake.rst
  script/run.sh
Labels: Type:Refactoring, Type:Testing

#1196 fix bug in `isPinned()` and `pin()`
  include/alpaka/mem/buf/BufCpu.hpp
Labels: Type:Bug

#1195 update changelog
  CHANGELOG.md
Labels: Type:Documentation

#1198 fix documentation
  docs/source/basic/cheatsheet.rst
  docs/source/basic/library.rst
  docs/source/dev/backends.rst
Labels: Type:Bug, Type:Documentation

#1199 fix documentation `Execution Control`
  docs/source/dev/backends.rst
Labels: Type:Bug, Type:Documentation

#1200 fix CI: use `travis_retry` for `git clone`
  script/install_boost.sh
  script/run_doxygen.sh
Labels: Type:Bug, Type:Testing

#1206 CI: update used Xcode versions
  .github/workflows/ci.yml
  README.md
  script/install.sh
  test/common/devCompileOptions.cmake
Labels: OS:macOS, Type:Bug, Type:Testing

#1209 README.md: Add OpenACC, OpenMP 5.0 GPU
  README.md
Labels: Type:Documentation

#1204 [clang-format] Add .clang-format file
  .clang-format
  docs/source/dev/style.rst
Labels: Type:Documentation

#1212 Add CONTRIBUTING.md with formatting instructions
  CONTRIBUTING.md
Labels: Type:Documentation

#1214 TestAccs: Fix OMP5/OACC GCC<11 checks
  test/common/include/alpaka/test/acc/TestAccs.hpp
Labels: Type:Bug

#1215 Update to Catch 2.13.3
  thirdParty/catch2/include/catch2/catch.hpp
Labels: Type:Testing

#1197 rename shared memory functions
  CHANGELOG.md
  docs/source/basic/cheatsheet.rst
  docs/source/dev/backends.rst
  example/reduce/src/kernel.hpp
  include/alpaka/acc/AccOacc.hpp
  include/alpaka/block/shared/dyn/BlockSharedMemDynAlignedAlloc.hpp
  include/alpaka/block/shared/dyn/BlockSharedMemDynMember.hpp
  include/alpaka/block/shared/dyn/BlockSharedMemDynUniformCudaHipBuiltIn.hpp
  include/alpaka/block/shared/dyn/Traits.hpp
  include/alpaka/block/shared/st/BlockSharedMemStMasterSync.hpp
  include/alpaka/block/shared/st/BlockSharedMemStMember.hpp
  include/alpaka/block/shared/st/BlockSharedMemStNoSync.hpp
  include/alpaka/block/shared/st/BlockSharedMemStOmp5.hpp
  include/alpaka/block/shared/st/BlockSharedMemStUniformCudaHipBuiltIn.hpp
  include/alpaka/block/shared/st/Traits.hpp
  include/alpaka/ctx/block/CtxBlockOacc.hpp
  include/alpaka/kernel/TaskKernelCpuFibers.hpp
  include/alpaka/kernel/TaskKernelCpuOmp2Blocks.hpp
  include/alpaka/kernel/TaskKernelCpuOmp2Threads.hpp
  include/alpaka/kernel/TaskKernelCpuSerial.hpp
  include/alpaka/kernel/TaskKernelCpuTbbBlocks.hpp
  include/alpaka/kernel/TaskKernelCpuThreads.hpp
  include/alpaka/kernel/TaskKernelOacc.hpp
  include/alpaka/kernel/TaskKernelOmp5.hpp
  test/integ/matMul/src/matMul.cpp
  test/integ/sharedMem/src/sharedMem.cpp
  test/unit/atomic/src/AtomicTest.cpp
  test/unit/block/shared/src/BlockSharedMemDyn.cpp
  test/unit/block/shared/src/BlockSharedMemSt.cpp
  test/unit/block/sync/src/BlockSync.cpp
Labels: Type:Refactoring

#781 Improve clang-format support
  CMakeLists.txt
  README.md
  thirdParty/.clang-format
Labels: Type:Refactoring

#1217 Update tested CMake versions
  .github/workflows/ci.yml
Labels: Type:Testing

#1218 clang-format tinymt32.h
  include/alpaka/rand/TinyMT/tinymt32.h
Labels: Type:Documentation

#1219 Enable OpenMP backends for more Visual Studio builds
  .github/workflows/ci.yml
Labels: Backend:CUDA, Backend:OpenMP, OS:Windows, Type:Testing

#1222 update documentation for clang-format
  CONTRIBUTING.md
  docs/source/dev/style.rst
Labels: Type:Documentation
