Repository alpaka-group/alpaka, pull requests merged in 2021-06, with the labels that each got.

#1327 Add missing <limits> header and fix integer namespace
  include/alpaka/block/shared/st/detail/BlockSharedMemStMemberImpl.hpp
Labels: Backend:Boost.Fiber, Backend:OpenACC, Backend:OpenMP, Backend:TBB, Backend:std::thread, Type:Bug

#1317 Changelog for 0.7.0
  CHANGELOG.md
Labels: Type:Documentation

#1320 fix HIP compiler options not recognized (backport to 0.6.1)
  cmake/alpakaCommon.cmake
Labels: Backend:HIP, Type:Bug

#1324 fix HIP compiler options not recognized
  cmake/alpakaCommon.cmake
Labels: Backend:HIP, Type:Bug

#1339 CI: fix warp test
  test/unit/warp/src/Activemask.cpp
  test/unit/warp/src/Ballot.cpp
Labels: Type:Bug, Type:Testing

#1341 Fix outdated comments in the OpenMP schedule example
  example/openMPSchedule/src/openMPSchedule.cpp
Labels: Type:Documentation, Type:Example

#1342 TaskKernelOacc: copyin(all used local vars)
  include/alpaka/kernel/TaskKernelOacc.hpp
Labels: Backend:OpenACC, Type:Bug

#1350 update release date
  CHANGELOG.md
Labels: Type:Documentation
