Repository alpaka-group/alpaka, pull requests merged in 2021-04, with the labels that each got.

#1283 Add support for CMake 3.20
  .github/workflows/ci.yml
  script/install_cmake.sh
  script/run_generate.sh
Labels: Type:Testing

#1291 Fix CtxBlockOacc: SyncBlockThreads
  include/alpaka/ctx/block/CtxBlockOacc.hpp
Labels: Type:Bug

#1302 CI: disable GCC 10.3 + NVCC tests
  .github/workflows/ci.yml
  README.md
Labels: Type:Bug, Type:Testing

#1300 Drop support for clang < 9 as CUDA compiler
  .github/workflows/ci.yml
  README.md
  cmake/alpakaCommon.cmake
Labels: Type:Refactoring

#1303 CtxBlockOacc: Fix assert in DeclareSharedVar
  include/alpaka/ctx/block/CtxBlockOacc.hpp
Labels: Backend:OpenACC, Type:Bug

#1294 CMake CUDA: dev compile options not propagated
  test/common/devCompileOptions.cmake
Labels: Backend:CUDA, Type:Bug, Type:Testing

#1306 Add Front and Contains type list meta functions
  include/alpaka/alpaka.hpp
  include/alpaka/meta/TypeListOps.hpp
  test/unit/meta/src/TypeListOpsTest.cpp
Labels: Type:Enhancement

#1307 example: fix warning (NVCC+OpenMP)
  example/openMPSchedule/src/openMPSchedule.cpp
Labels: Backend:CUDA, Backend:OpenMP, Type:Warning
