Repository alpaka-group/alpaka, pull requests merged in 2021-09, with the labels that each got.

#1385 Purge legacy software support
  .github/workflows/ci.yml
  README.md
  script/install_clang.sh
Labels: Type:Enhancement, Type:Testing

#1401 fix `alpaka_compiler_option`
  cmake/alpakaCommon.cmake
Labels: Type:Bug, Type:Install

#1405 fix warning in thread fence test
  test/unit/mem/fence/src/FenceTest.cpp
Labels: Type:Warning, Type:Testing

#1406 fix Clang-CUDA math tests
  test/unit/math/src/math.cpp
Labels: Type:Testing

#1375 Add runtime tests on Gitlab CI
  .gitlab-ci.yml
  docs/source/dev/ci.rst
  docs/source/images/arch_gitlab_mirror.svg
  docs/source/index.rst
  script/gitlabci/fake_sudo.sh
  script/gitlabci/job_base.yml
  script/run_build.sh
  script/run_tests.sh
Labels: Type:Testing

#1413 document kernel lambdas
  docs/source/basic/library.rst
  example/helloWorldLambda/src/helloWorldLambda.cpp
Labels: Type:Enhancement, Type:Documentation
