Repository alpaka-group/alpaka, pull requests merged in 2021-03, with the labels that each got.

#1258 fix CPU static shared memory implementation
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/block/shared/dyn/BlockSharedMemDynAlignedAlloc.hpp
  include/alpaka/block/shared/st/BlockSharedMemStMasterSync.hpp
  include/alpaka/block/shared/st/BlockSharedMemStMember.hpp
  include/alpaka/block/shared/st/BlockSharedMemStMemberMasterSync.hpp
  include/alpaka/block/shared/st/BlockSharedMemStNoSync.hpp
  include/alpaka/block/shared/st/BlockSharedMemStOmp5.hpp
  include/alpaka/block/shared/st/detail/BlockSharedMemStMemberImpl.hpp
  include/alpaka/ctx/block/CtxBlockOacc.hpp
  test/unit/block/shared/src/BlockSharedMemSt.cpp
Labels: Backend:Boost.Fiber, Backend:OpenACC, Backend:OpenMP, Backend:TBB, Backend:std::thread, Type:Bug

#1265 document return value of `empty()` and `isComplete()`
  include/alpaka/event/Traits.hpp
  include/alpaka/queue/Traits.hpp
Labels: Type:Documentation

#1262 set version to 0.6.1
  docs/source/conf.py
  include/alpaka/version.hpp
Labels: Type:Documentation

#1266 fix queue test
  test/unit/queue/src/QueueTest.cpp
Labels: Backend:CUDA, Backend:HIP, Type:Bug

#1270 CI: fix deadlock when using ubuntu 20.04 container
  script/install.sh
Labels: Type:Bug, Type:Testing

#1280 Fix BlockSharedMemStMemberImpl::getVarPtr for last var
  include/alpaka/block/shared/st/detail/BlockSharedMemStMemberImpl.hpp
  test/unit/block/shared/src/BlockSharedMemSt.cpp
Labels: Type:Bug

#1282 fix static shared memory alignment
  include/alpaka/block/shared/st/detail/BlockSharedMemStMemberImpl.hpp
Labels: Backend:Boost.Fiber, Backend:OpenACC, Backend:OpenMP, Backend:TBB, Backend:std::thread, Type:Bug
