Repository alpaka-group/alpaka, pull requests merged in 2021-12, with the labels that each got.

#1499 Delete meta::Void, replace with std::void_t
  include/alpaka/alpaka.hpp
  include/alpaka/kernel/TaskKernelCpuOmp2Blocks.hpp
  include/alpaka/kernel/Traits.hpp
  include/alpaka/mem/view/ViewAccessor.hpp
  include/alpaka/meta/Void.hpp
  test/unit/meta/src/VoidTest.cpp
Labels: Type:Enhancement, Type:Refactoring

#1506 Drop support for clang-6/7 with nvcc
  .github/workflows/ci.yml
  README.md
Labels: Type:Enhancement, Type:Testing, Backend:CUDA, Type:Documentation

#1503 CI: HIP fix outdated apt keys
  script/gitlabci/job_base.yml
Labels: Type:Bug, Type:Testing, Backend:HIP

#1504 CI: use ubuntu container and not nvidia container for CUDA
  script/before_install.sh
  script/gitlabci/job_base.yml
  script/install_cuda.sh
Labels: Type:Testing, Backend:CUDA

#1486 Add nvcc 11.5 to CI
  .github/workflows/ci.yml
  README.md
  script/install_cuda.sh
Labels: Type:Testing, Backend:CUDA

#1508 Use all cores for building on GitHub runners
  .github/workflows/ci.yml
  script/docker_ci.sh
Labels: Type:Enhancement, Type:Testing

#1507 Fix installation
  CMakeLists.txt
Labels: Type:Install

#1502 Use C++17 mandatory copy elision
  include/alpaka/mem/fence/MemFenceCpu.hpp
Labels: Type:Enhancement, Type:Refactoring, Backend:TBB, Backend:Boost.Fiber, Backend:std::thread, Backend:Serial

#1510 CI: fix CUDA 9.2 download path
  script/install_cuda.sh
Labels: Type:Bug, Type:Testing, Backend:CUDA

#1450 Isolate parallel region for nested parallelism with tbb backend
  include/alpaka/kernel/TaskKernelCpuTbbBlocks.hpp
Labels: Type:Enhancement, Type:Refactoring, Backend:TBB

#1515 Avoid setting the CUDA/HIP device when not necessary
  include/alpaka/event/EventUniformCudaHipRt.hpp
  include/alpaka/mem/buf/BufUniformCudaHipRt.hpp
  include/alpaka/mem/buf/uniformCudaHip/Copy.hpp
  include/alpaka/mem/buf/uniformCudaHip/Set.hpp
  include/alpaka/queue/cuda_hip/QueueUniformCudaHipRtBase.hpp
  include/alpaka/test/event/EventHostManualTrigger.hpp
Labels: Type:Refactoring, Backend:CUDA, Backend:HIP

#1516 Silence warnings on non-x86 CPUs
  include/alpaka/dev/cpu/SysInfo.hpp
Labels: Type:Bug, Type:Enhancement, Type:Warning, Type:Testing, Backend:OpenMP, Backend:TBB, Backend:Boost.Fiber, Backend:std::thread, Type:Machine/System, Backend:Serial

#1511 Simplify CPU kernel launch
  include/alpaka/kernel/TaskKernelCpuOmp2Blocks.hpp
  include/alpaka/kernel/TaskKernelCpuOmp2Threads.hpp
  include/alpaka/kernel/TaskKernelCpuSerial.hpp
  include/alpaka/kernel/TaskKernelCpuTbbBlocks.hpp
Labels: Type:Enhancement, Type:Refactoring, Backend:OpenMP, Backend:TBB, Backend:Serial

#1514 Extend a queue's lifetime until async memory operations are complete
  include/alpaka/mem/buf/BufCpu.hpp
  test/unit/mem/buf/src/BufTest.cpp
Labels: Type:Bug, Type:Enhancement, Type:Refactoring, Backend:TBB, Backend:Boost.Fiber, Backend:std::thread, Backend:Serial

#1501 Remove functions in meta/Metafunctions.hpp, replace with std:: counterparts
  include/alpaka/alpaka.hpp
  include/alpaka/core/Cuda.hpp
  include/alpaka/core/Hip.hpp
  include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp
  include/alpaka/meta/Metafunctions.hpp
  include/alpaka/meta/Unique.hpp
  test/unit/meta/src/MetafunctionsTest.cpp
Labels: Type:Enhancement, Type:Refactoring

#1518 Add changelog for 0.8
  CHANGELOG.md
Labels: Type:Enhancement, Type:Documentation

#1524 Remove MySQL disabling
  CHANGELOG.md
  script/print_env.sh
Labels: Type:Bug, Type:Testing

#1522 [Backport] Changelog for 0.8.0, remove MySQL disabling
  CHANGELOG.md
  script/print_env.sh
Labels: Type:Enhancement, Type:Documentation

#1530 HIP CI node changes
  script/gitlabci/job_base.yml
  script/install_hip.sh
Labels: Type:Testing, Backend:HIP

#1527 fix Philox RNG
  example/randomCells2D/src/randomCells2D.cpp
  example/randomStrategies/src/randomStrategies.cpp
  include/alpaka/rand/Philox/PhiloxSingle.hpp
Labels: Type:Bug

#1539 Add cmake option ALPAKA_CHECK_HEADERS
  CMakeLists.txt
  script/run_generate.sh
  test/analysis/headerCheck/CMakeLists.txt
Labels: Type:Refactoring, Type:Testing, Type:Install

#1541 CI: speedup boost code download
  script/install_boost.sh
Labels: Type:Testing

#1526 Refactor matMul and check pitch
  test/integ/matMul/src/matMul.cpp
Labels: Type:Refactoring, Type:Testing

#1533 Added OpenMP configuration on MacOS
  .github/workflows/ci.yml
  script/before_install.sh
  script/docker_ci.sh
  script/install.sh
  script/install_omp.sh
Labels: Type:Enhancement, Type:Testing, Backend:OpenMP, OS:macOS

#1542 gitlab CI refactoring
  .github/workflows/ci.yml
  .gitlab-ci.yml
  script/docker_ci.sh
  script/gitlabci/job_base.yml
  script/gitlabci/job_cuda10.0.yml
  script/gitlabci/job_cuda10.1.yml
  script/gitlabci/job_cuda10.2.yml
  script/gitlabci/job_cuda11.0.yml
  script/gitlabci/job_cuda11.1.yml
  script/gitlabci/job_cuda11.2.yml
  script/gitlabci/job_cuda11.3.yml
  script/gitlabci/job_cuda11.4.yml
  script/gitlabci/job_cuda11.5.yml
  script/gitlabci/job_cuda9.2.yml
  script/gitlabci/job_hip4.2.yml
  script/run.sh
Labels: Type:Refactoring, Type:Testing

#1521 Upgrade to at least boost-1.74.0
  .github/workflows/ci.yml
  cmake/alpakaCommon.cmake
  script/before_install.sh
  script/gitlabci/job_cuda10.0.yml
  script/gitlabci/job_cuda10.1.yml
  script/gitlabci/job_cuda10.2.yml
  script/gitlabci/job_cuda11.0.yml
  script/gitlabci/job_cuda11.1.yml
  script/gitlabci/job_cuda11.2.yml
  script/gitlabci/job_cuda11.3.yml
  script/gitlabci/job_cuda11.4.yml
  script/gitlabci/job_cuda11.5.yml
  script/gitlabci/job_cuda9.2.yml
  script/gitlabci/job_hip4.2.yml
  script/install_boost.sh
Labels: Type:Enhancement, Backend:Boost.Fiber

#1543 Format tables in README.md
  README.md
Labels: Type:Documentation

#1488 Test installation in CI
  .github/workflows/ci.yml
  script/docker_ci.sh
  script/run.sh
  script/run_generate.sh
  script/run_install.sh
Labels: Type:Testing, Type:Install
