Repository alpaka-group/alpaka, pull requests merged in 2021-11, with the labels that each got.

#1319 Philox random number generator
  example/CMakeLists.txt
  example/randomCells2D/CMakeLists.txt
  example/randomCells2D/src/randomCells2D.cpp
  example/randomStrategies/CMakeLists.txt
  example/randomStrategies/src/randomStrategies.cpp
  include/alpaka/alpaka.hpp
  include/alpaka/meta/IsArrayOrVector.hpp
  include/alpaka/rand/Philox/MultiplyAndSplit64to32.hpp
  include/alpaka/rand/Philox/PhiloxBaseCommon.hpp
  include/alpaka/rand/Philox/PhiloxBaseCudaArray.hpp
  include/alpaka/rand/Philox/PhiloxBaseStdArray.hpp
  include/alpaka/rand/Philox/PhiloxBaseTraits.hpp
  include/alpaka/rand/Philox/PhiloxConstants.hpp
  include/alpaka/rand/Philox/PhiloxSingle.hpp
  include/alpaka/rand/Philox/PhiloxVector.hpp
  include/alpaka/rand/RandPhilox.hpp
  test/unit/meta/src/IsArrayOrVectorTest.cpp
Labels: Type:Enhancement

#1446 math: Add isnan, isinf, isfinite
  include/alpaka/math/MathStdLib.hpp
  include/alpaka/math/MathUniformCudaHipBuiltIn.hpp
  include/alpaka/math/isfinite/IsfiniteStdLib.hpp
  include/alpaka/math/isfinite/IsfiniteUniformCudaHipBuiltIn.hpp
  include/alpaka/math/isfinite/Traits.hpp
  include/alpaka/math/isinf/IsinfStdLib.hpp
  include/alpaka/math/isinf/IsinfUniformCudaHipBuiltIn.hpp
  include/alpaka/math/isinf/Traits.hpp
  include/alpaka/math/isnan/IsnanStdLib.hpp
  include/alpaka/math/isnan/IsnanUniformCudaHipBuiltIn.hpp
  include/alpaka/math/isnan/Traits.hpp
  test/unit/math/src/DataGen.hpp
  test/unit/math/src/Defines.hpp
  test/unit/math/src/Functor.hpp
Labels: Type:Enhancement

#1451 handle alpaka includes as SYSTEM includes
  cmake/alpakaCommon.cmake
Labels: Type:Refactoring

#1433 Add Accessor for views and buffers (only feature)
  docs/source/basic/cheatsheet.rst
  docs/source/basic/library.rst
  include/alpaka/alpaka.hpp
  include/alpaka/mem/view/Accessor.hpp
  include/alpaka/mem/view/ViewAccessor.hpp
  test/unit/mem/view/src/Accessor.cpp
Labels: Type:Enhancement

#1459 Fix a typo and add a linebreak in accessor docs
  docs/source/basic/library.rst
Labels: Type:Enhancement, Type:Documentation

#1461 Upgrade to Catch2 v2.13.7
  thirdParty/catch2/include/catch2/catch.hpp
Labels: Type:Testing

#1463 Support non-cached cmake variable ALPAKA_CXX_STANDARD in external projects
  cmake/alpakaCommon.cmake
Labels: Type:Install

#1464 Ignore VS and more build folders
  .gitignore
Labels: OS:Windows

#1465 Update version number to 0.8.0-rc1
  docs/source/conf.py
Labels: Type:Enhancement, Type:Documentation

#1468 Update version number to 0.9.0-develop
  docs/source/conf.py
  include/alpaka/version.hpp
Labels: Type:Enhancement, Type:Install, Type:Documentation

#1469 fix cheat-sheet RNG section
  docs/source/basic/cheatsheet.rst
Labels: Type:Bug, Type:Documentation

#1470 Small example and test fixes
  example/CMakeLists.txt
  example/bufferCopy/CMakeLists.txt
  example/heatEquation/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/kernelSpecialization/CMakeLists.txt
  example/monteCarloIntegration/CMakeLists.txt
  example/openMPSchedule/CMakeLists.txt
  example/randomCells2D/CMakeLists.txt
  example/randomStrategies/CMakeLists.txt
  example/reduce/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  test/analysis/CMakeLists.txt
  test/catch_main/CMakeLists.txt
  test/integ/CMakeLists.txt
Labels: Type:Bug, Type:Enhancement, Type:Testing, Type:Example, Type:Install

#1473 [Backport to 0.8] Enable language CXX and update Catch2 message
  example/CMakeLists.txt
  example/bufferCopy/CMakeLists.txt
  example/heatEquation/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/kernelSpecialization/CMakeLists.txt
  example/monteCarloIntegration/CMakeLists.txt
  example/openMPSchedule/CMakeLists.txt
  example/randomCells2D/CMakeLists.txt
  example/randomStrategies/CMakeLists.txt
  example/reduce/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  test/analysis/CMakeLists.txt
  test/catch_main/CMakeLists.txt
  test/integ/CMakeLists.txt
Labels: Type:Enhancement, Type:Testing, Type:Install

#1466 Switch to C++17
  .github/workflows/ci.yml
  .gitlab-ci.yml
  .zenodo.json
  CMakeLists.txt
  README.md
  cmake/alpakaCommon.cmake
  docs/source/basic/library.rst
  docs/source/conf.py
  include/alpaka/core/UniformCudaHip.hpp
  include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp
  include/alpaka/pltf/PltfUniformCudaHipRt.hpp
  script/before_install.sh
  script/docker_ci.sh
  script/gitlabci/job_cuda.yml
  script/gitlabci/job_cuda11.4.yml
  script/install_boost.sh
  script/install_cuda.sh
  script/run_generate.sh
  test/catch_main/CMakeLists.txt
Labels: Type:Enhancement, Type:Testing, Type:Install

#1431 Atomic tests enabled and fix for float/double
  test/unit/atomic/src/AtomicTest.cpp
Labels: Type:Testing
