Repository alpaka-group/alpaka, pull requests merged in 2021-08, with the labels that each got.

#1356 Prepare for 0.7.0 release
  CHANGELOG.md
  docs/source/conf.py
Labels: Type:Documentation

#1363 Fix bug, if alpaka_add_library() and Clang as CUDA compiler is used together
  cmake/addLibrary.cmake
Labels: Type:Bug, Type:Install

#1364 fix `alpaka_add_(executable|library)`
  cmake/addExecutable.cmake
  cmake/addLibrary.cmake
Labels: Type:Bug

#1367 Port PR #1363 (bug Clang-CUDA alpaka_add_library) in 0.7.0-rc1 branch
  cmake/addLibrary.cmake
Labels: Type:Bug, Type:Install

#1368 Update author list [0.7.0]
  README.md
Labels: Type:Documentation

#1370 Update Zenodo file [0.7.0]
  .zenodo.json
Labels: Type:Documentation

#1372 ROCm container update outdated keys
  script/install_hip.sh
Labels: Type:Bug, Type:Testing

#1373 CI: update ROCm apt package keys
  script/install_hip.sh
Labels: Type:Bug, Type:Testing

#1369 Update author list [develop]
  README.md
Labels: Type:Documentation

#1374 Merge 0.6.1 and 0.7.0 changelogs into develop
  CHANGELOG.md
Labels: Type:Documentation

#1371 Update Zenodo file [develop]
  .zenodo.json
Labels: Type:Documentation

#1376 fix `alpaka_add_(executable|library)`
  cmake/addExecutable.cmake
  cmake/addLibrary.cmake
Labels: Type:Bug

#1366 Port PR #1363 (bug Clang-CUDA alpaka_add_library) in develop branch
  cmake/addLibrary.cmake
Labels: Type:Bug, Type:Install

#1382 fix ROCm install
  script/install_hip.sh
Labels: Type:Bug

#1380 CI: test CUDA 11.4
  .github/workflows/ci.yml
  README.md
  script/install_cuda.sh
Labels: Type:Testing, Type:Documentation

#1358 Add AtomicOaccExtended
  include/alpaka/acc/AccOacc.hpp
  include/alpaka/atomic/AtomicOaccBuiltIn.hpp
  include/alpaka/atomic/AtomicOaccExtended.hpp
  include/alpaka/ctx/block/CtxBlockOacc.hpp
  include/alpaka/dev/DevOacc.hpp
  include/alpaka/kernel/TaskKernelOacc.hpp
Labels: Type:Refactoring, Backend:OpenACC

#1383 Add gcc 11 support
  .github/workflows/ci.yml
  README.md
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuThreads.hpp
Labels: Type:Bug, Type:Enhancement, Backend:OpenMP, Backend:Boost.Fiber, Backend:std::thread

#1395 CI: fix overflow in `AccDevPropsTest`
  test/unit/acc/src/AccDevPropsTest.cpp
Labels: Type:Bug, Backend:CUDA, Backend:OpenMP, Backend:TBB, Backend:Boost.Fiber, Backend:std::thread, Backend:OpenACC, Backend:SYCL, Backend:HIP, Priority: 1

#1399 Ci: fix P2P test
  test/unit/mem/p2p/src/P2P.cpp
Labels: Type:Bug, Type:Testing

#1379 Add memory fences to kernel language
  .github/workflows/ci.yml
  .gitignore
  README.md
  cmake/alpakaCommon.cmake
  docs/source/basic/cheatsheet.rst
  docs/source/basic/library.rst
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
  include/alpaka/acc/AccOacc.hpp
  include/alpaka/acc/AccOmp5.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/core/Common.hpp
  include/alpaka/mem/fence/MemFenceCpu.hpp
  include/alpaka/mem/fence/MemFenceOacc.hpp
  include/alpaka/mem/fence/MemFenceOmp2Blocks.hpp
  include/alpaka/mem/fence/MemFenceOmp2Threads.hpp
  include/alpaka/mem/fence/MemFenceOmp5.hpp
  include/alpaka/mem/fence/MemFenceUniformCudaHipBuiltIn.hpp
  include/alpaka/mem/fence/Traits.hpp
  test/unit/CMakeLists.txt
  test/unit/mem/fence/CMakeLists.txt
  test/unit/mem/fence/src/FenceTest.cpp
Labels: Type:Enhancement, Backend:CUDA, Backend:OpenMP, Backend:TBB, Backend:Boost.Fiber, Backend:OpenACC, Backend:HIP

#1400 HIP: fix peer to peer memcopy
  include/alpaka/mem/buf/uniformCudaHip/Copy.hpp
Labels: Type:Bug, Backend:HIP

#1404 fix CUDA 11.3+ compile
  example/reduce/src/iterator.hpp
  example/reduce/src/reduce.cpp
  example/vectorAdd/src/vectorAdd.cpp
  test/integ/separableCompilation/src/main.cpp
Labels: Type:Bug, Backend:CUDA
