Repository alpaka-group/alpaka, pull requests merged in 2021-05, with the labels that each got.

#1146 Use CMake first-class CUDA support
  .github/workflows/ci.yml
  CMakeLists.txt
  README.md
  cmake/addExecutable.cmake
  cmake/addLibrary.cmake
  cmake/alpakaCommon.cmake
  docs/source/advanced/cmake.rst
  docs/source/basic/intro.rst
  example/CMakeLists.txt
  example/bufferCopy/CMakeLists.txt
  example/heatEquation/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/monteCarloIntegration/CMakeLists.txt
  example/reduce/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  script/before_install.sh
  script/docker_ci.sh
  script/install_cuda.sh
  script/prepare_sanitizers.sh
  script/run.sh
  script/run_generate.sh
  test/CMakeLists.txt
  test/analysis/CMakeLists.txt
  test/catch_main/CMakeLists.txt
  test/common/CMakeLists.txt
  test/common/devCompileOptions.cmake
  test/integ/CMakeLists.txt
  test/integ/separableCompilation/CMakeLists.txt
  test/unit/CMakeLists.txt
  test/unit/math/CMakeLists.txt
Labels: Backend:CUDA, Priority: 1, Type:Refactoring

#1310 Add support for clang 11
  .github/workflows/ci.yml
  README.md
  cmake/alpakaCommon.cmake
Labels: Type:Testing

#1313 fix OpenMP schedule support
  include/alpaka/kernel/TaskKernelCpuOmp2Blocks.hpp
Labels: Backend:OpenMP, Type:Bug

#1315 Update version number to 0.7.0-rc1
  docs/source/conf.py
Labels: Type:Documentation

#1314 update version number to 0.8.0-develop
  docs/source/conf.py
  include/alpaka/version.hpp
Labels: Type:Documentation

#1316 fix OpenMP schedule support
  include/alpaka/kernel/TaskKernelCpuOmp2Blocks.hpp
Labels: Type:Bug

#1329 Prefer TBBConfig.cmake over FindTBB.cmake
  cmake/alpakaCommon.cmake
Labels: Backend:TBB, Type:Install
