Repository alpaka-group/alpaka, pull requests merged in 2022-04, with the labels that each got.

#1664 Set BOOST_LANG_HIP to the HIP version number
  include/alpaka/core/BoostPredef.hpp
Labels: Type:Enhancement, Backend:HIP

#1675 Removed deprecated cudaStreamAddCallback
  docs/source/dev/backends.rst
  include/alpaka/queue/cuda_hip/QueueUniformCudaHipRt.hpp
Labels: Type:Enhancement, Type:Refactoring, Backend:CUDA, Backend:HIP

#1684 Update version number to 1.0.0-develop
  docs/source/conf.py
  include/alpaka/version.hpp
Labels: Type:Documentation

#1686 Add ALPAKA_DEFAULT_HOST_MEMORY_ALIGNMENT macro
  include/alpaka/mem/buf/BufCpu.hpp
Labels: Backend:OpenMP, Backend:TBB, Backend:Boost.Fiber, Backend:std::thread, Backend:Serial

#1696 Updated documentation for 0.9.0
  docs/source/dev/backends.rst
Labels: Type:Enhancement, Type:Documentation

#1697 Fix functions attributes documentation of the CUDA backend
  docs/source/dev/backends.rst
Labels: Type:Enhancement, Backend:CUDA, Type:Documentation, Backend:HIP

#1695 Add documentation about setting the stdlib with the Clang compiler
  docs/source/advanced/compiler.rst
  docs/source/index.rst
Labels: Type:Enhancement, Type:Documentation

#1699 document constexpr function behavior in CUDA kernel
  docs/source/dev/backends.rst
Labels: Type:Documentation

#1689 Use aligned new/delete instead of OS APIs
  include/alpaka/core/AlignedAlloc.hpp
  include/alpaka/mem/alloc/AllocCpuAligned.hpp
  include/alpaka/mem/buf/oacc/Copy.hpp
Labels: Type:Refactoring
