Repository alpaka-group/alpaka, pull requests merged in 2022-05, with the labels that each got.

#1703 fix CUDA repo keys
  script/install_cuda.sh
Labels: Type:Bug, Type:Testing

#1702 Drop support for icpc
  .github/workflows/ci.yml
  cmake/alpakaCommon.cmake
  include/alpaka/core/Align.hpp
  include/alpaka/core/AlignedAlloc.hpp
  include/alpaka/core/BoostPredef.hpp
  include/alpaka/core/Debug.hpp
  include/alpaka/core/Decay.hpp
  include/alpaka/core/Unreachable.hpp
  include/alpaka/core/Unroll.hpp
  include/alpaka/core/Vectorize.hpp
  include/alpaka/intrinsic/IntrinsicCpu.hpp
Labels: Type:Testing

#1704 Add braces around aggregate initializer
  include/alpaka/core/UniformCudaHip.hpp
Labels: Backend:CUDA, Backend:HIP

#1700 Add icpx to CI
  .github/workflows/ci.yml
  README.md
  include/alpaka/block/shared/st/BlockSharedMemStOmp5BuiltIn.hpp
  script/install.sh
  script/install_oneapi.sh
  test/common/devCompileOptions.cmake
  test/unit/time/src/ClockTest.cpp
Labels: Type:Testing

#1711 Fix wrong latter case in getWorkDiv() example in cheatsheet
  docs/source/basic/cheatsheet.rst
Labels: Type:Documentation

#1717 Cancel running workflows when updating PRs
  .github/workflows/ci.yml
Labels: Type:Testing

#1710 Introduce `alpaka::math::constants`
  cmake/alpakaCommon.cmake
  cmake/tests/MathConstants.cpp
  include/alpaka/math/Traits.hpp
  include/alpaka/rand/RandDefault.hpp
Labels: Type:Enhancement

#1716 Refactor and fix CPU intrinsics
  include/alpaka/intrinsic/IntrinsicCpu.hpp
  include/alpaka/intrinsic/IntrinsicFallback.hpp
Labels: Type:Bug, Type:Refactoring, Backend:OpenMP, Backend:TBB, Backend:Boost.Fiber, Backend:std::thread, Backend:Serial

#1721 Small fixes required for gcc-12
  cmake/alpakaCommon.cmake
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/mem/buf/BufOmp5.hpp
  test/unit/math/src/mathComplexDouble.cpp
  test/unit/math/src/mathComplexFloat.cpp
Labels: Type:Bug, Type:Refactoring

#1719 Add CallbackThread to QueueUniformCudaHipRt
  include/alpaka/core/CallbackThread.hpp
  include/alpaka/queue/cuda_hip/QueueUniformCudaHipRt.hpp
Labels: Type:Enhancement, Backend:CUDA, Backend:HIP

#1725 fix host memory alloc and pinning on OpenPower systems
  include/alpaka/dev/cpu/SysInfo.hpp
  include/alpaka/mem/alloc/AllocCpuAligned.hpp
Labels: Type:Bug
