Repository alpaka-group/alpaka, pull requests merged in 2022-02, with the labels that each got.

#1584 Run clang-tidy modernize checks
  example/bufferCopy/src/bufferCopy.cpp
  example/heatEquation/src/heatEquation.cpp
  example/openMPSchedule/src/openMPSchedule.cpp
  example/reduce/src/alpakaConfig.hpp
  example/reduce/src/iterator.hpp
  example/reduce/src/kernel.hpp
  example/reduce/src/reduce.cpp
  include/alpaka/atomic/AtomicStdLibLock.hpp
  include/alpaka/block/shared/dyn/BlockSharedMemDynMember.hpp
  include/alpaka/block/shared/dyn/BlockSharedMemDynOmp5BuiltIn.hpp
  include/alpaka/block/shared/st/BlockSharedMemStMemberMasterSync.hpp
  include/alpaka/block/shared/st/detail/BlockSharedMemStMemberImpl.hpp
  include/alpaka/core/AlignedAlloc.hpp
  include/alpaka/core/ConcurrentExecPool.hpp
  include/alpaka/core/Debug.hpp
  include/alpaka/dev/DevCpu.hpp
  include/alpaka/dev/DevOmp5.hpp
  include/alpaka/event/EventGenericThreads.hpp
  include/alpaka/kernel/TaskKernelCpuSerial.hpp
  include/alpaka/math/FloatEqualExact.hpp
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/mem/buf/BufOmp5.hpp
  include/alpaka/mem/view/ViewAccessOps.hpp
  include/alpaka/mem/view/ViewAccessor.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
  include/alpaka/queue/QueueGenericThreadsBlocking.hpp
  include/alpaka/queue/QueueGenericThreadsNonBlocking.hpp
  include/alpaka/rand/Philox/MultiplyAndSplit64to32.hpp
  include/alpaka/rand/RandPhilox.hpp
  include/alpaka/rand/RandStdLib.hpp
  include/alpaka/rand/TinyMT/Engine.hpp
  include/alpaka/test/Array.hpp
  include/alpaka/test/KernelExecutionFixture.hpp
  include/alpaka/test/event/EventHostManualTrigger.hpp
  include/alpaka/test/mem/view/ViewTest.hpp
  include/alpaka/vec/Vec.hpp
  test/integ/hostOnlyAPI/src/hostOnlyAPI.cpp
  test/integ/mandelbrot/src/mandelbrot.cpp
  test/integ/matMul/src/matMul.cpp
  test/integ/sharedMem/src/sharedMem.cpp
  test/integ/zeroDimBuffer/src/zeroDimBuffer.cpp
  test/unit/atomic/src/AtomicTest.cpp
  test/unit/block/shared/src/BlockSharedMemDyn.cpp
  test/unit/block/sharedSharing/src/BlockSharedMemSharing.cpp
  test/unit/block/sync/src/BlockSync.cpp
  test/unit/kernel/src/KernelWithOmpSchedule.cpp
  test/unit/math/src/Buffer.hpp
  test/unit/math/src/Defines.hpp
  test/unit/math/src/sincos.cpp
  test/unit/mem/buf/src/BufTest.cpp
  test/unit/mem/fence/src/FenceTest.cpp
  test/unit/mem/p2p/src/P2P.cpp
  test/unit/mem/view/src/Accessor.cpp
  test/unit/mem/view/src/ViewPlainPtrTest.cpp
  test/unit/mem/view/src/ViewSubViewTest.cpp
Labels: Type:Refactoring

#1583 Add Visual Studio 17 2022 to CI tests
  .github/workflows/ci.yml
  script/install_boost.sh
  script/run.sh
  script/run_generate.sh
Labels: Type:Testing, OS:Windows

#1586 Update BoostPredef.hpp
  include/alpaka/core/BoostPredef.hpp
  include/alpaka/core/Utility.hpp
Labels: Type:Refactoring

#1549 Fix pitch access calculation in randomCells2D example.
  example/CMakeLists.txt
  example/randomCells2D/src/randomCells2D.cpp
Labels: Type:Bug

#1589 display all necessary information in GitLab CI job to reproduce the job locally
  script/gitlab_ci_run.sh
  script/gitlabci/job_base.yml
  script/gitlabci/print_env.sh
  script/run_tests.sh
Labels: Type:Bug, Type:Enhancement, Type:Testing, Backend:CUDA, Backend:HIP

#1592 Use more nested namespace specifiers
  include/alpaka/mem/view/Accessor.hpp
  include/alpaka/mem/view/ViewAccessOps.hpp
  include/alpaka/mem/view/ViewAccessor.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
Labels: Type:Refactoring

#1593 Remove namespace alpaka::extent
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
  include/alpaka/core/Cuda.hpp
  include/alpaka/core/Hip.hpp
  include/alpaka/extent/Traits.hpp
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/mem/buf/BufOacc.hpp
  include/alpaka/mem/buf/BufOmp5.hpp
  include/alpaka/mem/buf/BufUniformCudaHipRt.hpp
  include/alpaka/mem/buf/cpu/Copy.hpp
  include/alpaka/mem/buf/cpu/Set.hpp
  include/alpaka/mem/buf/oacc/Copy.hpp
  include/alpaka/mem/buf/oacc/Set.hpp
  include/alpaka/mem/buf/omp5/Copy.hpp
  include/alpaka/mem/buf/omp5/Set.hpp
  include/alpaka/mem/buf/uniformCudaHip/Copy.hpp
  include/alpaka/mem/buf/uniformCudaHip/Set.hpp
  include/alpaka/mem/view/Traits.hpp
  include/alpaka/mem/view/ViewAccessOps.hpp
  include/alpaka/mem/view/ViewAccessor.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
  include/alpaka/mem/view/ViewStdArray.hpp
  include/alpaka/mem/view/ViewStdVector.hpp
  include/alpaka/mem/view/ViewSubView.hpp
  include/alpaka/test/mem/view/Iterator.hpp
  include/alpaka/test/mem/view/ViewTest.hpp
  include/alpaka/vec/Vec.hpp
  include/alpaka/workdiv/WorkDivHelpers.hpp
  include/alpaka/workdiv/WorkDivMembers.hpp
  include/alpaka/workdiv/WorkDivUniformCudaHipBuiltIn.hpp
  test/integ/hostOnlyAPI/src/hostOnlyAPI.cpp
  test/integ/mandelbrot/src/mandelbrot.cpp
  test/integ/zeroDimBuffer/src/zeroDimBuffer.cpp
  test/unit/mem/view/src/ViewPlainPtrTest.cpp
Labels: Type:Refactoring

#1612 Make BufCpu class layout not depend on CUDA/HIP
  include/alpaka/mem/buf/BufCpu.hpp
Labels: Type:Enhancement, Backend:OpenMP, Backend:TBB, Backend:Boost.Fiber, Backend:std::thread, Backend:Serial

#1615 Fix include path for Intel FPGA extensions
  include/alpaka/pltf/PltfFpgaSyclIntel.hpp
Labels: Type:Bug, Backend:SYCL
