Repository alpaka-group/alpaka, pull requests merged in 2022-06, with the labels that each got.

#1736 Remove concept ConceptUniformCudaHip
  include/alpaka/acc/Traits.hpp
Labels: Type:Refactoring

#1735 Diagnose CallbackThread joining itself
  include/alpaka/core/CallbackThread.hpp
Labels: Type:Testing

#1743 Allow temporary destination views in memset/memcpy
  include/alpaka/mem/buf/cpu/Copy.hpp
  include/alpaka/mem/buf/cpu/Set.hpp
  include/alpaka/mem/buf/oacc/Copy.hpp
  include/alpaka/mem/buf/oacc/Set.hpp
  include/alpaka/mem/buf/omp5/Copy.hpp
  include/alpaka/mem/buf/omp5/Set.hpp
  include/alpaka/mem/buf/sycl/Copy.hpp
  include/alpaka/mem/buf/sycl/Set.hpp
  include/alpaka/mem/buf/uniformCudaHip/Copy.hpp
  include/alpaka/mem/buf/uniformCudaHip/Set.hpp
  include/alpaka/mem/view/Traits.hpp
  test/unit/mem/view/src/ViewPlainPtrTest.cpp
Labels: Type:Enhancement, Type:Refactoring

#1750 Remove support for clang-5
  .github/workflows/ci.yml
  README.md
  cmake/alpakaCommon.cmake
  include/alpaka/core/Decay.hpp
  include/alpaka/math/Traits.hpp
  include/alpaka/mem/buf/Traits.hpp
  include/alpaka/rand/Philox/PhiloxBaseTraits.hpp
  script/before_install.sh
  test/unit/mem/fence/src/FenceTest.cpp
Labels: Type:Testing

#1751 Set policy CMP0091 to NEW
  CMakeLists.txt
Labels: OS:Windows, Type:CMake
