Repository alpaka-group/alpaka, pull requests merged in 2022-12, with the labels that each got.

#1816 Fix missing `final` keyword for accelerator inheritance
  include/alpaka/acc/AccCpuSyclIntel.hpp
  include/alpaka/acc/AccFpgaSyclIntel.hpp
  include/alpaka/acc/AccFpgaSyclXilinx.hpp
  include/alpaka/acc/AccGpuSyclIntel.hpp
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
Labels: Type:Bug

#1853 fix CUDA CI
  script/install_cuda.sh
Labels: Type:Bug, Type:Testing

#1718 Drop Boost.fiber back-end
  .github/workflows/ci.yml
  README.md
  cmake/alpakaCommon.cmake
  docs/Doxyfile
  docs/source/advanced/cmake.rst
  docs/source/advanced/mapping.rst
  docs/source/basic/cheatsheet.rst
  docs/source/basic/intro.rst
  docs/source/dev/backends.rst
  example/bufferCopy/src/bufferCopy.cpp
  example/complex/src/complex.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/kernelSpecialization/src/kernelSpecialization.cpp
  example/reduce/src/alpakaConfig.hpp
  example/reduce/src/reduce.cpp
  example/vectorAdd/src/vectorAdd.cpp
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/Tag.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/atomic/AtomicNoOp.hpp
  include/alpaka/block/sync/BlockSyncBarrierFiber.hpp
  include/alpaka/core/ConcurrentExecPool.hpp
  include/alpaka/core/Fibers.hpp
  include/alpaka/example/ExampleDefaultAcc.hpp
  include/alpaka/idx/bt/IdxBtRefFiberIdMap.hpp
  include/alpaka/kernel/TaskKernelCpuFibers.hpp
  include/alpaka/standalone/CpuFibers.hpp
  include/alpaka/test/acc/TestAccs.hpp
  script/before_install.sh
  script/docker_ci.sh
  script/gitlabci/job_base.yml
  script/install_boost.sh
  script/run_generate.sh
  test/sanitizer_ubsan_blacklist.txt
  test/unit/acc/src/AccTagTest.cpp
Labels: Type:Refactoring, Backend:Boost.Fiber

#1855 Drop CUDA 9.2
  README.md
  cmake/alpakaCommon.cmake
  include/alpaka/warp/WarpUniformCudaHipBuiltIn.hpp
  script/gitlabci/job_cuda9.2.yml
  script/install_cuda.sh
Labels: Type:Testing, Backend:CUDA

#1766 Add clang-14 to CI
  .github/workflows/ci.yml
  README.md
  script/gitlabci/job_cuda10.0.yml
  script/gitlabci/job_cuda10.1.yml
  script/gitlabci/job_cuda10.2.yml
  script/gitlabci/job_cuda11.0.yml
  script/gitlabci/job_cuda11.1.yml
  script/gitlabci/job_cuda11.2.yml
  script/gitlabci/job_cuda11.3.yml
  script/gitlabci/job_cuda11.4.yml
  script/gitlabci/job_cuda11.5.yml
Labels: Type:Enhancement, Type:Testing, Backend:CUDA

#1860 Collapse compiler matrix
  README.md
Labels: Type:Enhancement, Type:Documentation

#1867 Add gcc-12 + OpenACC CI job
  .github/workflows/ci.yml
  README.md
Labels: Type:Enhancement, Type:Testing, Backend:OpenACC

#1849 remove boost 1.73 warning
  include/alpaka/atomic/AtomicCpu.hpp
Labels: Type:Refactoring

#1846 Add alpaka port of babelstream
  example/CMakeLists.txt
  example/babelstream/CMakeLists.txt
  example/babelstream/src/AlpakaStream.cpp
  example/babelstream/src/AlpakaStream.h
  example/babelstream/src/CUPLAStream.cpp
  example/babelstream/src/CUPLAStream.h
  example/babelstream/src/README.md
  example/babelstream/src/main.cpp
Labels: Type:Example

#1869 gitlab CI run more jobs as compile only
  script/gitlabci/job_cuda10.0.yml
  script/gitlabci/job_cuda10.1.yml
  script/gitlabci/job_cuda10.2.yml
  script/gitlabci/job_cuda11.0.yml
  script/gitlabci/job_cuda11.1.yml
  script/gitlabci/job_cuda11.2.yml
  script/gitlabci/job_cuda11.3.yml
  script/gitlabci/job_cuda11.4.yml
  script/gitlabci/job_cuda11.5.yml
  script/gitlabci/job_cuda11.6.yml
  script/gitlabci/job_hip4.2.yml
  script/gitlabci/job_hip4.3.yml
  script/gitlabci/job_hip4.5.yml
  script/gitlabci/job_hip5.0.yml
  script/gitlabci/job_hip5.1.yml
  script/gitlabci/job_hip5.2.yml
  script/gitlabci/job_hip5.3.yml
Labels: Type:Testing

#1878 Fix undefined constant with nvcc 12.0
  include/alpaka/test/event/EventHostManualTrigger.hpp
Labels: Type:Bug, Backend:CUDA

#1872 Drop legacy compilers and CUDA versions
  .github/workflows/ci.yml
  README.md
  include/alpaka/acc/Tag.hpp
  include/alpaka/core/Decay.hpp
  include/alpaka/math/Traits.hpp
  include/alpaka/mem/buf/Traits.hpp
  include/alpaka/rand/Philox/PhiloxBaseTraits.hpp
  script/before_install.sh
  script/gitlabci/job_analysis.yml
  script/gitlabci/job_base.yml
  script/gitlabci/job_clang.yml
  script/gitlabci/job_cuda10.0.yml
  script/gitlabci/job_cuda10.1.yml
  script/gitlabci/job_cuda10.2.yml
  script/install_clang.sh
  script/install_cuda.sh
  test/unit/mem/fence/src/FenceTest.cpp
Labels: Type:Refactoring, Type:Testing, Backend:CUDA

#1884 fix icpx error implicit conversion
  include/alpaka/rand/RandDefault.hpp
  test/integ/axpy/src/axpy.cpp
  test/unit/math/src/DataGen.hpp
  test/unit/math/src/FloatEqualExactTest.cpp
  test/unit/math/src/sincos.cpp
Labels: Type:Bug, Type:Testing

#1886 remove support for HIP 4.x
  README.md
  cmake/alpakaCommon.cmake
  script/gitlab_ci_run.sh
  script/gitlabci/job_hip4.2.yml
  script/gitlabci/job_hip4.3.yml
  script/gitlabci/job_hip4.5.yml
  script/gitlabci/job_hip5.1.yml
Labels: Type:Testing, Backend:HIP

#1887 Drop MSVC 2019
  .github/workflows/ci.yml
  README.md
  script/install_boost.sh
  script/install_cuda.sh
Labels: Type:Refactoring, Type:Testing, Backend:CUDA, Backend:TBB, OS:Windows
