Repository alpaka-group/alpaka, pull requests merged in 2022-11, with the labels that each got.

#1825 delete copy, assign, move and move assign operator for accelerators
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGenericSycl.hpp
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
  include/alpaka/acc/AccOacc.hpp
  include/alpaka/acc/AccOmp5.hpp
Labels: Type:Refactoring

#1829 Add some tests for subDivideGridElems
  include/alpaka/workdiv/WorkDivHelpers.hpp
  include/alpaka/workdiv/WorkDivMembers.hpp
  test/unit/workDiv/src/WorkDivHelpersTest.cpp
Labels: Type:Bug

#1840 CI: remove OMP2 backend tests for MACOSX
  .github/workflows/ci.yml
Labels: Type:Testing, Backend:OpenMP, OS:macOS, Type:CMake

#1826 fix warning calling `__host__` from `__host__ __device__` function
  include/alpaka/mem/view/Accessor.hpp
  include/alpaka/mem/view/Traits.hpp
  include/alpaka/mem/view/ViewAccessor.hpp
  include/alpaka/mem/view/ViewConst.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
Labels: Type:Warning

#1841 Drop alpaka/time
  include/alpaka/acc/AccCpuFibers.hpp
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
  include/alpaka/acc/AccOacc.hpp
  include/alpaka/acc/AccOmp5.hpp
  include/alpaka/alpaka.hpp
  include/alpaka/time/TimeOmp.hpp
  include/alpaka/time/TimeStdLib.hpp
  include/alpaka/time/TimeUniformCudaHipBuiltIn.hpp
  include/alpaka/time/Traits.hpp
  test/unit/CMakeLists.txt
  test/unit/time/CMakeLists.txt
  test/unit/time/src/ClockTest.cpp
Labels: Type:Testing, Backend:CUDA, Backend:OpenMP, Backend:TBB, Backend:Boost.Fiber, Backend:std::thread, Backend:OpenACC, Backend:SYCL, Backend:HIP, Backend:Serial

#1844 CI: change ROCm CI node
  script/gitlabci/job_base.yml
  script/install_hip.sh
Labels: Type:Testing, Backend:HIP

#1838 CI: add HIP/ROCm 5.3
  script/gitlabci/job_hip5.3.yml
Labels: Type:Testing, Backend:HIP

#1828 add math hyperbolic functions
  include/alpaka/math/MathGenericSycl.hpp
  include/alpaka/math/MathStdLib.hpp
  include/alpaka/math/MathUniformCudaHipBuiltIn.hpp
  include/alpaka/math/Traits.hpp
  test/unit/math/src/Functor.hpp
Labels: Type:Enhancement

#1847 Fix createView for containers without a size argument
  include/alpaka/mem/view/Traits.hpp
  test/unit/mem/view/src/ViewPlainPtrTest.cpp
Labels: Type:Bug
