Repository alpaka-group/alpaka, pull requests merged in 2022-09, with the labels that each got.

#1780 PhiloxBaseCommon,PhiloxConstants: constexpr workaround for GCC
  include/alpaka/rand/Philox/PhiloxBaseCommon.hpp
  include/alpaka/rand/Philox/PhiloxConstants.hpp
Labels: Type:Bug, Backend:OpenMP, Backend:OpenACC

#1790 Remove the functions to pin/unpin an existing buffer
  docs/source/dev/details.rst
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/mem/buf/BufGenericSycl.hpp
  include/alpaka/mem/buf/BufOacc.hpp
  include/alpaka/mem/buf/BufOmp5.hpp
  include/alpaka/mem/buf/BufUniformCudaHipRt.hpp
  include/alpaka/mem/buf/Traits.hpp
Labels: Type:Refactoring

#1785 add job generator to gitlab ci
  .gitignore
  .gitlab-ci.yml
  docs/source/conf.py
  docs/source/dev/ci.rst
  docs/source/images/job_generator_flow.svg
  script/job_generator/alpaka_filter.py
  script/job_generator/custom_job.py
  script/job_generator/generate_job_yaml.py
  script/job_generator/job_generator.py
  script/job_generator/reorder_jobs.py
  script/job_generator/requirements.txt
  script/job_generator/verify.py
  script/job_generator/versions.py
Labels: Type:Testing

#1803 Upgrade clang/CUDA headercheck CI to clang 13 and CUDA 11.2
  .github/workflows/ci.yml
Labels: Backend:CUDA
