Repository alpaka-group/alpaka, pull requests merged in 2023-12, with the labels that each got.

#2201 named access to `Vec`
  include/alpaka/vec/Vec.hpp
  test/unit/vec/src/VecTest.cpp
Labels: Type:Enhancement

#2198 add trait `IsKernelArgumentTriviallyCopyable`
  include/alpaka/kernel/Traits.hpp
Labels: Type:Refactoring

#2204 Change all CUDA warp operations to synchronise all threads
  include/alpaka/warp/WarpUniformCudaHipBuiltIn.hpp
Labels: Type:Refactoring, Backend:HIP

#2203 add CMake presets
  .gitignore
  CMakePresets.json
  docs/source/advanced/cmake.rst
Labels: Type:Enhancement, Type:Install

#2197 ROCm 5.3 and later support asynchronous memory operations
  include/alpaka/core/ApiHipRt.hpp
  include/alpaka/mem/buf/BufUniformCudaHipRt.hpp
Labels: Type:Enhancement, Backend:HIP

#2208 CI: fix OSX tests
  .github/workflows/ci.yml
  script/install_omp.sh
Labels: Type:Testing

#2199 remove `ALPAKA_ASSERT_OFFLOAD`, introduce `ALPAKA_ASSERT_ACC`
  cmake/alpakaCommon.cmake
  example/bufferCopy/src/bufferCopy.cpp
  include/alpaka/block/shared/dyn/BlockSharedMemDynMember.hpp
  include/alpaka/block/shared/st/detail/BlockSharedMemStMemberImpl.hpp
  include/alpaka/core/Assert.hpp
  include/alpaka/idx/bt/IdxBtOmp.hpp
  include/alpaka/warp/WarpGenericSycl.hpp
Labels: Type:Refactoring

#2210 add support for ROCm 6.0
  README.md
  cmake/alpakaCommon.cmake
  script/install_clang.sh
  script/install_hip.sh
  script/install_oneapi.sh
  script/job_generator/generate_job_yaml.py
  script/job_generator/versions.py
  script/run.sh
Labels: Type:Testing, Backend:HIP

#2213 fix icpx atomic OpenMP methods
  include/alpaka/atomic/AtomicOmpBuiltIn.hpp
Labels: Type:Bug, Backend:OpenMP
