Repository alpaka-group/alpaka, pull requests merged in 2023-09, with the labels that each got.

#2108 fix CUDA/HIP device wait for event
  include/alpaka/dev/DevUniformCudaHipRt.hpp
  include/alpaka/dev/common/QueueRegistry.hpp
  include/alpaka/event/EventUniformCudaHipRt.hpp
  include/alpaka/queue/cuda_hip/QueueUniformCudaHipRt.hpp
Labels: Type:Bug, Backend:CUDA, Backend:HIP

#1974 Rework `BOOST_COMP_HIP` and `BOOST_LANG_HIP`
  include/alpaka/core/BoostPredef.hpp
  include/alpaka/core/Common.hpp
Labels: Type:Enhancement, Backend:HIP

#2119 Fix unsigned integer conversion
  include/alpaka/mem/view/ViewAccessOps.hpp
Labels: Type:Warning

#2125 Fix SYCL pitch calculations
  include/alpaka/mem/buf/cpu/Copy.hpp
  include/alpaka/mem/buf/cpu/Set.hpp
  include/alpaka/mem/buf/sycl/Copy.hpp
  include/alpaka/mem/buf/sycl/Set.hpp
Labels: Type:Bug, Backend:SYCL

#2118 Fix nvcc warnings
  include/alpaka/test/Extent.hpp
  include/alpaka/test/event/EventHostManualTrigger.hpp
  include/alpaka/test/mem/view/ViewTest.hpp
  include/alpaka/vec/Vec.hpp
  test/common/devCompileOptions.cmake
  test/unit/math/src/mathLambda.cpp
  test/unit/vec/src/VecTest.cpp
Labels: Type:Warning, Backend:CUDA

#2121 Fix and update a few things in the documentation
  docs/source/basic/cheatsheet.rst
  docs/source/basic/example.rst
  docs/source/basic/install.rst
  docs/source/basic/intro.rst
  docs/source/basic/library.rst
  docs/source/index.rst
Labels: Type:Documentation

#2106 Remove STLTuple
  include/alpaka/core/STLTuple/LICENSE.txt
  include/alpaka/core/STLTuple/STLTuple.hpp
  include/alpaka/core/Tuple.hpp
  include/alpaka/kernel/TaskKernelGenericSycl.hpp
Labels: Type:Refactoring, Backend:SYCL

#2131 GitLab CI: enable runtime tests for gcc and clang cpu jobs
  .gitlab-ci.yml
  script/job_generator/generate_job_yaml.py
  script/job_generator/job_generator.py
  script/job_generator/job_modifier.py
Labels: Type:Bug, Type:Testing, Backend:OpenMP, Backend:TBB, Backend:std::thread, Backend:Serial

#2120 prevent `allocMappedBufIfSupported` from accepting arbitrary Types as `TPlatform`
  include/alpaka/mem/buf/Traits.hpp
Labels: Type:Bug

#2137 Let CMake print TSan warning
  test/unit/core/CMakeLists.txt
  test/unit/core/src/ThreadPool.cpp
  test/unit/mem/fence/CMakeLists.txt
Labels: Type:Warning

#2139 Add missing `ALPAKA_UNREACHABLE`
  include/alpaka/core/CudaHipCommon.hpp
Labels: Type:Warning, Backend:CUDA, Backend:HIP

#2141 Gitlab CI: enable Clang as device compiler for CPU backends
  .github/workflows/ci.yml
  script/job_generator/generate_job_yaml.py
  script/job_generator/job_generator.py
Labels: Type:Testing, Backend:OpenMP, Backend:TBB, Backend:std::thread, Backend:Serial

#2135 Improve nvcc's handling of `-Werror`
  test/common/devCompileOptions.cmake
Labels: Type:Warning, Backend:CUDA

#2144 Rename `extentBuf`, `extentView` and `offsetView`
  test/unit/mem/view/src/ViewPlainPtrTest.cpp
  test/unit/mem/view/src/ViewSubViewTest.cpp
Labels: Type:Warning, Type:Refactoring, Type:Testing

#2145 Simplify oneTBB installation
  script/install_oneapi.sh
  script/install_tbb.sh
Labels: Type:Bug, Type:Testing, Backend:TBB

#2140 update SYCL README
  README_SYCL.md
Labels: Backend:SYCL, Type:Documentation

#2136 Refactor `mapIdx` and `mapIdxPitchBytes`
  include/alpaka/idx/MapIdx.hpp
Labels: Type:Refactoring

#2149 Avoid unnecessary indention by conditional compilation
  include/alpaka/rand/RandGenericSycl.hpp
  include/alpaka/rand/RandUniformCudaHipRand.hpp
Labels: Type:Refactoring

#2154 Delete old sanitizer blacklists
  script/prepare_sanitizers.sh
  test/sanitizer_lsan_blacklist.txt
  test/sanitizer_ubsan_blacklist.txt
Labels: Type:Testing

#2155 Remove FP contraction for math test
  test/unit/math/CMakeLists.txt
Labels: Type:Refactoring, Type:Testing

#2152 Use a nested namespace specifier
  include/alpaka/atomic/AtomicUniformCudaHipBuiltIn.hpp
Labels: Type:Refactoring

#2151 Remove unnecessary member initialization calls
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuOmp2Threads.hpp
  include/alpaka/acc/AccCpuSerial.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
  include/alpaka/acc/AccCpuThreads.hpp
  include/alpaka/acc/AccGenericSycl.hpp
  include/alpaka/acc/AccGpuUniformCudaHipRt.hpp
Labels: Type:Refactoring

#2156 Refactor test classes
  include/alpaka/test/KernelExecutionFixture.hpp
  include/alpaka/test/queue/QueueTestFixture.hpp
  test/unit/mem/copy/src/BufSlicing.cpp
Labels: Type:Warning, Type:Refactoring, Type:Testing

#2158 Follow rule of zero
  include/alpaka/test/queue/QueueTestFixture.hpp
  test/unit/mem/copy/src/BufSlicing.cpp
Labels: Type:Refactoring

#2159 Silence more `nvcc` warnings
  include/alpaka/idx/MapIdx.hpp
  test/common/devCompileOptions.cmake
Labels: Type:Warning, Backend:CUDA

#2160 Switch to 1.0.0-rc1
  docs/source/conf.py
Labels: Type:Documentation

#2161 Disable activemask for SYCL
  include/alpaka/warp/WarpGenericSycl.hpp
  test/unit/warp/src/Activemask.cpp
Labels: Backend:SYCL

#2162 refactor template order `allocMappedBufIfSupported`
  include/alpaka/mem/buf/Traits.hpp
  test/integ/axpy/src/axpy.cpp
  test/integ/hostOnlyAPI/src/hostOnlyAPI.cpp
  test/integ/mandelbrot/src/mandelbrot.cpp
  test/integ/matMul/src/matMul.cpp
  test/integ/separableCompilation/src/main.cpp
  test/unit/math/src/Buffer.hpp
  test/unit/mem/fence/src/FenceTest.cpp
Labels: Type:Refactoring

#2165 Workaround gcc warning on uninitialized PlatformCpu
  include/alpaka/platform/PlatformCpu.hpp
  include/alpaka/test/KernelExecutionFixture.hpp
  include/alpaka/test/queue/QueueTestFixture.hpp
  test/unit/mem/copy/src/BufSlicing.cpp
Labels: Type:Warning

#2176 Fix clang-format version in docs
  CONTRIBUTING.md
  docs/source/dev/style.rst
Labels: Type:Documentation

#2179 Remove unnecessary `-fintelfpga` flag
  cmake/alpakaCommon.cmake
Labels: Type:Bug, Backend:SYCL, Type:CMake
