Repository alpaka-group/alpaka, pull requests merged in 2023-01, with the labels that each got.

#1889 add HIP to the CI generator parameter
  script/gitlabci/job_base.yml
  script/gitlabci/job_hip5.0.yml
  script/gitlabci/job_hip5.1.yml
  script/gitlabci/job_hip5.2.yml
  script/gitlabci/job_hip5.3.yml
  script/job_generator/alpaka_filter.py
  script/job_generator/alpaka_globals.py
  script/job_generator/custom_job.py
  script/job_generator/generate_job_yaml.py
  script/job_generator/job_generator.py
  script/job_generator/job_type_selection.py
  script/job_generator/reorder_jobs.py
  script/job_generator/verify.py
  script/job_generator/versions.py
Labels: Type:Enhancement, Type:Refactoring, Type:Testing, Backend:HIP

#1898 Add clang-15 to CI
  README.md
  script/gitlabci/job_clang.yml
Labels: Type:Enhancement, Type:Testing

#1883 Use `hipLaunchHostFunc` with HIP 5.4.0 and later
  include/alpaka/core/ApiHipRt.hpp
Labels: Type:Refactoring, Backend:HIP

#1894 Use `hipMallocAsync` and `hipFreeAsync` with HIP 5.2.0 and later
  include/alpaka/core/ApiHipRt.hpp
Labels: Type:Enhancement, Backend:HIP

#1899 Update to Xcode 14.2
  .github/workflows/ci.yml
  README.md
Labels: Type:Testing, OS:macOS

#1900 Manually install sanitizer libraries
  script/install_clang.sh
Labels: Type:Testing

#1902 Enable more C++20 jobs
  .github/workflows/ci.yml
  script/gitlabci/job_clang.yml
Labels: Type:Enhancement, Type:Testing

#1901 fix agc-manager detection in the CI
  script/install.sh
Labels: Type:Bug, Type:Testing

#1818 Implement trait constants
  include/alpaka/acc/Traits.hpp
  include/alpaka/dev/Traits.hpp
  include/alpaka/pltf/Traits.hpp
  include/alpaka/queue/Traits.hpp
Labels: Type:Enhancement

#1903 Update CMake and Boost point releases
  .github/workflows/ci.yml
Labels: Type:Enhancement, Type:Testing, Type:CMake

#1865 Make SYCL runtime objects `static`.
  include/alpaka/pltf/PltfCpuSyclIntel.hpp
  include/alpaka/pltf/PltfFpgaSyclIntel.hpp
  include/alpaka/pltf/PltfFpgaSyclXilinx.hpp
  include/alpaka/pltf/PltfGenericSycl.hpp
  include/alpaka/pltf/PltfGpuSyclIntel.hpp
Labels: Type:Enhancement, Type:Refactoring, Backend:SYCL

#1904 make GitLab CI jobs interruptible
  .gitlab-ci.yml
  script/job_generator/generate_job_yaml.py
Labels: Type:Testing

#1907 fix Clang installation in CI
  script/install_clang.sh
Labels: Type:Bug, Type:Testing

#1896 add CUDA compiler to job generator
  script/gitlabci/job_cuda11.0.yml
  script/gitlabci/job_cuda11.1.yml
  script/gitlabci/job_cuda11.2.yml
  script/gitlabci/job_cuda11.3.yml
  script/gitlabci/job_cuda11.4.yml
  script/gitlabci/job_cuda11.5.yml
  script/gitlabci/job_cuda11.6.yml
  script/gitlabci/job_cuda11.7.yml
  script/gitlabci/job_cuda11.8.yml
  script/gitlabci/job_cuda12.0.yml
  script/install_cmake.sh
  script/job_generator/alpaka_filter.py
  script/job_generator/alpaka_globals.py
  script/job_generator/generate_job_yaml.py
  script/job_generator/job_generator.py
  script/job_generator/job_modifier.py
  script/job_generator/job_type_selection.py
  script/job_generator/versions.py
Labels: Type:Testing

#1908 GitLab CI: split compile only and runtime test in two child pipelines
  .gitlab-ci.yml
  script/job_generator/generate_job_yaml.py
  script/job_generator/job_generator.py
Labels: Type:Testing
