Repository alpaka-group/alpaka, pull requests merged in 2023-07, with the labels that each got.

#1999 Refactor ndloop
  include/alpaka/meta/NdLoop.hpp
Labels: Type:Refactoring

#1998 Refactor TaskKernelCpuThreads
  include/alpaka/kernel/TaskKernelCpuThreads.hpp
Labels: Type:Refactoring

#1989 fix host callback unit test
  test/unit/queue/src/QueueTest.cpp
Labels: Type:Bug, Type:Testing

#1986 Enable two phase lookup with MSVC
  include/alpaka/mem/fence/MemFenceOmp2Threads.hpp
  test/common/devCompileOptions.cmake
Labels: Type:Refactoring

#2006 Silence clang-16 warnings about unsafe buffer usage.
  cmake/alpakaCommon.cmake
  include/alpaka/mem/buf/BufCpu.hpp
  test/common/CMakeLists.txt
Labels: Type:Enhancement, Type:Warning

#2010 Update readthedocs config to version 2
  .readthedocs.yml
Labels: Type:Bug, Type:Documentation

#2008 Remove the requirement that the native handle is an `int`
  test/unit/traits/src/NativeHandleTest.cpp
Labels: Type:Testing, Backend:SYCL

#2014 Change separable compilation test from `double` to `float`
  test/integ/separableCompilation/include/mysqrt.hpp
  test/integ/separableCompilation/src/main.cpp
  test/integ/separableCompilation/src/mysqrt.cpp
Labels: Type:Testing

#2005 update alpaka-job-matrix-library to 1.3.5
  .gitlab-ci.yml
  script/job_generator/requirements.txt
  script/job_generator/verify.py
Labels: Type:Enhancement, Type:Testing

#2017 Update the Any test to work with a sub-group size of 4
  test/unit/warp/src/Any.cpp
Labels: Type:Testing

#2018 Remove conflicting entry from .clang-format
  .clang-format
Labels: Type:Bug

#2020 Fix compilation errors in PltfGenericSycl
  include/alpaka/pltf/PltfGenericSycl.hpp
Labels: Backend:SYCL

#2021 Fix the delagating constructor in KernelExecutionFixture
  include/alpaka/test/KernelExecutionFixture.hpp
Labels: Type:Bug

#2022 queue test: fix catch2 usages within threads
  test/unit/queue/src/QueueTest.cpp
Labels: Type:Bug, Type:Testing

#2026 fix CallBack thread data race
  include/alpaka/core/CallbackThread.hpp
Labels: Type:Bug

#2029 add math::log2 and math::log10
  include/alpaka/math/MathGenericSycl.hpp
  include/alpaka/math/MathStdLib.hpp
  include/alpaka/math/MathUniformCudaHipBuiltIn.hpp
  include/alpaka/math/Traits.hpp
  test/unit/math/src/Functor.hpp
  test/unit/math/src/mathADL.cpp
Labels: Type:Enhancement

#2011 fix callback thread task lifetime
  include/alpaka/core/CallbackThread.hpp
  include/alpaka/event/EventGenericThreads.hpp
  include/alpaka/queue/cuda_hip/QueueUniformCudaHipRt.hpp
  include/alpaka/test/event/EventHostManualTrigger.hpp
Labels: Type:Bug

#2030 add missing ADL tests for math hyperbolic functions
  test/unit/math/src/mathADL.cpp
Labels: Type:Testing

#2025 documentation: QueueCpuOmp2Collective
  include/alpaka/test/queue/QueueCpuOmp2Collective.hpp
Labels: Type:Documentation

#2032 Complete renaming Pltf to Platform
  include/alpaka/mem/buf/BufCpuSycl.hpp
  include/alpaka/mem/buf/BufGenericSycl.hpp
  include/alpaka/mem/buf/BufGpuSyclIntel.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
  include/alpaka/platform/PlatformGenericSycl.hpp
Labels: Type:Refactoring

#2031 Update SYCL README
  README_SYCL.md
Labels: Backend:SYCL, Type:Documentation

#1971 Add clang-16 test runner
  README.md
  script/job_generator/alpaka_filter.py
  script/job_generator/requirements.txt
  script/job_generator/versions.py
Labels: Type:Enhancement, Type:Testing

#2013 Some refactoring around QueueCpuOmp2Collective
  include/alpaka/test/queue/QueueCpuOmp2Collective.hpp
  test/unit/queue/src/CollectiveQueue.cpp
Labels: Type:Refactoring, Backend:OpenMP
