Repository alpaka-group/alpaka, pull requests merged in 2023-11, with the labels that each got.

#2183 Add 1.0.0 authors
  .zenodo.json
  README.md
Labels: Type:Documentation

#2189 Set release date in changelog
  CHANGELOG.md
Labels: Type:Documentation

#2168 Strip namespaces from mathTest
  test/unit/math/src/Buffer.hpp
  test/unit/math/src/DataGen.hpp
  test/unit/math/src/Defines.hpp
  test/unit/math/src/FloatEqualExactTest.cpp
  test/unit/math/src/Functor.hpp
  test/unit/math/src/TestTemplate.hpp
  test/unit/math/src/mathComplexDouble.cpp
  test/unit/math/src/mathComplexFloat.cpp
  test/unit/math/src/mathDouble.cpp
  test/unit/math/src/mathFloat.cpp
  test/unit/math/src/mathLambda.cpp
  test/unit/math/src/powMixedTypes.cpp
  test/unit/math/src/sincos.cpp
Labels: Type:Refactoring, Type:Testing

#2193 Trim device names
  include/alpaka/dev/Traits.hpp
Labels: Type:Enhancement

#2196 Check for HIP versions in min/max range
  cmake/alpakaCommon.cmake
Labels: Type:Refactoring, Type:Install

#2175 Add alpaka-ls
  example/CMakeLists.txt
  example/ls/CMakeLists.txt
  example/ls/src/ls.cpp
Labels: Type:Testing
