Repository alpaka-group/alpaka, pull requests merged in 2024-08, with the labels that each got.

#2331 Rewrite the `getValidWorkDivForKernel` 1D and 2D tests
  test/unit/workDiv/src/WorkDivForKernelTest.cpp
Labels: Type:Bug, Type:Testing

#2329 Link `libcudart` even when `libcurand` is not used
  cmake/alpakaCommon.cmake
Labels: Type:Bug, Backend:CUDA

#2330 Re-enable the `KernelNoTemplateGpu` test
  test/unit/kernel/src/KernelWithoutTemplatedAccParam.cpp
Labels: Type:Testing, Backend:CUDA, Backend:HIP

#2332 Remove unnecessary include
  include/alpaka/kernel/TaskKernelGenericSycl.hpp
Labels: Type:Refactoring

#2335 Fix `isValidWorkDivKernel` to use the correct device
  include/alpaka/workdiv/WorkDivHelpers.hpp
Labels: Type:Bug

#2336 fix complex math pow test
  test/unit/math/src/TestTemplate.hpp
Labels: Type:Testing

#2338 Add thread count to CPU blocks accelerators
  include/alpaka/acc/AccCpuOmp2Blocks.hpp
  include/alpaka/acc/AccCpuTbbBlocks.hpp
Labels: Type:Refactoring, Backend:OpenMP, Backend:TBB

#2342 Make alpaka follow `CMAKE_CUDA_RUNTIME_LIBRARY`
  cmake/alpakaCommon.cmake
Labels: Type:Refactoring, Backend:CUDA, Type:CMake

#2344 Fix the device used by `KernelExecutionFixture`
  include/alpaka/test/KernelExecutionFixture.hpp
Labels: Type:Bug, Type:Testing

#2343 Ignore `vim` temporary files
  .gitignore
Labels: Type:Enhancement

#2347 fix `getFunctionAttributes` for the SYCL backend
  include/alpaka/kernel/TaskKernelCpuSycl.hpp
  include/alpaka/kernel/TaskKernelFpgaSyclIntel.hpp
  include/alpaka/kernel/TaskKernelGenericSycl.hpp
  include/alpaka/kernel/TaskKernelGpuSyclIntel.hpp
Labels: Type:Bug

#2348 Use shared CUDA libraries by default
  cmake/alpakaCommon.cmake
Labels: Type:Bug, Backend:CUDA, Type:CMake

#2351 Add missing #include
  include/alpaka/mem/global/DeviceGlobalGenericSycl.hpp
Labels: Type:Bug

#2354 add colored output to the CI scripts
  script/after_failure.sh
  script/before_install.sh
  script/ci.sh
  script/docker_ci.sh
  script/docker_retry.sh
  script/install.sh
  script/install_analysis.sh
  script/install_boost.sh
  script/install_clang.sh
  script/install_cmake.sh
  script/install_cuda.sh
  script/install_doxygen.sh
  script/install_gcc.sh
  script/install_hip.sh
  script/install_omp.sh
  script/install_oneapi.sh
  script/install_tbb.sh
  script/prepare_sanitizers.sh
  script/print_env.sh
  script/push_doc.sh
  script/run.sh
  script/run_analysis.sh
  script/run_build.sh
  script/run_doxygen.sh
  script/run_generate.sh
  script/run_install.sh
  script/run_tests.sh
  script/setup_utilities.sh
  script/setup_utilities/agc-manager.sh
  script/setup_utilities/color_echo.sh
  script/setup_utilities/sudo.sh
Labels: Type:Enhancement, Type:Testing

#2355 CI jobs: allow to disable exit on error
  script/gitlabci/print_env.sh
  script/run.sh
  script/setup_utilities.sh
  script/setup_utilities/set.sh
Labels: Type:Enhancement, Type:Testing

#2359 add some color output to CI install scripts
  script/install_boost.sh
  script/install_clang.sh
  script/install_cmake.sh
  script/install_cuda.sh
  script/install_gcc.sh
  script/install_hip.sh
  script/install_oneapi.sh
  script/install_tbb.sh
  script/setup_utilities/travis_retry.sh
Labels: Type:Enhancement, Type:Testing

#2349 remove `KernelBundle`, change signature of `[get|is]ValidWorkDiv*`
  docs/source/basic/cheatsheet.rst
  example/bufferCopy/src/bufferCopy.cpp
  example/complex/src/complex.cpp
  example/conv2DWithMdspan/src/conv2DWithMdspan.cpp
  example/convolution1D/src/convolution1D.cpp
  example/convolution2D/src/convolution2D.cpp
  example/counterBasedRng/src/counterBasedRng.cpp
  example/heatEquation/src/heatEquation.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/kernelSpecialization/src/kernelSpecialization.cpp
  example/matrixMulWithMdspan/src/matrixMulMdSpan.cpp
  example/monteCarloIntegration/src/monteCarloIntegration.cpp
  example/openMPSchedule/src/openMPSchedule.cpp
  example/randomCells2D/src/randomCells2D.cpp
  example/randomStrategies/src/randomStrategies.cpp
  example/vectorAdd/src/vectorAdd.cpp
  include/alpaka/alpaka.hpp
  include/alpaka/kernel/KernelBundle.hpp
  include/alpaka/kernel/TaskKernelCpuOmp2Blocks.hpp
  include/alpaka/kernel/TaskKernelCpuOmp2Threads.hpp
  include/alpaka/kernel/TaskKernelCpuSerial.hpp
  include/alpaka/kernel/TaskKernelCpuSycl.hpp
  include/alpaka/kernel/TaskKernelCpuTbbBlocks.hpp
  include/alpaka/kernel/TaskKernelCpuThreads.hpp
  include/alpaka/kernel/TaskKernelFpgaSyclIntel.hpp
  include/alpaka/kernel/TaskKernelGenericSycl.hpp
  include/alpaka/kernel/TaskKernelGpuSyclIntel.hpp
  include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp
  include/alpaka/kernel/Traits.hpp
  include/alpaka/test/KernelExecutionFixture.hpp
  include/alpaka/workdiv/WorkDivHelpers.hpp
  test/integ/axpy/src/axpy.cpp
  test/integ/mandelbrot/src/mandelbrot.cpp
  test/integ/matMul/src/matMul.cpp
  test/integ/separableCompilation/src/main.cpp
  test/integ/sharedMem/src/sharedMem.cpp
  test/unit/math/src/TestTemplate.hpp
  test/unit/workDiv/src/WorkDivForKernelTest.cpp
Labels: Type:Refactoring

#2360 remove second Docker container launch in GitHub Actions Linux Jobs
  .github/workflows/ci.yml
  script/ci.sh
  script/docker_ci.sh
  script/docker_retry.sh
  script/install_clang.sh
Labels: Type:Bug, Type:Enhancement, Type:Testing

#2320 alpaka CI: set CMAKE_CXX_COMPILER instead using update-alternatives
  .github/workflows/ci.yml
  example/complex/CMakeLists.txt
  script/before_install.sh
  script/gitlabci/job_base.yml
  script/gitlabci/print_env.sh
  script/install.sh
  script/install_boost.sh
  script/install_clang.sh
  script/install_cuda.sh
  script/install_gcc.sh
  script/install_hip.sh
  script/install_oneapi.sh
  script/job_generator/generate_job_yaml.py
  script/prepare_sanitizers.sh
  script/run.sh
  script/run_generate.sh
Labels: Type:Bug, Type:Enhancement, Type:Testing

#2364 Add ORCID for Julian Lenz
  .zenodo.json
Labels: Type:Documentation

#2363 rename `threadElemExtents` into `threadElemExtent`
  include/alpaka/workdiv/WorkDivHelpers.hpp
Labels: Type:Refactoring

#2362 rename `threadsPerGrid` to `elementsPerGrid`
  example/bufferCopy/src/bufferCopy.cpp
  example/complex/src/complex.cpp
  example/convolution1D/src/convolution1D.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/kernelSpecialization/src/kernelSpecialization.cpp
  example/openMPSchedule/src/openMPSchedule.cpp
  test/unit/workDiv/src/WorkDivForKernelTest.cpp
Labels: Type:Refactoring, Type:Example
