Repository alpaka-group/alpaka, pull requests merged in 2024-03, with the labels that each got.

#2245 fix CI bug for omp installation
  script/install_omp.sh
Labels: Type:Bug, Type:Testing

#2236 Allow non-integral types in Vec generator constructor
  include/alpaka/vec/Vec.hpp
  test/unit/vec/src/VecTest.cpp
Labels: Type:Bug

#2243 workDivMembers construction with a user defined type
  test/unit/workDiv/CMakeLists.txt
  test/unit/workDiv/src/FooVec.hpp
  test/unit/workDiv/src/WorkDivHelpersTest.cpp
Labels: Type:Testing

#2250 Fix tsan error: change memory randomization
  script/ci.sh
Labels: Type:Bug, Type:Testing

#2238 Remove CUDA vector array wrapper
  example/counterBasedRng/src/counterBasedRng.cpp
  example/randomCells2D/src/randomCells2D.cpp
  example/randomStrategies/src/randomStrategies.cpp
  include/alpaka/alpaka.hpp
  include/alpaka/meta/CudaVectorArrayWrapper.hpp
  include/alpaka/meta/IsArrayOrVector.hpp
  include/alpaka/rand/Philox/PhiloxBaseCommon.hpp
  include/alpaka/rand/Philox/PhiloxBaseCudaArray.hpp
  include/alpaka/rand/Philox/PhiloxBaseStdArray.hpp
  include/alpaka/rand/Philox/PhiloxBaseTraits.hpp
  include/alpaka/rand/Philox/PhiloxConstants.hpp
  include/alpaka/rand/Philox/PhiloxSingle.hpp
  include/alpaka/rand/Philox/PhiloxStateless.hpp
  include/alpaka/rand/Philox/PhiloxStatelessKeyedBase.hpp
  include/alpaka/rand/Philox/PhiloxStatelessVector.hpp
  include/alpaka/rand/Philox/PhiloxVector.hpp
  include/alpaka/rand/RandDefault.hpp
  include/alpaka/rand/RandPhilox.hpp
  include/alpaka/rand/RandPhiloxStateless.hpp
  include/alpaka/rand/RandUniformCudaHipRand.hpp
  include/alpaka/vec/Vec.hpp
  test/unit/meta/src/CudaVectorArrayWrapperTest.cpp
  test/unit/meta/src/IsArrayOrVectorTest.cpp
  test/unit/rand/src/PhiloxTest.cpp
  test/unit/vec/src/VecTest.cpp
Labels: Type:Refactoring, Backend:CUDA, Backend:HIP

#2237 Create benchmarks directory and move babelstream into it
  CMakeLists.txt
  benchmarks/CMakeLists.txt
  benchmarks/babelstream/CMakeLists.txt
  benchmarks/babelstream/src/AlpakaStream.cpp
  benchmarks/babelstream/src/AlpakaStream.h
  benchmarks/babelstream/src/LICENSE
  benchmarks/babelstream/src/README.md
  benchmarks/babelstream/src/Stream.h
  benchmarks/babelstream/src/main.cpp
  example/CMakeLists.txt
  script/run_generate.sh
Labels: Type:Refactoring, Type:Testing
