Repository alpaka-group/alpaka, pull requests merged in 2024-11, with the labels that each got.

#2415 add static function dim() to alpaka::Vec
  include/alpaka/vec/Vec.hpp
  test/unit/vec/src/VecTest.cpp
Labels: Type:Enhancement

#2421 fix typo in CI pipeline
  .gitlab-ci.yml
Labels: Type:Bug, Type:Testing

#2422 Check in CMake if the compiler supports the minimum required C++ standard
  cmake/alpakaCommon.cmake
Labels: Type:Enhancement, Type:CMake

#2423 fix printing environment variables in GitLab CI
  script/gitlabci/print_env.sh
Labels: Type:Bug, Type:Testing

#2425 update MacOS runner to 14 and 15
  .github/workflows/ci.yml
  README.md
  script/homebrew/13.2.1/libomp.rb
  script/homebrew/14.2/libomp.rb
  script/homebrew/14.3.1/libomp.rb
  script/install_omp.sh
  script/readme_generator/supported_compilers.json
Labels: Type:Bug, Type:Testing, OS:macOS

#2424 set default environment variables in the CI
  .github/workflows/ci.yml
  script/gitlabci/print_env.sh
  script/job_generator/generate_job_yaml.py
  script/set_default_env_vars.sh
Labels: Type:Enhancement, Type:Testing

#2428 [1.3.0] add static function dim() to alpaka::Vec
  include/alpaka/vec/Vec.hpp
  test/unit/vec/src/VecTest.cpp
Labels: Type:Enhancement

#2420 fix bablestream benchmark
  benchmarks/babelstream/src/babelStreamCommon.hpp
  benchmarks/babelstream/src/babelStreamMainTest.cpp
Labels: Type:Bug
