Repository alpaka-group/alpaka, pull requests merged in 2024-05, with the labels that each got.

#2264 Restrict utilities to integer types
  include/alpaka/core/Utility.hpp
Labels: Type:Enhancement

#2266 fix forwarding of msvc compiler flag '/Zo'
  test/common/devCompileOptions.cmake
Labels: Type:Bug, Backend:CUDA, OS:Windows, Type:CMake

#2265 fix usage of Idx to alpaka::Idx
  include/alpaka/mem/buf/BufUniformCudaHipRt.hpp
  include/alpaka/mem/view/ViewSubView.hpp
Labels: Type:Bug, OS:Windows

#2267 implement AccIsEnabled
  cmake/alpakaCommon.cmake
  include/alpaka/acc/Tag.hpp
  include/alpaka/acc/TagAccIsEnabled.hpp
  include/alpaka/alpaka.hpp
  test/unit/acc/src/AccTagTest.cpp
Labels: Type:Enhancement, Backend:CUDA, Backend:OpenMP, Backend:TBB, Backend:Boost.Fiber, Backend:std::thread, Backend:SYCL, Backend:HIP, Backend:Serial

#2273 fix alpaka_add_library relocatable device code
  cmake/addLibrary.cmake
Labels: Type:Bug, Type:CMake

#2269 implement alpaka::meta::isList, alpaka::meta::ToList and alpaka::meta::toTuple
  include/alpaka/meta/TypeListOps.hpp
  test/unit/meta/src/TypeListOpsTest.cpp
Labels: Type:Enhancement

#2270 refactor template order `allocMappedBuf`
  docs/source/dev/backends.rst
  include/alpaka/mem/buf/Traits.hpp
Labels: Type:Enhancement, Type:Refactoring

#2272 document cmake flag to build alpaka benchmarks
  docs/source/advanced/cmake.rst
Labels: Type:Documentation, Type:CMake
