Repository alpaka-group/alpaka, pull requests merged in 2024-01, with the labels that each got.

#2214 remove HIP 5.0 support
  README.md
  cmake/alpakaCommon.cmake
  script/job_generator/generate_job_yaml.py
  script/job_generator/versions.py
Labels: Type:Refactoring

#2217 Align BabelStream with LLAMA version
  example/babelstream/src/AlpakaStream.cpp
  example/babelstream/src/AlpakaStream.h
  example/babelstream/src/README.md
  example/babelstream/src/Stream.h
  example/babelstream/src/main.cpp
Labels: Type:Refactoring, Type:Example

#2211 add CUDA 12.3 to the CI
  README.md
  script/install_cuda.sh
  script/job_generator/requirements.txt
  script/job_generator/verify.py
  script/job_generator/versions.py
Labels: Type:Testing

#2218 Add verbose output to alpaka-ls
  example/ls/src/ls.cpp
Labels: Type:Example

#2224 update develop version to 1.2.0
  include/alpaka/version.hpp
Labels: Type:Documentation

#2223 set version to 1.1.0 for the next release
  include/alpaka/version.hpp
Labels: Type:Documentation

#2225 Changelog for version 1.1.0
  CHANGELOG.md
Labels: Type:Documentation

#2227 update zenodo.json
  .zenodo.json
Labels: Type:Documentation

#2230 update list of contributors in readme
  README.md
Labels: Type:Documentation

#2233 Remove Obsolete #ifdefs from the examples
  example/bufferCopy/src/bufferCopy.cpp
  example/complex/src/complex.cpp
  example/counterBasedRng/src/counterBasedRng.cpp
  example/heatEquation/src/heatEquation.cpp
  example/helloWorld/src/helloWorld.cpp
  example/kernelSpecialization/src/kernelSpecialization.cpp
  example/parallelLoopPatterns/src/parallelLoopPatterns.cpp
  example/tagSpecialization/src/tagSpecialization.cpp
  example/vectorAdd/src/vectorAdd.cpp
Labels: Type:Refactoring, Type:Example

#2232 Revise coding guidelines
  docs/source/dev/style.rst
Labels: Type:Refactoring

#2220 1D Convolution example
  example/CMakeLists.txt
  example/convolution1D/CMakeLists.txt
  example/convolution1D/src/convolution1D.cpp
Labels: Type:Example
