Repository alpaka-group/alpaka, pull requests merged in 2024-09, with the labels that each got.

#2374 refactoring of the SYCL backend
  include/alpaka/acc/AccCpuSycl.hpp
  include/alpaka/acc/AccFpgaSyclIntel.hpp
  include/alpaka/acc/AccGenericSycl.hpp
  include/alpaka/acc/AccGpuSyclIntel.hpp
  include/alpaka/dev/DevCpuSycl.hpp
  include/alpaka/dev/DevFpgaSyclIntel.hpp
  include/alpaka/dev/DevGenericSycl.hpp
  include/alpaka/dev/DevGpuSyclIntel.hpp
  include/alpaka/event/EventCpuSycl.hpp
  include/alpaka/event/EventFpgaSyclIntel.hpp
  include/alpaka/event/EventGenericSycl.hpp
  include/alpaka/event/EventGpuSyclIntel.hpp
  include/alpaka/kernel/TaskKernelCpuSycl.hpp
  include/alpaka/kernel/TaskKernelFpgaSyclIntel.hpp
  include/alpaka/kernel/TaskKernelGenericSycl.hpp
  include/alpaka/kernel/TaskKernelGpuSyclIntel.hpp
  include/alpaka/mem/buf/BufCpuSycl.hpp
  include/alpaka/mem/buf/BufFpgaSyclIntel.hpp
  include/alpaka/mem/buf/BufGenericSycl.hpp
  include/alpaka/mem/buf/BufGpuSyclIntel.hpp
  include/alpaka/mem/buf/sycl/Copy.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
  include/alpaka/platform/PlatformCpuSycl.hpp
  include/alpaka/platform/PlatformFpgaSyclIntel.hpp
  include/alpaka/platform/PlatformGenericSycl.hpp
  include/alpaka/platform/PlatformGpuSyclIntel.hpp
  include/alpaka/queue/QueueCpuSyclBlocking.hpp
  include/alpaka/queue/QueueCpuSyclNonBlocking.hpp
  include/alpaka/queue/QueueFpgaSyclIntelBlocking.hpp
  include/alpaka/queue/QueueFpgaSyclIntelNonBlocking.hpp
  include/alpaka/queue/QueueGenericSyclBlocking.hpp
  include/alpaka/queue/QueueGenericSyclNonBlocking.hpp
  include/alpaka/queue/QueueGpuSyclIntelBlocking.hpp
  include/alpaka/queue/QueueGpuSyclIntelNonBlocking.hpp
  include/alpaka/queue/sycl/QueueGenericSyclBase.hpp
  include/alpaka/test/acc/TestAccs.hpp
  include/alpaka/test/event/EventHostManualTrigger.hpp
  include/alpaka/test/queue/Queue.hpp
Labels: Type:Refactoring, Backend:SYCL

#2376 Mark the deduction guide for vector as ALPAKA_FN_HOST_ACC
  example/bufferCopy/src/bufferCopy.cpp
  include/alpaka/vec/Vec.hpp
Labels: Type:Bug

#2283 Throw error from device to host with a msg #2258
  include/alpaka/alpaka.hpp
  include/alpaka/core/RuntimeMacros.hpp
  test/unit/CMakeLists.txt
  test/unit/runtime/CMakeLists.txt
  test/unit/runtime/src/KernelThrow.cpp
Labels: Type:Enhancement

#2299 Make babelstream runnable and test for different Accs
  CMakeLists.txt
  benchmarks/CMakeLists.txt
  benchmarks/babelstream/CMakeLists.txt
  benchmarks/babelstream/src/AlpakaStream.cpp
  benchmarks/babelstream/src/AlpakaStream.h
  benchmarks/babelstream/src/README.md
  benchmarks/babelstream/src/Stream.h
  benchmarks/babelstream/src/babelStreamCommon.hpp
  benchmarks/babelstream/src/babelStreamMainTest.cpp
  benchmarks/babelstream/src/main.cpp
  thirdParty/CMakeLists.txt
Labels: Type:Testing

#2384 Heat Equation 2D Bug Fixes
  example/heatEquation2D/src/analyticalSolution.hpp
  example/heatEquation2D/src/heatEquation2D.cpp
  example/heatEquation2D/src/writeImage.hpp
Labels: Type:Bug, Type:Example

#2386 Update cheatsheet.rst
  docs/source/basic/cheatsheet.rst
Labels: Type:Documentation

#2383 reduce Uniform/Independent-Elements iterator register footprint
  example/bufferCopy/src/bufferCopy.cpp
  include/alpaka/exec/IndependentElements.hpp
  include/alpaka/exec/UniformElements.hpp
Labels: Type:Refactoring

#2388 implement markdown generator for compiler backend compatibility table
  README.md
  script/readme_generator/README.md
  script/readme_generator/generate_supported_compilers.py
  script/readme_generator/supported_compilers.json
Labels: Type:Enhancement, Type:Documentation

#2390 fix and update SYCL targets
  include/alpaka/kernel/SyclSubgroupSize.hpp
Labels: Type:Refactoring, Backend:SYCL

#2392 fix cray clang compiler errors
  cmake/alpakaCommon.cmake
  include/alpaka/meta/Filter.hpp
Labels: Type:Bug

#2393 execute pre-commit and apply changes
  script/install_cuda.sh
  script/job_generator/alpaka_filter.py
  script/readme_generator/generate_supported_compilers.py
  script/setup_utilities/travis_retry.sh
Labels: Type:Refactoring

#2394 update README.md
  README.md
Labels: Type:Documentation

#2398 Update cheatsheet.rst
  docs/source/basic/cheatsheet.rst
Labels: Type:Documentation

#2399 change documentation for Buf and mdspan
  docs/source/basic/cheatsheet.rst
Labels: Type:Documentation

#2401 update version to 2.0.0
  include/alpaka/version.hpp
Labels: Type:Documentation

#2400 add changelog for release 1.2.0
  CHANGELOG.md
Labels: Type:Documentation
