Repository alpaka-group/alpaka, pull requests merged in 2024-07, with the labels that each got.

#2306 update CI container to version 3.2
  .gitlab-ci.yml
  script/gitlabci/job_cuda.yml
  script/job_generator/alpaka_filter.py
Labels: Type:Testing

#2302 add trait `IsKernelTriviallyCopyable`
  include/alpaka/kernel/Traits.hpp
Labels: Type:Refactoring

#2301 move the `Complex` class to `internal` namespace
  include/alpaka/math/Complex.hpp
Labels: Type:Bug, Type:Refactoring

#2322 ctest: display only output of tests, which failed
  script/run_tests.sh
Labels: Type:Enhancement, Type:Testing

#2324 fix missing C++20 STL for ICPX in the CI
  script/install_oneapi.sh
Labels: Type:Bug, Type:Testing

#2323 CI: improve script utils
  script/after_failure.sh
  script/before_install.sh
  script/ci.sh
  script/docker_ci.sh
  script/docker_retry.sh
  script/gitlab_ci_run.sh
  script/gitlabci/fake_sudo.sh
  script/gitlabci/print_env.sh
  script/install.sh
  script/install_analysis.sh
  script/install_boost.sh
  script/install_clang.sh
  script/install_cmake.sh
  script/install_cuda.sh
  script/install_doxygen.sh
  script/install_gcc.sh
  script/install_hip.sh
  script/install_omp.sh
  script/install_oneapi.sh
  script/install_tbb.sh
  script/prepare_sanitizers.sh
  script/print_env.sh
  script/push_doc.sh
  script/run.sh
  script/run_analysis.sh
  script/run_build.sh
  script/run_doxygen.sh
  script/run_generate.sh
  script/run_install.sh
  script/run_tests.sh
  script/setup_utilities.sh
  script/setup_utilities/agc-manager.sh
  script/setup_utilities/set.sh
  script/setup_utilities/sudo.sh
  script/setup_utilities/travis_retry.sh
Labels: Type:Enhancement, Type:Testing

#2325 add remove_restrict to kernelbundle
  include/alpaka/kernel/KernelBundle.hpp
Labels: Type:Refactoring

#2311 Update the CUDA/HIP kernel tasks
  include/alpaka/kernel/TaskKernelGpuUniformCudaHipRt.hpp
Labels: Type:Refactoring, Backend:CUDA, Backend:HIP

#2317 Matrix Multiplication example using MdSpan
  example/CMakeLists.txt
  example/matrixMulWithMdspan/CMakeLists.txt
  example/matrixMulWithMdspan/src/matrixMulMdSpan.cpp
Labels: Type:Example

#2326 reduce code duplications `matrixMulWithMdSpan`
  example/matrixMulWithMdspan/src/matrixMulMdSpan.cpp
Labels: Type:Refactoring, Type:Example
