Repository alpaka-group/alpaka, pull requests merged in 2024-10, with the labels that each got.

#2404 fix Aurora's ORCID
  .zenodo.json
Labels: Type:Bug, Type:Documentation

#2406 set release date for 1.2.0 to 02.10.2024
  CHANGELOG.md
Labels: Type:Documentation

#2402 switch to C++20 only
  .clang-format
  .github/workflows/ci.yml
  .zenodo.json
  CMakeLists.txt
  README.md
  benchmarks/CMakeLists.txt
  benchmarks/babelstream/CMakeLists.txt
  cmake/alpakaCommon.cmake
  docs/source/basic/example.rst
  docs/source/basic/install.rst
  docs/source/basic/library.rst
  docs/source/conf.py
  docs/source/dev/details.rst
  docs/source/index.rst
  example/CMakeLists.txt
  example/bufferCopy/CMakeLists.txt
  example/complex/CMakeLists.txt
  example/conv2DWithMdspan/CMakeLists.txt
  example/convolution1D/CMakeLists.txt
  example/convolution2D/CMakeLists.txt
  example/counterBasedRng/CMakeLists.txt
  example/heatEquation/CMakeLists.txt
  example/heatEquation2D/CMakeLists.txt
  example/helloWorld/CMakeLists.txt
  example/helloWorldLambda/CMakeLists.txt
  example/kernelSpecialization/CMakeLists.txt
  example/ls/CMakeLists.txt
  example/matrixMulWithMdspan/CMakeLists.txt
  example/monteCarloIntegration/CMakeLists.txt
  example/openMPSchedule/CMakeLists.txt
  example/parallelLoopPatterns/CMakeLists.txt
  example/randomCells2D/CMakeLists.txt
  example/randomStrategies/CMakeLists.txt
  example/reduce/CMakeLists.txt
  example/tagSpecialization/CMakeLists.txt
  example/vectorAdd/CMakeLists.txt
  script/gitlabci/job_analysis.yml
  script/gitlabci/job_clang.yml
  script/gitlabci/job_cuda.yml
  script/install_boost.sh
  script/job_generator/versions.py
  script/readme_generator/supported_compilers.json
  test/CMakeLists.txt
  test/analysis/CMakeLists.txt
  test/common/CMakeLists.txt
  test/integ/CMakeLists.txt
  test/unit/CMakeLists.txt
Labels: Type:Refactoring

#2408 merge 1.2.0 release changes back to develop
  .zenodo.json
  CHANGELOG.md
Labels: Type:Documentation

#2403 implement alpaka::concepts::Tag
  .github/workflows/ci.yml
  example/bufferCopy/src/bufferCopy.cpp
  example/complex/src/complex.cpp
  example/conv2DWithMdspan/src/conv2DWithMdspan.cpp
  example/convolution1D/src/convolution1D.cpp
  example/convolution2D/src/convolution2D.cpp
  example/counterBasedRng/src/counterBasedRng.cpp
  example/heatEquation/src/heatEquation.cpp
  example/heatEquation2D/src/heatEquation2D.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/kernelSpecialization/src/kernelSpecialization.cpp
  example/matrixMulWithMdspan/src/matrixMulMdSpan.cpp
  example/monteCarloIntegration/src/monteCarloIntegration.cpp
  example/parallelLoopPatterns/src/parallelLoopPatterns.cpp
  example/randomCells2D/src/randomCells2D.cpp
  example/randomStrategies/src/randomStrategies.cpp
  example/tagSpecialization/src/tagSpecialization.cpp
  example/vectorAdd/src/vectorAdd.cpp
  include/alpaka/acc/AccGenericSycl.hpp
  include/alpaka/acc/Tag.hpp
  include/alpaka/acc/TagAccIsEnabled.hpp
  include/alpaka/dev/DevGenericSycl.hpp
  include/alpaka/event/EventGenericSycl.hpp
  include/alpaka/kernel/TaskKernelGenericSycl.hpp
  include/alpaka/mem/buf/BufGenericSycl.hpp
  include/alpaka/mem/buf/sycl/Copy.hpp
  include/alpaka/mem/global/DeviceGlobalCpu.hpp
  include/alpaka/mem/global/DeviceGlobalUniformCudaHipBuiltIn.hpp
  include/alpaka/mem/global/Traits.hpp
  include/alpaka/mem/view/ViewPlainPtr.hpp
  include/alpaka/platform/PlatformGenericSycl.hpp
  include/alpaka/queue/QueueGenericSyclBlocking.hpp
  include/alpaka/queue/QueueGenericSyclNonBlocking.hpp
  include/alpaka/queue/sycl/QueueGenericSyclBase.hpp
  include/alpaka/test/event/EventHostManualTrigger.hpp
  include/alpaka/test/queue/Queue.hpp
  script/gitlabci/job_clang.yml
  script/job_generator/versions.py
  test/common/devCompileOptions.cmake
  test/unit/acc/src/AccTagTest.cpp
  test/unit/idx/src/MapIdxPitchBytes.cpp
Labels: Type:Enhancement, Type:Refactoring

#2411 Prints Acc tags of tags-tuple at runtime
  example/bufferCopy/src/bufferCopy.cpp
  example/complex/src/complex.cpp
  example/conv2DWithMdspan/src/conv2DWithMdspan.cpp
  example/convolution1D/src/convolution1D.cpp
  example/convolution2D/src/convolution2D.cpp
  example/counterBasedRng/src/counterBasedRng.cpp
  example/heatEquation/src/heatEquation.cpp
  example/heatEquation2D/src/heatEquation2D.cpp
  example/helloWorld/src/helloWorld.cpp
  example/helloWorldLambda/src/helloWorldLambda.cpp
  example/kernelSpecialization/src/kernelSpecialization.cpp
  example/matrixMulWithMdspan/src/matrixMulMdSpan.cpp
  example/monteCarloIntegration/src/monteCarloIntegration.cpp
  example/parallelLoopPatterns/src/parallelLoopPatterns.cpp
  example/randomCells2D/src/randomCells2D.cpp
  example/randomStrategies/src/randomStrategies.cpp
  example/tagSpecialization/src/tagSpecialization.cpp
  example/vectorAdd/src/vectorAdd.cpp
  include/alpaka/acc/Tag.hpp
Labels: Type:Bug

#2412 call job_generator.py only one time to generate all job yaml files
  .gitlab-ci.yml
  script/job_generator/generate_job_yaml.py
  script/job_generator/job_generator.py
Labels: Type:Enhancement, Type:Testing
