Repository alpaka-group/alpaka, pull requests merged in 2025-06, with the labels that each got.

#2475 Add ConstBuf
  CONTRIBUTING.md
  include/alpaka/alpaka.hpp
  include/alpaka/dev/DevCpu.hpp
  include/alpaka/dev/DevGenericSycl.hpp
  include/alpaka/dev/DevUniformCudaHipRt.hpp
  include/alpaka/mem/buf/BufCpu.hpp
  include/alpaka/mem/buf/BufUniformCudaHipRt.hpp
  include/alpaka/mem/buf/Traits.hpp
  include/alpaka/mem/buf/cpu/BufCpu.hpp
  include/alpaka/mem/buf/cpu/BufCpuImpl.hpp
  include/alpaka/mem/buf/cpu/ConstBufCpu.hpp
  include/alpaka/mem/buf/cpu/traits/BufCpuTraits.hpp
  include/alpaka/mem/buf/cpu/traits/ConstBufCpuTraits.hpp
  include/alpaka/mem/buf/sycl/BufGenericSycl.hpp
  include/alpaka/mem/buf/sycl/BufGenericSyclImpl.hpp
  include/alpaka/mem/buf/sycl/ConstBufGenericSycl.hpp
  include/alpaka/mem/buf/sycl/specializations/BufCpuSycl.hpp
  include/alpaka/mem/buf/sycl/specializations/BufFpgaSyclIntel.hpp
  include/alpaka/mem/buf/sycl/specializations/BufGpuSyclIntel.hpp
  include/alpaka/mem/buf/sycl/traits/BufGenericSyclTraits.hpp
  include/alpaka/mem/buf/sycl/traits/ConstBufGenericSyclTraits.hpp
  include/alpaka/mem/buf/uniformCudaHip/BufUniformCudaHipRt.hpp
  include/alpaka/mem/buf/uniformCudaHip/BufUniformCudaHipRtImpl.hpp
  include/alpaka/mem/buf/uniformCudaHip/ConstBufUniformCudaHipRt.hpp
  include/alpaka/mem/buf/uniformCudaHip/specializations/BufCudaRt.hpp
  include/alpaka/mem/buf/uniformCudaHip/specializations/BufHipRt.hpp
  include/alpaka/mem/buf/uniformCudaHip/traits/BufUniformCudaHipRtTraits.hpp
  include/alpaka/mem/buf/uniformCudaHip/traits/ConstBufUniformCudaHipRtTraits.hpp
  test/integ/matMul/src/matMul.cpp
  test/unit/mem/buf/src/ConstBufTest.cpp
Labels: Type:Enhancement

#2509 Change attribute intel::reqd_sub_group_size to sycl::reqd_sub_group_size
  include/alpaka/kernel/TaskKernelGenericSycl.hpp
Labels: Type:Warning, Backend:SYCL

#2518 update zenodoo file
  .zenodo.json
Labels: Type:Documentation

#2522 [1.3] Update Ubuntu 20.04 images in GitHub Actions
  .github/workflows/ci.yml
Labels: Type:Testing

#2528 [1.3] Change attribute `intel::reqd_sub_group_size` to `sycl::reqd_sub_group_size`
  include/alpaka/kernel/TaskKernelGenericSycl.hpp
Labels: Type:Warning, Backend:SYCL

#2533 Fix PR description in the changlog
  CHANGELOG.md
Labels: Type:Documentation

#2535 [1.3] Add missing #includes for SYCL tags
  include/alpaka/mem/buf/BufCpuSycl.hpp
  include/alpaka/mem/buf/BufFpgaSyclIntel.hpp
  include/alpaka/mem/buf/BufGpuSyclIntel.hpp
  include/alpaka/mem/global/DeviceGlobalGenericSycl.hpp
  include/alpaka/platform/PlatformCpuSycl.hpp
  include/alpaka/platform/PlatformFpgaSyclIntel.hpp
  include/alpaka/platform/PlatformGpuSyclIntel.hpp
Labels: Type:Bug, Backend:SYCL

#2534 Add missing #includes for SYCL tags
  include/alpaka/mem/buf/sycl/specializations/BufCpuSycl.hpp
  include/alpaka/mem/buf/sycl/specializations/BufFpgaSyclIntel.hpp
  include/alpaka/mem/buf/sycl/specializations/BufGpuSyclIntel.hpp
  include/alpaka/mem/global/DeviceGlobalGenericSycl.hpp
  include/alpaka/platform/PlatformCpuSycl.hpp
  include/alpaka/platform/PlatformFpgaSyclIntel.hpp
  include/alpaka/platform/PlatformGpuSyclIntel.hpp
Labels: Type:Bug, Backend:SYCL

#2525 [1.3] `alpaka::math` custom implementations for CPU backend
  include/alpaka/core/BitCast.hpp
  include/alpaka/math/MathStdLib.hpp
  test/unit/math/src/DataGen.hpp
  test/unit/math/src/TestTemplate.hpp
Labels: Type:Bug
